"""Aprovisionamiento y ciclo de vida de cuentas contra un PostgreSQL 16 real (SCRUM-97).

Se omite salvo que este definida ``SCRUM97_TEST_DATABASE_URL``. Nunca cae por
omision sobre ``DATABASE_URL``: esta suite hace **commits reales**, ejecuta DDL y
provoca carreras, y no puede terminar sobre la base de desarrollo de nadie. El
workflow de CI convierte la omision en un job en rojo.

**Aislamiento: bases temporales propias.** Igual que SCRUM-69 y SCRUM-70, usa el
servidor solo como conexion de mantenimiento: crea bases con prefijo
``scrum97_tmp_``, las migra, carga el dataset canonico, escribe de verdad y las
elimina al terminar. Solo elimina las que ella creo.

**El dataset canonico no se toca.** Sus 30 pacientes y 5 medicos ya tienen su
cuenta, asi que no queda ningun perfil libre que provisionar. Las pruebas que lo
necesitan crean, **solo dentro de su base temporal**, una paciente y un medico
ficticios adicionales sin cuenta (cedula ``SIM-PAC-S97-...``), y provisionan
``paciente31@example.com`` y ``medico06@example.com``. Ningun vinculo canonico se
borra para fabricar el escenario, y esos perfiles no forman parte del dataset.

Lo que se comprueba con filas reales y no con dobles: las restricciones y el
trigger diferido de la revision ``54053d46abd6``, la migracion sobre una base
limpia y sobre una con las 37 cuentas, la provision atomica, el hash Argon2id,
el login de la cuenta nueva, la desactivacion con un token emitido antes, la
reactivacion de la misma identidad, la preservacion de la historia clinica, la
continuidad entre embarazos y seis carreras con conexiones independientes.

Todos los datos son simulados y completamente ficticios.
"""

from __future__ import annotations

import itertools
import json
import logging
import os
import re
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Any, Callable

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi import Request
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.exc import DBAPIError, IntegrityError
from sqlalchemy.orm import Session
from sqlalchemy.pool import NullPool

from app.api.dependencias import get_db_auditoria, obtener_configuracion_jwt
from app.config import ConfiguracionJWT, settings
from app.db.base import SCHEMA_OPERACIONAL as O
from app.db.session import get_db
from app.etl.ejecucion import ejecutar_etl
from app.loader.dataset import validar_dataset
from app.loader.postgres import cargar_dataset, preflight
from app.main import app
from app.services import auditoria as servicio_auditoria
from app.services import cuentas as servicio_cuentas
from app.services.auditoria import AccionAuditada
from app.services.cuentas import RESTRICCION_ROL_VINCULO
from app.services.passwords import PREFIJO_ARGON2ID, verificar
from tests.conftest import construir_config_alembic
from tests.test_generate_mock_data import cargar_generador

VARIABLE_DE_ENTORNO = "SCRUM97_TEST_DATABASE_URL"
PREFIJO_DE_BASE = "scrum97_tmp_"
PATRON_DE_BASE = re.compile(r"^scrum97_tmp_[0-9a-f]{8}_[a-z0-9_]{1,30}$")

pytestmark = pytest.mark.skipif(
    not os.environ.get(VARIABLE_DE_ENTORNO),
    reason=(
        f"Define {VARIABLE_DE_ENTORNO} apuntando a un servidor PostgreSQL donde "
        "el rol pueda crear bases temporales para validar el ciclo de cuentas."
    ),
)

SECRETO = "secreto-ficticio-de-la-suite-postgresql-de-scrum97"
CONFIGURACION = ConfiguracionJWT(secreto=SECRETO, expiracion=timedelta(minutes=30))

REVISION_SCRUM_97 = "54053d46abd6"
REVISION_ANALITICA = "60facdbacf51"

RUTA_TOKEN = "/api/v1/autenticacion/token"
RUTA_YO = "/api/v1/autenticacion/yo"
RUTA_PACIENTE = "/api/v1/cuentas/pacientes/{}"
RUTA_MEDICO = "/api/v1/cuentas/medicos/{}"
RUTA_ESTADO = "/api/v1/cuentas/{}/estado"

EMAIL_ADMIN = "admin01@example.com"
EMAIL_ADMIN_2 = "admin02@example.com"
EMAIL_PACIENTE_CANONICA = "paciente01@example.com"
EMAIL_MEDICO_CANONICO = "medico01@example.com"
EMAIL_PACIENTE_NUEVA = "paciente31@example.com"
EMAIL_MEDICO_NUEVO = "medico06@example.com"
PASSWORD_NUEVA = "Clave-Simulada-SCRUM97-7731"

CONTEOS_CANONICOS = {
    "usuario": 37,
    "usuario_paciente": 30,
    "usuario_medico": 5,
    "paciente": 30,
    "medico": 5,
    "embarazo": 30,
    "sesion_monitoreo": 732,
    "lectura_biometrica": 1180,
}
ROLES_CANONICOS = {"ADMIN": 2, "MEDICO": 5, "PACIENTE": 30}

TRIGGERS = {
    "trg_usuario_rol_vinculo": "usuario",
    "trg_usuario_paciente_rol_vinculo": "usuario_paciente",
    "trg_usuario_medico_rol_vinculo": "usuario_medico",
}

CONTADOR = itertools.count(1)

# Limites de las conexiones que compiten: una carrera mal sincronizada falla por
# tiempo, no deja el CI colgado.
OPCIONES_DE_LIMITE = "-c lock_timeout=20000 -c statement_timeout=60000"
TIEMPO_MAXIMO_DE_ESPERA = 20.0
CABECERA_PARTICIPANTE = "X-Participante-De-Prueba"


# ---------------------------------------------------------------------------
# Servidor y bases temporales
# ---------------------------------------------------------------------------


class ServidorDePruebas:
    """Crea y elimina bases temporales; nunca toca una que no haya creado."""

    def __init__(self, url: str) -> None:
        self.url = make_url(url)
        self.ejecucion = uuid.uuid4().hex[:8]
        self.engine = create_engine(url, isolation_level="AUTOCOMMIT", poolclass=NullPool)
        self.creadas: list[str] = []

    def _citar(self, nombre: str) -> str:
        return self.engine.dialect.identifier_preparer.quote(nombre)

    def url_de(self, nombre: str) -> str:
        return self.url.set(database=nombre).render_as_string(hide_password=False)

    def crear(self, sufijo: str, *, plantilla: str | None = None) -> str:
        nombre = f"{PREFIJO_DE_BASE}{self.ejecucion}_{sufijo}"
        assert PATRON_DE_BASE.match(nombre), nombre
        sentencia = f"CREATE DATABASE {self._citar(nombre)}"
        if plantilla is not None:
            assert plantilla in self.creadas
            sentencia += f" TEMPLATE {self._citar(plantilla)}"
        with self.engine.connect() as conexion:
            conexion.execute(text(sentencia))
        self.creadas.append(nombre)
        return nombre

    def eliminar(self, nombre: str) -> None:
        if nombre not in self.creadas or not PATRON_DE_BASE.match(nombre):
            raise AssertionError(f"Se rechaza eliminar una base no creada aqui: {nombre}")
        with self.engine.connect() as conexion:
            conexion.execute(
                text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :nombre AND pid <> pg_backend_pid()"
                ),
                {"nombre": nombre},
            )
            conexion.execute(text(f"DROP DATABASE {self._citar(nombre)}"))
        self.creadas.remove(nombre)


class BaseTemporal:
    def __init__(self, nombre: str, url: str) -> None:
        self.nombre = nombre
        self.url = url
        self.engine = create_engine(url, poolclass=NullPool)

    def escalar(self, sql: str, **parametros: Any) -> Any:
        with self.engine.connect() as conexion:
            return conexion.execute(text(sql), parametros).scalar()

    def filas(self, sql: str, **parametros: Any) -> list:
        with self.engine.connect() as conexion:
            return list(conexion.execute(text(sql), parametros))

    def escribir(self, sql: str, **parametros: Any) -> Any:
        with self.engine.begin() as conexion:
            resultado = conexion.execute(text(sql), parametros)
            return resultado.scalar() if resultado.returns_rows else None


def migrar(url: str, destino: str) -> None:
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(settings, "database_url", url)
        command.upgrade(construir_config_alembic(), destino)


def revertir(url: str, destino: str) -> None:
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(settings, "database_url", url)
        command.downgrade(construir_config_alembic(), destino)


def diferencias_de_alembic(url: str) -> str | None:
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(settings, "database_url", url)
        try:
            command.check(construir_config_alembic())
        except AutogenerateDiffsDetected as error:
            return str(error)
    return None


def cargar(url: str, dataset, *, revision: str | None = None):
    """Carga el dataset. Con ``revision`` se omite el preflight (base anterior)."""
    engine = create_engine(url, poolclass=NullPool)
    try:
        if revision is None:
            with engine.connect() as conexion:
                revision = preflight(conexion)
        with engine.begin() as conexion:
            return cargar_dataset(conexion, dataset, revision=revision)
    finally:
        engine.dispose()


@pytest.fixture(scope="session")
def servidor():
    url = os.environ[VARIABLE_DE_ENTORNO]
    if not make_url(url).get_backend_name().startswith("postgresql"):
        pytest.fail(f"{VARIABLE_DE_ENTORNO} debe apuntar a PostgreSQL.")

    servidor = ServidorDePruebas(url)
    try:
        yield servidor
    finally:
        for nombre in reversed(list(servidor.creadas)):
            servidor.eliminar(nombre)
        servidor.engine.dispose()


@pytest.fixture(scope="session")
def generador():
    return cargar_generador()


@pytest.fixture(scope="session")
def dataset_canonico(tmp_path_factory, generador):
    carpeta = tmp_path_factory.mktemp("dataset_scrum97")
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(generador, "CARPETA_SALIDA", carpeta)
        generador.main()
    return validar_dataset(
        json.loads((carpeta / "dataset_fetalalert.json").read_text(encoding="utf-8"))
    )


@pytest.fixture(scope="session")
def password_canonica(generador) -> str:
    return generador.PASSWORD_SIMULADA


@pytest.fixture(scope="session")
def plantilla(servidor, dataset_canonico) -> str:
    """Base en head con el dataset canonico y ``auditoria_log`` vacia."""
    nombre = servidor.crear("plantilla")
    url = servidor.url_de(nombre)
    migrar(url, "head")
    cargar(url, dataset_canonico)
    return nombre


@pytest.fixture(scope="session")
def plantilla_previa(servidor, dataset_canonico) -> str:
    """Base existente antes de SCRUM-97: revision analitica y las 37 cuentas."""
    nombre = servidor.crear("plantilla_previa")
    url = servidor.url_de(nombre)
    migrar(url, REVISION_ANALITICA)
    cargar(url, dataset_canonico, revision=REVISION_ANALITICA)
    return nombre


@contextmanager
def clon_de(servidor, plantilla_nombre: str | None):
    nombre = servidor.crear(f"c{next(CONTADOR)}", plantilla=plantilla_nombre)
    base = BaseTemporal(nombre, servidor.url_de(nombre))
    try:
        yield base
    finally:
        base.engine.dispose()
        servidor.eliminar(nombre)


@pytest.fixture
def base(servidor, plantilla):
    with clon_de(servidor, plantilla) as temporal:
        yield temporal


@pytest.fixture
def base_previa(servidor, plantilla_previa):
    with clon_de(servidor, plantilla_previa) as temporal:
        yield temporal


@pytest.fixture
def base_vacia(servidor):
    with clon_de(servidor, None) as temporal:
        yield temporal


# ---------------------------------------------------------------------------
# API sobre la base temporal
# ---------------------------------------------------------------------------


@contextmanager
def api_sobre(base: BaseTemporal):
    """La aplicacion real, con sus dos sesiones -- distintas -- atadas a la base."""

    def sesion_negocio():
        with Session(bind=base.engine, autoflush=False) as sesion_bd:
            yield sesion_bd

    def sesion_auditoria():
        with Session(bind=base.engine, autoflush=False) as sesion_bd:
            yield sesion_bd

    app.dependency_overrides[get_db] = sesion_negocio
    app.dependency_overrides[get_db_auditoria] = sesion_auditoria
    app.dependency_overrides[obtener_configuracion_jwt] = lambda: CONFIGURACION
    try:
        yield TestClient(app, raise_server_exceptions=False)
    finally:
        app.dependency_overrides.clear()


@pytest.fixture
def cliente(base):
    with api_sobre(base) as cliente:
        yield cliente


def bearer(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def iniciar_sesion(cliente, email: str, password: str) -> str:
    respuesta = cliente.post(RUTA_TOKEN, json={"email": email, "password": password})
    assert respuesta.status_code == 200, respuesta.text
    return respuesta.json()["access_token"]


@pytest.fixture
def token_admin(cliente, password_canonica) -> str:
    return iniciar_sesion(cliente, EMAIL_ADMIN, password_canonica)


def id_de_cuenta(base: BaseTemporal, email: str) -> int:
    return base.escalar(f"SELECT id_usuario FROM {O}.usuario WHERE email = :e", e=email)


# ---------------------------------------------------------------------------
# Perfiles libres: solo en la base temporal
# ---------------------------------------------------------------------------


def crear_paciente_libre(base: BaseTemporal, numero: int = 31) -> int:
    return base.escribir(
        f"INSERT INTO {O}.paciente (cedula, primer_nombre, apellido_paterno,"
        " apellido_materno, email_pac, fecha_nac)"
        " VALUES (:cedula, :nombre, 'Simulada', 'SCRUM97', :email, :nacimiento)"
        " RETURNING id_paciente",
        cedula=f"SIM-PAC-S97-{numero:03d}",
        nombre=f"Gestante{numero:02d}",
        email=f"paciente{numero:02d}@example.com",
        nacimiento=date(1996, 4, 18),
    )


def crear_medico_libre(base: BaseTemporal, numero: int = 6) -> int:
    return base.escribir(
        f"INSERT INTO {O}.medico (id_especialidad, primer_nombre, apellido_paterno,"
        " apellido_materno, email_med)"
        f" VALUES ((SELECT min(id_especialidad) FROM {O}.especialidad), :nombre,"
        " 'Simulado', 'SCRUM97', :email) RETURNING id_medico",
        nombre=f"Medico{numero:02d}",
        email=f"medico{numero:02d}@example.com",
    )


def provisionar_paciente(cliente, token, id_paciente, email=EMAIL_PACIENTE_NUEVA):
    return cliente.post(
        RUTA_PACIENTE.format(id_paciente),
        json={"email": email, "password": PASSWORD_NUEVA},
        headers=bearer(token),
    )


def provisionar_medico(cliente, token, id_medico, email=EMAIL_MEDICO_NUEVO):
    return cliente.post(
        RUTA_MEDICO.format(id_medico),
        json={"email": email, "password": PASSWORD_NUEVA},
        headers=bearer(token),
    )


def cambiar_estado(cliente, token, id_usuario, activo: bool):
    return cliente.patch(
        RUTA_ESTADO.format(id_usuario), json={"activo": activo}, headers=bearer(token)
    )


# ---------------------------------------------------------------------------
# Observacion
# ---------------------------------------------------------------------------


def conteos(base: BaseTemporal) -> dict[str, int]:
    return {tabla: base.escalar(f"SELECT count(*) FROM {O}.{tabla}") for tabla in CONTEOS_CANONICOS}


def roles(base: BaseTemporal) -> dict[str, int]:
    return {
        fila.nombre_rol: fila.total
        for fila in base.filas(
            f"SELECT r.nombre_rol, count(*) AS total FROM {O}.usuario u"
            f" JOIN {O}.rol r ON r.id_rol = u.id_rol GROUP BY r.nombre_rol"
        )
    }


def cuentas_incoherentes(base: BaseTemporal) -> int:
    """Cuentas cuyo rol no tiene exactamente su vinculo. Siempre debe ser 0."""
    return base.escalar(
        f"SELECT count(*) FROM {O}.usuario u JOIN {O}.rol r ON r.id_rol = u.id_rol"
        " WHERE NOT ("
        f" (r.nombre_rol = 'PACIENTE' AND (SELECT count(*) FROM {O}.usuario_paciente p WHERE p.id_usuario = u.id_usuario) = 1"
        f"  AND (SELECT count(*) FROM {O}.usuario_medico m WHERE m.id_usuario = u.id_usuario) = 0)"
        f" OR (r.nombre_rol = 'MEDICO' AND (SELECT count(*) FROM {O}.usuario_paciente p WHERE p.id_usuario = u.id_usuario) = 0"
        f"  AND (SELECT count(*) FROM {O}.usuario_medico m WHERE m.id_usuario = u.id_usuario) = 1)"
        f" OR (r.nombre_rol = 'ADMIN' AND (SELECT count(*) FROM {O}.usuario_paciente p WHERE p.id_usuario = u.id_usuario) = 0"
        f"  AND (SELECT count(*) FROM {O}.usuario_medico m WHERE m.id_usuario = u.id_usuario) = 0))"
    )


def auditoria_de(base: BaseTemporal) -> list:
    return base.filas(
        f"SELECT id_log, id_usuario, accion, nombre_entidad_afectada,"
        f" id_entidad_afectada, ip_origen, fecha_hora FROM {O}.auditoria_log ORDER BY id_log"
    )


def acciones_sobre(base: BaseTemporal, id_usuario: int) -> list[str]:
    return [
        fila.accion
        for fila in auditoria_de(base)
        if fila.nombre_entidad_afectada == "usuario"
        and fila.id_entidad_afectada == str(id_usuario)
        and fila.accion.startswith("CUENTA_")
    ]


def huella(base: BaseTemporal, tabla: str, filtro: str = "") -> str:
    return base.escalar(
        "SELECT md5(coalesce(string_agg(t::text, '|' ORDER BY t::text), ''))"
        f" FROM {tabla} t {filtro}"
    )


def revision_de(base: BaseTemporal) -> str:
    return base.escalar("SELECT version_num FROM alembic_version")


def triggers_de(base: BaseTemporal) -> dict[str, tuple[str, bool, bool]]:
    return {
        fila.tgname: (fila.tabla, fila.tgdeferrable, fila.tginitdeferred)
        for fila in base.filas(
            "SELECT t.tgname, c.relname AS tabla, t.tgdeferrable, t.tginitdeferred"
            " FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid"
            " JOIN pg_namespace n ON n.oid = c.relnamespace"
            " WHERE n.nspname = :esquema AND NOT t.tgisinternal",
            esquema=O,
        )
    }


def existe_funcion(base: BaseTemporal) -> bool:
    return bool(
        base.escalar(
            "SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace"
            " WHERE n.nspname = :esquema AND p.proname = 'validar_rol_vinculo_usuario'",
            esquema=O,
        )
    )


def existe_check_email(base: BaseTemporal) -> bool:
    return bool(
        base.escalar(
            "SELECT count(*) FROM pg_constraint WHERE conname = 'ck_usuario_email_canonico'"
        )
    )


def error_de_commit(base: BaseTemporal, *sentencias: str) -> DBAPIError | None:
    """Ejecuta las sentencias en una transaccion y devuelve el error del commit, si hay."""
    try:
        with base.engine.begin() as conexion:
            for sentencia in sentencias:
                conexion.execute(text(sentencia))
    except DBAPIError as error:
        return error
    return None


def restriccion_de(error: DBAPIError) -> tuple[str | None, str | None]:
    original = error.orig
    return getattr(original, "sqlstate", None), getattr(original.diag, "constraint_name", None)


# ---------------------------------------------------------------------------
# 1. Linea base: el dataset canonico sigue intacto
# ---------------------------------------------------------------------------


def test_conteos_canonicos_intactos(base):
    assert conteos(base) == CONTEOS_CANONICOS
    assert roles(base) == ROLES_CANONICOS
    assert cuentas_incoherentes(base) == 0


def test_el_dataset_canonico_no_tiene_perfiles_libres(base):
    assert base.escalar(
        f"SELECT count(*) FROM {O}.paciente p WHERE NOT EXISTS"
        f" (SELECT 1 FROM {O}.usuario_paciente up WHERE up.id_paciente = p.id_paciente)"
    ) == 0
    assert base.escalar(
        f"SELECT count(*) FROM {O}.medico m WHERE NOT EXISTS"
        f" (SELECT 1 FROM {O}.usuario_medico um WHERE um.id_medico = m.id_medico)"
    ) == 0


def test_los_correos_del_dataset_ya_son_canonicos(base):
    assert base.escalar(
        f"SELECT count(*) FROM {O}.usuario WHERE email <> lower(btrim(email))"
    ) == 0


# ---------------------------------------------------------------------------
# 2. Migracion
# ---------------------------------------------------------------------------


def test_una_sola_cabeza_sobre_la_revision_analitica():
    script = ScriptDirectory.from_config(construir_config_alembic())

    assert script.get_heads() == [REVISION_SCRUM_97]
    assert script.get_revision(REVISION_SCRUM_97).down_revision == REVISION_ANALITICA


def test_base_limpia_upgrade_downgrade_upgrade_y_check(base_vacia):
    migrar(base_vacia.url, "head")
    assert revision_de(base_vacia) == REVISION_SCRUM_97
    assert existe_check_email(base_vacia) and existe_funcion(base_vacia)
    assert set(triggers_de(base_vacia)) == set(TRIGGERS)

    revertir(base_vacia.url, "base")
    assert O not in {f[0] for f in base_vacia.filas("SELECT nspname FROM pg_namespace")}

    migrar(base_vacia.url, "head")
    assert revision_de(base_vacia) == REVISION_SCRUM_97
    assert diferencias_de_alembic(base_vacia.url) is None


def test_los_triggers_son_diferibles_e_inicialmente_diferidos(base):
    assert triggers_de(base) == {
        nombre: (tabla, True, True) for nombre, tabla in TRIGGERS.items()
    }


def test_base_existente_con_37_cuentas_upgrade_downgrade_upgrade(base_previa):
    assert revision_de(base_previa) == REVISION_ANALITICA
    antes = conteos(base_previa)
    usuarios_antes = huella(base_previa, f"{O}.usuario")
    vinculos_antes = huella(base_previa, f"{O}.usuario_paciente") + huella(base_previa, f"{O}.usuario_medico")
    assert antes == CONTEOS_CANONICOS
    assert not existe_check_email(base_previa) and not existe_funcion(base_previa)

    migrar(base_previa.url, "head")
    assert revision_de(base_previa) == REVISION_SCRUM_97
    assert conteos(base_previa) == antes
    assert huella(base_previa, f"{O}.usuario") == usuarios_antes
    assert set(triggers_de(base_previa)) == set(TRIGGERS)

    revertir(base_previa.url, REVISION_ANALITICA)
    assert revision_de(base_previa) == REVISION_ANALITICA
    assert triggers_de(base_previa) == {}
    assert not existe_check_email(base_previa) and not existe_funcion(base_previa)
    assert conteos(base_previa) == antes
    assert huella(base_previa, f"{O}.usuario") == usuarios_antes

    migrar(base_previa.url, "head")
    assert conteos(base_previa) == antes
    assert (
        huella(base_previa, f"{O}.usuario_paciente") + huella(base_previa, f"{O}.usuario_medico")
        == vinculos_antes
    )
    assert diferencias_de_alembic(base_previa.url) is None


def test_la_migracion_normaliza_correos_existentes(base_previa, password_canonica):
    base_previa.escribir(
        f"UPDATE {O}.usuario SET email = :sucio WHERE email = :limpio",
        sucio="  Admin01@Example.COM ",
        limpio=EMAIL_ADMIN,
    )

    migrar(base_previa.url, "head")

    assert id_de_cuenta(base_previa, EMAIL_ADMIN) is not None
    assert base_previa.escalar(
        f"SELECT count(*) FROM {O}.usuario WHERE email <> lower(email)"
    ) == 0
    with api_sobre(base_previa) as cliente:
        iniciar_sesion(cliente, "ADMIN01@example.com", password_canonica)


@pytest.mark.parametrize(
    "preparacion",
    [
        (f"UPDATE {O}.usuario SET email = 'Paciente01@Example.com' WHERE email = 'paciente02@example.com'",),
        (f"UPDATE {O}.usuario SET email = 'paciente 02@example.com' WHERE email = 'paciente02@example.com'",),
        (f"UPDATE {O}.usuario SET email = '   ' WHERE email = 'paciente02@example.com'",),
        (
            f"DELETE FROM {O}.usuario_paciente WHERE id_usuario ="
            f" (SELECT id_usuario FROM {O}.usuario WHERE email = 'paciente02@example.com')",
        ),
        (
            f"UPDATE {O}.usuario SET id_rol = (SELECT id_rol FROM {O}.rol WHERE nombre_rol = 'ADMIN')"
            " WHERE email = 'medico02@example.com'",
        ),
    ],
    ids=["colision", "espacio-interno", "vacio", "paciente-sin-vinculo", "admin-con-vinculo"],
)
def test_la_migracion_aborta_sin_modificar_nada(base_previa, preparacion):
    for sentencia in preparacion:
        base_previa.escribir(sentencia)
    usuarios = huella(base_previa, f"{O}.usuario")
    vinculos = huella(base_previa, f"{O}.usuario_paciente") + huella(base_previa, f"{O}.usuario_medico")

    with pytest.raises(DBAPIError) as error:
        migrar(base_previa.url, "head")

    assert "SCRUM-97" in str(error.value.orig)
    assert "@example.com" not in str(error.value.orig)
    assert revision_de(base_previa) == REVISION_ANALITICA
    assert huella(base_previa, f"{O}.usuario") == usuarios
    assert (
        huella(base_previa, f"{O}.usuario_paciente") + huella(base_previa, f"{O}.usuario_medico")
        == vinculos
    )
    assert not existe_check_email(base_previa)
    assert not existe_funcion(base_previa)


def test_el_loader_sigue_siendo_idempotente(base_vacia, dataset_canonico):
    migrar(base_vacia.url, "head")

    primera = cargar(base_vacia.url, dataset_canonico)
    segunda = cargar(base_vacia.url, dataset_canonico)

    assert primera.insertados > 0
    assert segunda.insertados == 0
    assert segunda.existentes == primera.total
    assert conteos(base_vacia) == CONTEOS_CANONICOS
    assert roles(base_vacia) == ROLES_CANONICOS
    assert cuentas_incoherentes(base_vacia) == 0


def test_el_check_de_correo_rechaza_formas_no_canonicas(base):
    for valor in ("Paciente01@example.com", " paciente01@example.com", "a b@example.com", ""):
        error = error_de_commit(
            base,
            f"UPDATE {O}.usuario SET email = '{valor}' WHERE email = '{EMAIL_PACIENTE_CANONICA}'",
        )
        assert isinstance(error, IntegrityError), valor
        assert restriccion_de(error) == ("23514", "ck_usuario_email_canonico")


# ---------------------------------------------------------------------------
# 3. Invariante rol <-> vinculo, directamente en SQL
# ---------------------------------------------------------------------------

ID_ROL = "(SELECT id_rol FROM " + O + ".rol WHERE nombre_rol = '{}')"
CUENTA = "(SELECT id_usuario FROM " + O + ".usuario WHERE email = '{}')"


def test_una_cuenta_y_su_vinculo_en_la_misma_transaccion_se_aceptan(base):
    id_paciente = crear_paciente_libre(base)

    error = error_de_commit(
        base,
        f"INSERT INTO {O}.usuario (id_rol, email, password_hash, activo)"
        f" VALUES ({ID_ROL.format('PACIENTE')}, 'directa@example.com', 'x', true)",
        f"INSERT INTO {O}.usuario_paciente (id_usuario, id_paciente)"
        f" VALUES ({CUENTA.format('directa@example.com')}, {id_paciente})",
    )

    assert error is None
    assert cuentas_incoherentes(base) == 0


@pytest.mark.parametrize(
    "sentencias",
    [
        # Cuenta clinica sin vinculo al commit.
        (
            f"INSERT INTO {O}.usuario (id_rol, email, password_hash, activo)"
            f" VALUES ({ID_ROL.format('PACIENTE')}, 'huerfana@example.com', 'x', true)",
        ),
        # La misma cuenta en ambos bridges.
        (
            f"INSERT INTO {O}.usuario_medico (id_usuario, id_medico)"
            f" VALUES ({CUENTA.format(EMAIL_PACIENTE_CANONICA)}, {{id_medico}})",
        ),
        # Rol incompatible con el bridge.
        (
            f"DELETE FROM {O}.usuario_paciente WHERE id_usuario = {CUENTA.format(EMAIL_PACIENTE_CANONICA)}",
            f"INSERT INTO {O}.usuario_medico (id_usuario, id_medico)"
            f" VALUES ({CUENTA.format(EMAIL_PACIENTE_CANONICA)}, {{id_medico}})",
        ),
        # ADMIN con bridge.
        (
            f"INSERT INTO {O}.usuario_paciente (id_usuario, id_paciente)"
            f" VALUES ({CUENTA.format(EMAIL_ADMIN)}, {{id_paciente}})",
        ),
        # Cambio de rol que deja el bridge anterior.
        (
            f"UPDATE {O}.usuario SET id_rol = {ID_ROL.format('ADMIN')}"
            f" WHERE email = '{EMAIL_PACIENTE_CANONICA}'",
        ),
        # Borrar el bridge deja una cuenta clinica sin vinculo.
        (
            f"DELETE FROM {O}.usuario_medico WHERE id_usuario = {CUENTA.format(EMAIL_MEDICO_CANONICO)}",
        ),
    ],
    ids=[
        "clinica-sin-vinculo",
        "ambos-bridges",
        "rol-incompatible",
        "admin-con-vinculo",
        "cambio-de-rol-sin-retirar-vinculo",
        "vinculo-borrado",
    ],
)
def test_el_trigger_diferido_rechaza_estados_incoherentes(base, sentencias):
    id_paciente = crear_paciente_libre(base)
    id_medico = crear_medico_libre(base)
    antes = conteos(base)

    error = error_de_commit(
        base, *(s.format(id_medico=id_medico, id_paciente=id_paciente) for s in sentencias)
    )

    assert isinstance(error, IntegrityError)
    assert restriccion_de(error) == ("23514", RESTRICCION_ROL_VINCULO)
    assert conteos(base) == antes
    assert cuentas_incoherentes(base) == 0


def test_un_cambio_de_rol_coherente_en_una_transaccion_se_acepta(base):
    error = error_de_commit(
        base,
        f"DELETE FROM {O}.usuario_paciente WHERE id_usuario = {CUENTA.format(EMAIL_PACIENTE_CANONICA)}",
        f"UPDATE {O}.usuario SET id_rol = {ID_ROL.format('ADMIN')} WHERE email = '{EMAIL_PACIENTE_CANONICA}'",
    )

    assert error is None
    assert cuentas_incoherentes(base) == 0


def test_los_unique_de_los_bridges_siguen_vigentes(base):
    id_paciente = base.escalar(f"SELECT min(id_paciente) FROM {O}.usuario_paciente")

    error = error_de_commit(
        base,
        f"INSERT INTO {O}.usuario (id_rol, email, password_hash, activo)"
        f" VALUES ({ID_ROL.format('PACIENTE')}, 'segunda@example.com', 'x', true)",
        f"INSERT INTO {O}.usuario_paciente (id_usuario, id_paciente)"
        f" VALUES ({CUENTA.format('segunda@example.com')}, {id_paciente})",
    )

    assert restriccion_de(error) == ("23505", "uq_usuario_paciente_id_paciente")


# ---------------------------------------------------------------------------
# 4. Provision
# ---------------------------------------------------------------------------


def test_admin_provisiona_una_paciente(cliente, base, token_admin):
    id_paciente = crear_paciente_libre(base)
    id_admin = id_de_cuenta(base, EMAIL_ADMIN)

    respuesta = provisionar_paciente(cliente, token_admin, id_paciente)

    assert respuesta.status_code == 201, respuesta.text
    cuerpo = respuesta.json()
    id_usuario = cuerpo["id_usuario"]
    assert cuerpo == {"id_usuario": id_usuario, "id_paciente": id_paciente, "rol": "PACIENTE", "activo": True}

    fila = base.filas(
        f"SELECT u.email, u.password_hash, u.activo, r.nombre_rol FROM {O}.usuario u"
        f" JOIN {O}.rol r ON r.id_rol = u.id_rol WHERE u.id_usuario = :id",
        id=id_usuario,
    )[0]
    assert fila.email == EMAIL_PACIENTE_NUEVA
    assert fila.password_hash.startswith(PREFIJO_ARGON2ID)
    assert PASSWORD_NUEVA not in fila.password_hash
    assert verificar(fila.password_hash, PASSWORD_NUEVA)
    assert fila.activo is True and fila.nombre_rol == "PACIENTE"
    assert base.escalar(
        f"SELECT id_paciente FROM {O}.usuario_paciente WHERE id_usuario = :id", id=id_usuario
    ) == id_paciente

    [evento] = [f for f in auditoria_de(base) if f.accion.startswith("CUENTA_")]
    assert evento.accion == AccionAuditada.CUENTA_PACIENTE_PROVISIONADA.value
    assert evento.id_usuario == id_admin
    assert (evento.nombre_entidad_afectada, evento.id_entidad_afectada) == ("usuario", str(id_usuario))
    assert cuentas_incoherentes(base) == 0


def test_admin_provisiona_un_medico(cliente, base, token_admin):
    id_medico = crear_medico_libre(base)

    respuesta = provisionar_medico(cliente, token_admin, id_medico)

    assert respuesta.status_code == 201, respuesta.text
    id_usuario = respuesta.json()["id_usuario"]
    assert respuesta.json() == {"id_usuario": id_usuario, "id_medico": id_medico, "rol": "MEDICO", "activo": True}
    assert base.escalar(
        f"SELECT id_medico FROM {O}.usuario_medico WHERE id_usuario = :id", id=id_usuario
    ) == id_medico
    assert acciones_sobre(base, id_usuario) == [AccionAuditada.CUENTA_MEDICO_PROVISIONADA.value]
    assert roles(base) == {**ROLES_CANONICOS, "MEDICO": 6}


@pytest.mark.parametrize(
    ("email_de_login", "rol", "crear", "provisionar"),
    [
        ("Paciente31@Example.COM ", "PACIENTE", crear_paciente_libre, provisionar_paciente),
        (" MEDICO06@example.com", "MEDICO", crear_medico_libre, provisionar_medico),
    ],
    ids=["paciente", "medico"],
)
def test_la_cuenta_nueva_inicia_sesion_y_yo_devuelve_su_identidad(
    cliente, base, token_admin, email_de_login, rol, crear, provisionar
):
    id_usuario = provisionar(cliente, token_admin, crear(base)).json()["id_usuario"]

    token = iniciar_sesion(cliente, email_de_login, PASSWORD_NUEVA)

    assert cliente.get(RUTA_YO, headers=bearer(token)).json() == {"id_usuario": id_usuario, "rol": rol}


def test_el_login_canonico_funciona_para_las_cuentas_semilla(cliente, password_canonica):
    token = iniciar_sesion(cliente, "  Admin02@EXAMPLE.com ", password_canonica)

    assert cliente.get(RUTA_YO, headers=bearer(token)).json()["rol"] == "ADMIN"


@pytest.mark.parametrize(
    "email",
    [EMAIL_PACIENTE_CANONICA, "PACIENTE01@EXAMPLE.COM", "  paciente01@example.com  "],
    ids=["exacto", "mayusculas", "espacios"],
)
def test_un_correo_existente_o_equivalente_es_409(cliente, base, token_admin, email):
    id_paciente = crear_paciente_libre(base)
    antes = conteos(base)

    respuesta = provisionar_paciente(cliente, token_admin, id_paciente, email=email)

    assert respuesta.status_code == 409
    assert respuesta.json()["detail"] == servicio_cuentas.MENSAJE_EMAIL_EN_USO
    assert conteos(base) == antes
    assert [f for f in auditoria_de(base) if f.accion.startswith("CUENTA_")] == []


def test_segunda_cuenta_para_la_misma_paciente_es_409(cliente, base, token_admin):
    id_paciente = crear_paciente_libre(base)
    assert provisionar_paciente(cliente, token_admin, id_paciente).status_code == 201
    antes = conteos(base)

    respuesta = provisionar_paciente(cliente, token_admin, id_paciente, email="otra31@example.com")

    assert respuesta.status_code == 409
    assert respuesta.json()["detail"] == servicio_cuentas.MENSAJE_PERFIL_YA_VINCULADO
    assert conteos(base) == antes


def test_segunda_cuenta_para_un_medico_canonico_es_409(cliente, base, token_admin):
    id_medico = base.escalar(f"SELECT min(id_medico) FROM {O}.usuario_medico")
    antes = conteos(base)

    respuesta = provisionar_medico(cliente, token_admin, id_medico, email="otro@example.com")

    assert respuesta.status_code == 409
    assert conteos(base) == antes


@pytest.mark.parametrize("ruta", [RUTA_PACIENTE, RUTA_MEDICO])
def test_un_perfil_inexistente_es_404(cliente, base, token_admin, ruta):
    antes = conteos(base)

    respuesta = cliente.post(
        ruta.format(2_000_000_000),
        json={"email": EMAIL_PACIENTE_NUEVA, "password": PASSWORD_NUEVA},
        headers=bearer(token_admin),
    )

    assert respuesta.status_code == 404
    assert conteos(base) == antes


def test_un_fallo_entre_la_cuenta_y_el_vinculo_no_deja_huerfanos(
    cliente, base, token_admin, monkeypatch
):
    id_paciente = crear_paciente_libre(base)
    antes = conteos(base)

    def vinculo_roto(**_):
        raise RuntimeError("fallo simulado despues de insertar la cuenta")

    monkeypatch.setattr(servicio_cuentas, "UsuarioPaciente", vinculo_roto)

    respuesta = provisionar_paciente(cliente, token_admin, id_paciente)

    assert respuesta.status_code == 500
    assert conteos(base) == antes
    assert id_de_cuenta(base, EMAIL_PACIENTE_NUEVA) is None
    assert [f for f in auditoria_de(base) if f.accion.startswith("CUENTA_")] == []


def test_un_fallo_de_la_auditoria_de_exito_revierte_todo(cliente, base, token_admin, monkeypatch):
    id_paciente = crear_paciente_libre(base)
    antes = conteos(base)
    original = servicio_auditoria.registrar

    def auditoria_rota(sesion_bd, accion, **kwargs):
        if accion.value.startswith("CUENTA_"):
            raise DBAPIError("INSERT auditoria", {}, Exception("fallo simulado"))
        return original(sesion_bd, accion, **kwargs)

    monkeypatch.setattr(servicio_auditoria, "registrar", auditoria_rota)

    respuesta = provisionar_paciente(cliente, token_admin, id_paciente)

    assert respuesta.status_code == 500
    assert conteos(base) == antes
    assert id_de_cuenta(base, EMAIL_PACIENTE_NUEVA) is None


# ---------------------------------------------------------------------------
# 5. RBAC contra filas reales
# ---------------------------------------------------------------------------


ID_INEXISTENTE = 2_000_000_000
MARCADOR_PASSWORD_DENEGADA = "Marcador-Denegacion-SCRUM97-7731"
TABLAS_DE_IDENTIDAD = ("usuario", "usuario_paciente", "usuario_medico", "paciente", "medico")


def _objetivo_existente(base: BaseTemporal, ruta: str) -> tuple[int, tuple[str, ...]]:
    """Un objetivo real de cada ruta y los datos que lo identifican.

    Pacientes y medicos: un perfil libre, que un ADMIN si podria provisionar.
    Estado: una cuenta PACIENTE canonica, que un ADMIN si podria desactivar.
    """
    if ruta == "pacientes":
        return crear_paciente_libre(base), ("paciente31@example.com", "SIM-PAC-S97-031", "Gestante31")
    if ruta == "medicos":
        return crear_medico_libre(base), ("medico06@example.com", "Medico06")
    return id_de_cuenta(base, "paciente02@example.com"), ("paciente02@example.com",)


def _pedir(cliente, token: str, ruta: str, id_objetivo: int):
    cabeceras = bearer(token)
    cuerpo = {"email": f"{ruta}.denegada@example.com", "password": MARCADOR_PASSWORD_DENEGADA}
    if ruta == "pacientes":
        return cliente.post(RUTA_PACIENTE.format(id_objetivo), json=cuerpo, headers=cabeceras)
    if ruta == "medicos":
        return cliente.post(RUTA_MEDICO.format(id_objetivo), json=cuerpo, headers=cabeceras)
    return cliente.patch(RUTA_ESTADO.format(id_objetivo), json={"activo": False}, headers=cabeceras)


@pytest.mark.parametrize("ruta", ["pacientes", "medicos", "estado"])
@pytest.mark.parametrize(
    "email_actor", [EMAIL_PACIENTE_CANONICA, EMAIL_MEDICO_CANONICO], ids=["PACIENTE", "MEDICO"]
)
def test_un_no_admin_recibe_403_identico_y_queda_auditado(
    cliente, base, password_canonica, email_actor, ruta
):
    """Matriz completa actor x ruta, cada una con objetivo existente e inexistente.

    La denegacion la escribe ``exigir_roles`` de SCRUM-70, en su propia
    transaccion y antes de que el handler mire el objetivo: por eso ni la
    respuesta ni la fila de auditoria pueden distinguir un objetivo real de uno
    que no existe.
    """
    id_existente, datos_del_objetivo = _objetivo_existente(base, ruta)
    token = iniciar_sesion(cliente, email_actor, password_canonica)
    id_actor = id_de_cuenta(base, email_actor)
    ultimo_log = base.escalar(f"SELECT max(id_log) FROM {O}.auditoria_log")
    huellas = {t: huella(base, f"{O}.{t}") for t in TABLAS_DE_IDENTIDAD}
    antes = conteos(base)

    existente = _pedir(cliente, token, ruta, id_existente)
    inexistente = _pedir(cliente, token, ruta, ID_INEXISTENTE)

    assert existente.status_code == inexistente.status_code == 403
    assert existente.text == inexistente.text
    for respuesta in (existente, inexistente):
        assert "www-authenticate" not in {clave.lower() for clave in respuesta.headers}

    # Nada cambio: cuentas, estados, vinculos ni perfiles.
    assert {t: huella(base, f"{O}.{t}") for t in TABLAS_DE_IDENTIDAD} == huellas
    assert conteos(base) == antes

    # Una fila por intento, del actor, sobre ``usuario`` y sin objetivo.
    nuevas = [f for f in auditoria_de(base) if f.id_log > ultimo_log]
    assert [f.accion for f in nuevas] == [AccionAuditada.ACCESO_DENEGADO_ROL.value] * 2
    assert [
        (f.id_usuario, f.nombre_entidad_afectada, f.id_entidad_afectada) for f in nuevas
    ] == [(id_actor, "usuario", None)] * 2

    campos = " ".join(
        str(valor)
        for fila in nuevas
        for valor in (fila.accion, fila.nombre_entidad_afectada, fila.id_entidad_afectada, fila.ip_origen)
    )
    for prohibido in (
        "@example.com",
        email_actor,
        MARCADOR_PASSWORD_DENEGADA,
        token,
        "eyJ",
        "Bearer",
        PREFIJO_ARGON2ID,
        str(id_existente),
        str(ID_INEXISTENTE),
        *datos_del_objetivo,
    ):
        assert prohibido not in campos


def test_anonimo_y_token_invalido_reciben_401(cliente, base):
    id_paciente = crear_paciente_libre(base)

    anonimo = cliente.post(
        RUTA_PACIENTE.format(id_paciente),
        json={"email": EMAIL_PACIENTE_NUEVA, "password": PASSWORD_NUEVA},
    )
    invalido = provisionar_paciente(cliente, "no.es.un.token", id_paciente)

    assert anonimo.status_code == invalido.status_code == 401
    assert id_de_cuenta(base, EMAIL_PACIENTE_NUEVA) is None


def test_no_existe_get_administrativo(cliente, token_admin):
    assert cliente.get("/api/v1/cuentas/100/estado", headers=bearer(token_admin)).status_code == 405
    assert cliente.get("/api/v1/cuentas", headers=bearer(token_admin)).status_code == 404


# ---------------------------------------------------------------------------
# 6. Ciclo de vida
# ---------------------------------------------------------------------------


def test_desactivar_reactivar_y_el_token_previo(cliente, base, token_admin):
    id_paciente = crear_paciente_libre(base)
    id_usuario = provisionar_paciente(cliente, token_admin, id_paciente).json()["id_usuario"]
    hash_original = base.escalar(f"SELECT password_hash FROM {O}.usuario WHERE id_usuario = :id", id=id_usuario)

    token_previo = iniciar_sesion(cliente, EMAIL_PACIENTE_NUEVA, PASSWORD_NUEVA)
    assert cliente.get(RUTA_YO, headers=bearer(token_previo)).status_code == 200

    # activa -> inactiva
    respuesta = cambiar_estado(cliente, token_admin, id_usuario, False)
    assert respuesta.status_code == 200
    assert respuesta.json() == {"id_usuario": id_usuario, "rol": "PACIENTE", "activo": False}

    nuevo_login = cliente.post(RUTA_TOKEN, json={"email": EMAIL_PACIENTE_NUEVA, "password": PASSWORD_NUEVA})
    assert nuevo_login.status_code == 401
    assert cliente.get(RUTA_YO, headers=bearer(token_previo)).status_code == 401

    # inactiva -> inactiva: no-op, sin segunda auditoria
    assert cambiar_estado(cliente, token_admin, id_usuario, False).json()["activo"] is False

    # inactiva -> activa
    respuesta = cambiar_estado(cliente, token_admin, id_usuario, True)
    assert respuesta.status_code == 200
    assert respuesta.json() == {"id_usuario": id_usuario, "rol": "PACIENTE", "activo": True}

    # activa -> activa: no-op
    assert cambiar_estado(cliente, token_admin, id_usuario, True).status_code == 200

    assert acciones_sobre(base, id_usuario) == [
        AccionAuditada.CUENTA_PACIENTE_PROVISIONADA.value,
        AccionAuditada.CUENTA_DESACTIVADA.value,
        AccionAuditada.CUENTA_REACTIVADA.value,
    ]

    # Misma identidad: id, hash y vinculo.
    assert id_de_cuenta(base, EMAIL_PACIENTE_NUEVA) == id_usuario
    assert base.escalar(f"SELECT password_hash FROM {O}.usuario WHERE id_usuario = :id", id=id_usuario) == hash_original
    assert base.filas(f"SELECT id_usuario, id_paciente FROM {O}.usuario_paciente WHERE id_paciente = :p", p=id_paciente) == [(id_usuario, id_paciente)]
    assert base.escalar(f"SELECT count(*) FROM {O}.usuario WHERE email = :e", e=EMAIL_PACIENTE_NUEVA) == 1

    token_nuevo = iniciar_sesion(cliente, EMAIL_PACIENTE_NUEVA, PASSWORD_NUEVA)
    assert cliente.get(RUTA_YO, headers=bearer(token_nuevo)).json() == {"id_usuario": id_usuario, "rol": "PACIENTE"}


def test_limitacion_aceptada_el_token_previo_vuelve_a_valer_tras_reactivar(cliente, base, token_admin, password_canonica):
    """Documentada, no resuelta: la autoridad es ``Usuario.activo`` y no hay revocacion.

    Mientras la cuenta esta inactiva el token se rechaza; si se reactiva antes de
    que ese token expire, vuelve a autorizar. Se fija aqui para que nadie la lea
    como una garantia que el sistema no da.
    """
    token_previo = iniciar_sesion(cliente, EMAIL_MEDICO_CANONICO, password_canonica)
    id_usuario = id_de_cuenta(base, EMAIL_MEDICO_CANONICO)

    cambiar_estado(cliente, token_admin, id_usuario, False)
    assert cliente.get(RUTA_YO, headers=bearer(token_previo)).status_code == 401

    cambiar_estado(cliente, token_admin, id_usuario, True)
    assert cliente.get(RUTA_YO, headers=bearer(token_previo)).status_code == 200


@pytest.mark.parametrize("email", [EMAIL_ADMIN, EMAIL_ADMIN_2], ids=["propia", "otra"])
@pytest.mark.parametrize("activo", [False, True])
def test_una_cuenta_admin_no_se_administra(cliente, base, token_admin, email, activo):
    id_usuario = id_de_cuenta(base, email)

    respuesta = cambiar_estado(cliente, token_admin, id_usuario, activo)

    assert respuesta.status_code == 409
    assert base.escalar(f"SELECT activo FROM {O}.usuario WHERE id_usuario = :id", id=id_usuario) is True
    assert acciones_sobre(base, id_usuario) == []


def test_estado_de_cuenta_inexistente_es_404(cliente, token_admin):
    assert cambiar_estado(cliente, token_admin, 2_000_000_000, False).status_code == 404


def test_un_admin_desactivado_ya_no_administra(cliente, base, token_admin, password_canonica):
    """El actor tambien se revalida en PostgreSQL en cada peticion."""
    base.escribir(f"UPDATE {O}.usuario SET activo = false WHERE email = :e", e=EMAIL_ADMIN)

    respuesta = cambiar_estado(cliente, token_admin, id_de_cuenta(base, EMAIL_PACIENTE_CANONICA), False)

    assert respuesta.status_code == 401


# ---------------------------------------------------------------------------
# 7. Preservacion de la historia
# ---------------------------------------------------------------------------

TABLAS_PRESERVADAS = (
    "paciente",
    "medico",
    "embarazo",
    "sesion_monitoreo",
    "lectura_biometrica",
    "usuario_paciente",
    "usuario_medico",
    "seguimiento_clinico",
    "asignacion_dispositivo",
    "idempotencia_solicitud",
)


def test_desactivar_y_reactivar_no_borra_ni_altera_nada(cliente, base, token_admin):
    ejecutar_etl(base.engine)
    hechos = base.escalar("SELECT count(*) FROM analitico.fact_lectura_biometrica")
    assert hechos > 0
    id_paciente_canonica = id_de_cuenta(base, EMAIL_PACIENTE_CANONICA)
    id_medico_canonico = id_de_cuenta(base, EMAIL_MEDICO_CANONICO)
    ultimo_log = base.escalar(f"SELECT max(id_log) FROM {O}.auditoria_log")

    huellas = {t: huella(base, f"{O}.{t}") for t in TABLAS_PRESERVADAS}
    huella_analitica = huella(base, "analitico.fact_lectura_biometrica")
    auditoria_previa = huella(base, f"{O}.auditoria_log", f"WHERE id_log <= {ultimo_log}")

    for id_usuario in (id_paciente_canonica, id_medico_canonico):
        assert cambiar_estado(cliente, token_admin, id_usuario, False).status_code == 200
    assert {t: huella(base, f"{O}.{t}") for t in TABLAS_PRESERVADAS} == huellas

    for id_usuario in (id_paciente_canonica, id_medico_canonico):
        assert cambiar_estado(cliente, token_admin, id_usuario, True).status_code == 200

    assert {t: huella(base, f"{O}.{t}") for t in TABLAS_PRESERVADAS} == huellas
    assert huella(base, "analitico.fact_lectura_biometrica") == huella_analitica
    assert huella(base, f"{O}.auditoria_log", f"WHERE id_log <= {ultimo_log}") == auditoria_previa
    assert conteos(base) == CONTEOS_CANONICOS


# ---------------------------------------------------------------------------
# 8. Continuidad longitudinal
# ---------------------------------------------------------------------------


def test_la_misma_paciente_y_la_misma_cuenta_a_traves_de_dos_embarazos(cliente, base, token_admin):
    id_paciente = crear_paciente_libre(base)
    id_clinica = base.escalar(f"SELECT min(id_clinica) FROM {O}.clinica")
    id_anterior = base.escribir(
        f"INSERT INTO {O}.embarazo (id_paciente, id_clinica, numero_gestas, numero_partos,"
        " fecha_inicio, fecha_probable_parto, estado_embarazo, fecha_cierre)"
        " VALUES (:p, :c, 1, 0, :inicio, :fpp, 'FINALIZADO', :cierre) RETURNING id_embarazo",
        p=id_paciente, c=id_clinica,
        inicio=date(2024, 1, 10), fpp=date(2024, 10, 16), cierre=date(2024, 10, 12),
    )
    huella_anterior = huella(base, f"{O}.embarazo", f"WHERE id_embarazo = {id_anterior}")

    id_usuario = provisionar_paciente(cliente, token_admin, id_paciente).json()["id_usuario"]
    pacientes_antes = base.escalar(f"SELECT count(*) FROM {O}.paciente")
    usuarios_antes = base.escalar(f"SELECT count(*) FROM {O}.usuario")

    id_nuevo = base.escribir(
        f"INSERT INTO {O}.embarazo (id_paciente, id_clinica, numero_gestas, numero_partos,"
        " fecha_inicio, fecha_probable_parto) VALUES (:p, :c, 2, 1, :inicio, :fpp)"
        " RETURNING id_embarazo",
        p=id_paciente, c=id_clinica, inicio=date(2026, 3, 2), fpp=date(2026, 12, 7),
    )

    embarazos = base.filas(
        f"SELECT id_embarazo, id_paciente, estado_embarazo, fecha_cierre FROM {O}.embarazo"
        " WHERE id_paciente = :p ORDER BY fecha_inicio",
        p=id_paciente,
    )
    assert [e.id_embarazo for e in embarazos] == [id_anterior, id_nuevo]
    assert id_anterior != id_nuevo
    assert {e.id_paciente for e in embarazos} == {id_paciente}
    assert (embarazos[0].estado_embarazo, embarazos[0].fecha_cierre) == ("FINALIZADO", date(2024, 10, 12))
    assert (embarazos[1].estado_embarazo, embarazos[1].fecha_cierre) == ("ACTIVO", None)

    assert base.escalar(f"SELECT count(*) FROM {O}.paciente") == pacientes_antes
    assert base.escalar(f"SELECT count(*) FROM {O}.usuario") == usuarios_antes
    assert base.filas(
        f"SELECT id_usuario FROM {O}.usuario_paciente WHERE id_paciente = :p", p=id_paciente
    ) == [(id_usuario,)]
    assert base.escalar(
        f"SELECT count(*) FROM {O}.paciente WHERE cedula = 'SIM-PAC-S97-031'"
    ) == 1
    assert huella(base, f"{O}.embarazo", f"WHERE id_embarazo = {id_anterior}") == huella_anterior

    token = iniciar_sesion(cliente, EMAIL_PACIENTE_NUEVA, PASSWORD_NUEVA)
    assert cliente.get(RUTA_YO, headers=bearer(token)).json() == {"id_usuario": id_usuario, "rol": "PACIENTE"}


# ---------------------------------------------------------------------------
# 9. Concurrencia con conexiones independientes
# ---------------------------------------------------------------------------


@dataclass
class Carrera:
    a: Any
    b: Any


@contextmanager
def participantes(base: BaseTemporal):
    """Dos clientes, cada uno con su engine y su application_name."""
    engines = {
        letra: create_engine(
            base.url,
            poolclass=NullPool,
            connect_args={"application_name": f"scrum97-{letra}", "options": OPCIONES_DE_LIMITE},
        )
        for letra in "AB"
    }

    def _engine(peticion: Request):
        return engines[peticion.headers[CABECERA_PARTICIPANTE]]

    def sesion_negocio(peticion: Request):
        with Session(bind=_engine(peticion), autoflush=False) as sesion_bd:
            yield sesion_bd

    def sesion_auditoria(peticion: Request):
        with Session(bind=_engine(peticion), autoflush=False) as sesion_bd:
            yield sesion_bd

    app.dependency_overrides[get_db] = sesion_negocio
    app.dependency_overrides[get_db_auditoria] = sesion_auditoria
    app.dependency_overrides[obtener_configuracion_jwt] = lambda: CONFIGURACION
    clientes = {
        letra: TestClient(app, raise_server_exceptions=False, headers={CABECERA_PARTICIPANTE: letra})
        for letra in "AB"
    }
    try:
        yield clientes
    finally:
        app.dependency_overrides.clear()
        for letra in "AB":
            clientes[letra].close()
            engines[letra].dispose()


def correr(base: BaseTemporal, bloqueo: list[str], a: Callable, b: Callable) -> Carrera:
    """Un control toma el candado, A y B esperan ambos, el control suelta.

    Lo que sincroniza es PostgreSQL: se sondea ``pg_stat_activity`` hasta que las
    dos conexiones esperan un candado, y solo entonces se libera. El sondeo va por
    un observador en autocommit: dentro de una transaccion PostgreSQL devuelve la
    misma foto de esa vista en cada lectura, y el control nunca veria la espera.
    """
    control = base.engine.connect()
    observador = base.engine.connect().execution_options(isolation_level="AUTOCOMMIT")
    transaccion = control.begin()
    try:
        for sentencia in bloqueo:
            control.execute(text(sentencia))
        with participantes(base) as clientes, ThreadPoolExecutor(max_workers=2) as pool:
            futuro_a = pool.submit(a, clientes["A"])
            futuro_b = pool.submit(b, clientes["B"])
            limite = time.monotonic() + TIEMPO_MAXIMO_DE_ESPERA
            while True:
                esperando = observador.execute(
                    text(
                        "SELECT count(*) FROM pg_stat_activity WHERE application_name"
                        " IN ('scrum97-A', 'scrum97-B') AND wait_event_type = 'Lock'"
                    )
                ).scalar()
                if esperando == 2:
                    break
                for futuro in (futuro_a, futuro_b):
                    if futuro.done():
                        pytest.fail(f"Un participante termino antes de la carrera: {futuro.result()}")
                if time.monotonic() > limite:
                    pytest.fail("Los dos participantes no llegaron a esperar el candado.")
                time.sleep(0.05)
            transaccion.rollback()
            return Carrera(a=futuro_a.result(timeout=90), b=futuro_b.result(timeout=90))
    finally:
        if transaccion.is_active:
            transaccion.rollback()
        control.close()
        observador.close()


def estados(carrera: Carrera) -> list[int]:
    return sorted([carrera.a.status_code, carrera.b.status_code])


def test_carrera_mismo_correo(base, cliente, token_admin, caplog):
    paciente_a = crear_paciente_libre(base, 31)
    paciente_b = crear_paciente_libre(base, 32)
    antes = conteos(base)

    with caplog.at_level(logging.DEBUG):
        carrera = correr(
            base,
            [f"LOCK TABLE {O}.usuario IN EXCLUSIVE MODE"],
            lambda c: provisionar_paciente(c, token_admin, paciente_a),
            lambda c: provisionar_paciente(c, token_admin, paciente_b),
        )

    assert estados(carrera) == [201, 409]
    perdedora = carrera.a if carrera.a.status_code == 409 else carrera.b
    assert perdedora.json()["detail"] == servicio_cuentas.MENSAJE_EMAIL_EN_USO
    assert conteos(base)["usuario"] == antes["usuario"] + 1
    assert conteos(base)["usuario_paciente"] == antes["usuario_paciente"] + 1
    assert base.escalar(f"SELECT count(*) FROM {O}.usuario WHERE email = :e", e=EMAIL_PACIENTE_NUEVA) == 1
    assert cuentas_incoherentes(base) == 0
    assert len([f for f in auditoria_de(base) if f.accion == "CUENTA_PACIENTE_PROVISIONADA"]) == 1
    assert "uq_usuario_email" in caplog.text
    for prohibido in (EMAIL_PACIENTE_NUEVA, PASSWORD_NUEVA, "INSERT INTO", PREFIJO_ARGON2ID):
        assert prohibido not in caplog.text


@pytest.mark.parametrize("tipo", ["paciente", "medico"])
def test_carrera_mismo_perfil(base, cliente, token_admin, tipo):
    if tipo == "paciente":
        id_perfil = crear_paciente_libre(base)
        tabla, columna, provisionar = "paciente", "id_paciente", provisionar_paciente
    else:
        id_perfil = crear_medico_libre(base)
        tabla, columna, provisionar = "medico", "id_medico", provisionar_medico
    antes = conteos(base)

    carrera = correr(
        base,
        [f"SELECT {columna} FROM {O}.{tabla} WHERE {columna} = {id_perfil} FOR UPDATE"],
        lambda c: provisionar(c, token_admin, id_perfil, "carrera.a@example.com"),
        lambda c: provisionar(c, token_admin, id_perfil, "carrera.b@example.com"),
    )

    assert estados(carrera) == [201, 409]
    assert conteos(base)["usuario"] == antes["usuario"] + 1
    assert base.escalar(
        f"SELECT count(*) FROM {O}.usuario_{tabla} WHERE {columna} = :p", p=id_perfil
    ) == 1
    assert cuentas_incoherentes(base) == 0
    assert len([f for f in auditoria_de(base) if f.accion.startswith("CUENTA_")]) == 1


@pytest.mark.parametrize(
    ("inicial", "pedido_a", "pedido_b"),
    [(True, False, False), (False, True, True), (True, False, True)],
    ids=["dos-desactivaciones", "dos-reactivaciones", "desactivar-y-activar"],
)
def test_carrera_de_estado(base, cliente, token_admin, inicial, pedido_a, pedido_b):
    id_usuario = id_de_cuenta(base, "paciente02@example.com")
    base.escribir(f"UPDATE {O}.usuario SET activo = :a WHERE id_usuario = :id", a=inicial, id=id_usuario)

    carrera = correr(
        base,
        [f"SELECT id_usuario FROM {O}.usuario WHERE id_usuario = {id_usuario} FOR UPDATE"],
        lambda c: cambiar_estado(c, token_admin, id_usuario, pedido_a),
        lambda c: cambiar_estado(c, token_admin, id_usuario, pedido_b),
    )

    assert estados(carrera) == [200, 200]
    final = base.escalar(f"SELECT activo FROM {O}.usuario WHERE id_usuario = :id", id=id_usuario)
    acciones = acciones_sobre(base, id_usuario)

    if pedido_a == pedido_b:
        # Un ganador, un no-op: una sola transicion auditada.
        esperado = "CUENTA_DESACTIVADA" if pedido_a is False else "CUENTA_REACTIVADA"
        assert acciones == [esperado]
        assert final is pedido_a
    else:
        # Dos ordenes posibles, ambos coherentes con la auditoria.
        assert acciones in (["CUENTA_DESACTIVADA"], ["CUENTA_DESACTIVADA", "CUENTA_REACTIVADA"])
        assert final is (acciones[-1] == "CUENTA_REACTIVADA")
    assert cuentas_incoherentes(base) == 0


# ---------------------------------------------------------------------------
# 10. Saneamiento de lo realmente escrito
# ---------------------------------------------------------------------------

PROHIBIDOS = ("$argon2id$", "Bearer", "eyJ", SECRETO, "@example.com", "postgresql", "SELECT", PASSWORD_NUEVA)


def test_ninguna_fila_de_auditoria_ni_respuesta_lleva_datos_prohibidos(
    cliente, base, token_admin, password_canonica
):
    id_paciente = crear_paciente_libre(base)
    respuestas = [provisionar_paciente(cliente, token_admin, id_paciente)]
    id_usuario = respuestas[0].json()["id_usuario"]
    respuestas.append(provisionar_paciente(cliente, token_admin, id_paciente))
    respuestas.append(cambiar_estado(cliente, token_admin, id_usuario, False))
    respuestas.append(cambiar_estado(cliente, token_admin, id_usuario, True))
    token_paciente = iniciar_sesion(cliente, EMAIL_PACIENTE_CANONICA, password_canonica)
    respuestas.append(provisionar_paciente(cliente, token_paciente, id_paciente))
    respuestas.append(cliente.post(RUTA_PACIENTE.format(id_paciente), json={"password": PASSWORD_NUEVA}, headers=bearer(token_admin)))

    texto_auditoria = " ".join(" ".join(str(v) for v in fila) for fila in auditoria_de(base))
    for prohibido in PROHIBIDOS:
        assert prohibido not in texto_auditoria
    for respuesta in respuestas:
        for prohibido in (PASSWORD_NUEVA, "$argon2id$", EMAIL_PACIENTE_NUEVA, "password_hash"):
            assert prohibido not in respuesta.text


def test_la_suite_no_deja_bases_residuales(servidor):
    with servidor.engine.connect() as conexion:
        residuales = [
            fila[0]
            for fila in conexion.execute(
                text("SELECT datname FROM pg_database WHERE datname LIKE :patron"),
                {"patron": f"{PREFIJO_DE_BASE}%"},
            )
        ]

    ajenas = [n for n in residuales if not n.startswith(f"{PREFIJO_DE_BASE}{servidor.ejecucion}_")]
    assert ajenas == [], f"Bases de ejecuciones anteriores sin limpiar: {ajenas}"
