"""Idempotencia del endpoint contra un servidor PostgreSQL 16 real (SCRUM-63).

Se omite salvo que esté definida ``SCRUM63_TEST_DATABASE_URL``. Nunca cae por
omisión sobre ``DATABASE_URL`` ni sobre la variable de otra suite: una prueba que
escribe no puede terminar sobre la base de desarrollo de alguien por haberse
olvidado de exportar una variable.

**Qué prueba esto que no probaban las suites offline.** Allí la ``Session`` es un
doble y las tres sentencias de idempotencia se guionan. Aquí las ejecuta
PostgreSQL: el ``INSERT ... ON CONFLICT (recurso, clave) DO NOTHING RETURNING``,
el ``UPDATE`` que enlaza el resultado y su ``rowcount``, la UNIQUE que hace de
garantía, el CHECK que impide un resultado a medias y la FK ``RESTRICT`` que
impide que una reclamación desaparezca con su sesión.

**Aislamiento.** Se reutilizan las fixtures de SCRUM-62 sin cambiarlas: cada
prueba abre una transacción exterior que revierte pase lo que pase, y la
``Session`` que atiende la petición se une a ella con
``join_transaction_mode="create_savepoint"``, de modo que el ``commit`` del
endpoint es real y observable pero no sobrevive. No se ejecuta ``TRUNCATE``, ni
``DROP`` general, ni ``create_all``, y las pruebas de endpoint no migran nada.

**La excepción son las pruebas de migración**, que sí ejecutan un
``downgrade``/``upgrade`` real. Por eso comprueban antes que la base conectada es
la dedicada, por nombre, y abortan contra cualquier otra.

La concurrencia no se prueba aquí. Corresponde a la fase siguiente.

Ejecución desde ``backend/``::

    $env:SCRUM63_TEST_DATABASE_URL = "postgresql+psycopg://<usuario>:<clave>@127.0.0.1:<puerto>/<base>"
    .\\.venv\\Scripts\\python.exe -m pytest tests/test_ingestion_idempotency_postgresql.py -v

Todos los datos son simulados y completamente ficticios.
"""

from __future__ import annotations

import hashlib
import os
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import date
from typing import Any

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi import Request
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, delete, func, inspect, insert, select, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import make_url
from sqlalchemy.exc import ArgumentError, IntegrityError, SQLAlchemyError
from sqlalchemy.orm import Session

from app.api.v1.sesiones import CABECERA_IDEMPOTENCIA, CABECERA_REPLAY
from app.config import settings
from app.db.base import SCHEMA_OPERACIONAL
from app.db.session import get_db
from app.main import app
from app.models.catalogos import Semaforo, TiempoGestacional
from app.models.clinico import Clinica, Embarazo, Paciente
from app.models.idempotencia import IdempotenciaSolicitud
from app.models.monitoreo import (
    AsignacionDispositivo,
    Dispositivo,
    LecturaBiometrica,
    SesionMonitoreo,
)
from app.services.errores import MENSAJE_INESPERADO
from app.services.idempotencia import (
    MENSAJE_COLISION,
    RECURSO_SESIONES_MONITOREO,
    huella_del_paquete,
)
from app.schemas.monitoreo import SesionMonitoreoEntrada
from tests.conftest import construir_config_alembic
from tests.test_migration_postgresql import NOMBRE_DE_BASE_REQUERIDO

# Fixtures y ayudantes de SCRUM-62, reutilizados tal cual. ``engine_de_pruebas``
# se redefine más abajo sobre la variable de esta suite, y por eso
# ``conexion_revertida`` -- que lo pide por nombre -- acaba usando el de aquí.
from tests.test_ingestion_api_postgresql import (  # noqa: F401
    FECHA_INICIO_EMBARAZO,
    FECHA_PROBABLE_PARTO,
    ID_INEXISTENTE,
    RUTA,
    SPO2_FUERA_DE_RANGO,
    VENTANA,
    VENTANA_TEMPRANA,
    Referencias,
    _asegurar_semaforo,
    _asegurar_semanas,
    _crear_asignacion,
    _crear_dispositivo,
    conexion_revertida,
    contar_lecturas,
    contar_sesiones,
    lectura_de_signos,
    lecturas_del_embarazo,
    localizar_secuencia,
    paquete_de_movimiento,
    paquete_de_signos,
    referencias,
    sesion_de_pruebas,
    sesiones_del_embarazo,
)

VARIABLE_DE_ENTORNO = "SCRUM63_TEST_DATABASE_URL"
MOTOR_REQUERIDO = "postgresql"

REVISION_INICIAL = "150788f88be7"
# The revision this suite validates. Since SCRUM-69 it is no longer the head of
# the chain -- the analytic schema sits on top of it -- so the cycle below names
# it explicitly instead of assuming the head is SCRUM-63's.
REVISION_SCRUM_63 = "87d8ed46686b"
TABLA_IDEMPOTENCIA = "idempotencia_solicitud"

pytestmark = pytest.mark.skipif(
    not os.environ.get(VARIABLE_DE_ENTORNO),
    reason=(
        f"Define {VARIABLE_DE_ENTORNO} apuntando a una base PostgreSQL dedicada "
        "para ejecutar la validación de idempotencia."
    ),
)

FRAGMENTOS_PROHIBIDOS = (
    "postgresql+psycopg://",
    "psycopg",
    "INSERT INTO",
    "SELECT",
    "Traceback",
    "sqlalchemy",
    "uq_idempotencia_solicitud",
    "ON CONFLICT",
)


# ---------------------------------------------------------------------------
# Conexión: exclusiva de esta suite, sin recurso alternativo
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def url_de_pruebas() -> str:
    """URL de la base de pruebas, comprobada sin abrir ninguna conexión.

    ``os.environ[...]`` y no ``.get(...)``: sin la variable esta suite no se
    ejecuta, y no existe ningún camino que la sustituya por otra.
    """
    url = os.environ[VARIABLE_DE_ENTORNO]
    try:
        motor = make_url(url).get_backend_name()
    except ArgumentError:
        pytest.fail(f"{VARIABLE_DE_ENTORNO} no es una URL de conexión válida.")
    if motor != MOTOR_REQUERIDO:
        pytest.fail(
            f"{VARIABLE_DE_ENTORNO} apunta a un motor '{motor}'. Estas pruebas "
            "solo se ejecutan contra PostgreSQL."
        )
    return url


@pytest.fixture(scope="session")
def engine_de_pruebas(url_de_pruebas):
    """Engine sobre una base que ya debe estar migrada al head de la cadena."""
    engine = create_engine(url_de_pruebas)
    if not inspect(engine).has_table(TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL):
        engine.dispose()
        # Sin URL en el mensaje: lleva credenciales.
        pytest.fail(
            f"La base indicada por {VARIABLE_DE_ENTORNO} no tiene la tabla "
            f"'{TABLA_IDEMPOTENCIA}'. Ejecuta 'alembic upgrade head' desde "
            "backend/ antes de correr estas pruebas."
        )
    yield engine
    engine.dispose()


def _variables_de_entorno_leidas() -> set[str]:
    """Literales que este módulo usa para leer ``os.environ``, según su AST.

    Se mira el árbol sintáctico y no el texto del archivo: buscar cadenas
    prohibidas en la propia fuente es una comprobación que se derrota a sí misma,
    porque el nombre aparecería justamente en la línea que lo prohíbe.
    """
    import ast
    from pathlib import Path

    arbol = ast.parse(Path(__file__).read_text(encoding="utf-8"))
    nombres: set[str] = set()

    def _es_environ(nodo) -> bool:
        return isinstance(nodo, ast.Attribute) and nodo.attr == "environ"

    for nodo in ast.walk(arbol):
        # os.environ["X"]
        if isinstance(nodo, ast.Subscript) and _es_environ(nodo.value):
            if isinstance(nodo.slice, ast.Constant):
                nombres.add(nodo.slice.value)
            elif isinstance(nodo.slice, ast.Name):
                nombres.add(f"<variable {nodo.slice.id}>")
        # os.environ.get("X")
        if (
            isinstance(nodo, ast.Call)
            and isinstance(nodo.func, ast.Attribute)
            and nodo.func.attr == "get"
            and _es_environ(nodo.func.value)
            and nodo.args
        ):
            primero = nodo.args[0]
            if isinstance(primero, ast.Constant):
                nombres.add(primero.value)
            elif isinstance(primero, ast.Name):
                nombres.add(f"<variable {primero.id}>")
    return nombres


def test_esta_suite_solo_lee_su_propia_variable():
    """Ni recurso alternativo ni herencia de otra suite, comprobado sobre el AST."""
    leidas = _variables_de_entorno_leidas()

    assert VARIABLE_DE_ENTORNO == "SCRUM63_TEST_DATABASE_URL"
    # Toda lectura pasa por la constante del módulo, y la constante es esa.
    assert leidas == {"<variable VARIABLE_DE_ENTORNO>"}


def test_las_fixtures_heredadas_cuelgan_del_engine_de_esta_suite(
    conexion_revertida, engine_de_pruebas, sesion_de_pruebas
):
    """La atadura que hace que reutilizar fixtures de SCRUM-62 sea seguro.

    ``conexion_revertida``, ``sesion_de_pruebas`` y ``referencias`` se definen en
    el módulo de SCRUM-62, pero piden ``engine_de_pruebas`` **por nombre**, y
    pytest lo resuelve desde el módulo que solicita la fixture -- este. Por eso
    la suite depende solo de ``SCRUM63_TEST_DATABASE_URL``.

    Es una atadura implícita, y esta prueba es lo que la vuelve explícita: si
    alguien retirara ``engine_de_pruebas`` de este módulo, las fixtures heredadas
    caerían en silencio sobre el engine de SCRUM-62 y la suite seguiría en verde
    mientras ambas variables estuvieran definidas. Aquí no.
    """
    assert conexion_revertida.engine is engine_de_pruebas
    assert sesion_de_pruebas.get_bind() is conexion_revertida


# ---------------------------------------------------------------------------
# 1. Migración real: la revisión nueva se aplica, se revierte y se reaplica
# ---------------------------------------------------------------------------


def _revision_estampada(engine) -> str | None:
    with engine.connect() as conexion:
        existe = conexion.execute(
            text("select to_regclass('public.alembic_version')")
        ).scalar()
        if existe is None:
            return None
        return conexion.execute(text("select version_num from alembic_version")).scalar()


def _tiene_la_tabla(engine) -> bool:
    return inspect(engine).has_table(TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL)


@pytest.fixture(scope="module")
def ciclo_de_la_revision(engine_de_pruebas, url_de_pruebas):
    """``head -> 150788f88be7 -> head``, ejecutado una sola vez y fotografiado.

    Es el único punto de esta suite que ejecuta DDL, y por eso comprueba antes
    que la base conectada es la dedicada, **por nombre**. Contra cualquier otra
    aborta sin tocar nada: un downgrade borra la tabla de idempotencia.
    """
    with engine_de_pruebas.connect() as conexion:
        nombre = conexion.execute(text("select current_database()")).scalar()
    if nombre != NOMBRE_DE_BASE_REQUERIDO:
        pytest.fail(
            f"{VARIABLE_DE_ENTORNO} apunta a la base '{nombre}'. Este ciclo "
            f"revierte y reaplica una revisión, así que solo se ejecuta contra "
            f"la base dedicada '{NOMBRE_DE_BASE_REQUERIDO}'."
        )

    config = construir_config_alembic()
    fotografia: dict[str, Any] = {"partida": _revision_estampada(engine_de_pruebas)}

    with pytest.MonkeyPatch.context() as parche:
        # alembic/env.py resuelve la URL desde settings, no desde el Config: esto
        # es lo que de verdad mantiene el ciclo lejos de la base de desarrollo.
        parche.setattr(settings, "database_url", url_de_pruebas)

        # The target is named, not relative: «-1» would now revert the analytic
        # revision that sits on top, and this cycle is about SCRUM-63's. Going
        # down to the initial revision takes every later revision with it.
        command.downgrade(config, REVISION_INICIAL)
        fotografia["tras_downgrade"] = _revision_estampada(engine_de_pruebas)
        fotografia["tabla_tras_downgrade"] = _tiene_la_tabla(engine_de_pruebas)

        command.upgrade(config, "head")
        fotografia["tras_upgrade"] = _revision_estampada(engine_de_pruebas)
        fotografia["tabla_tras_upgrade"] = _tiene_la_tabla(engine_de_pruebas)

        try:
            command.check(config)
            fotografia["diferencias"] = None
        except AutogenerateDiffsDetected as error:
            fotografia["diferencias"] = str(error)

    return fotografia


def _head_de_la_cadena() -> str:
    return ScriptDirectory.from_config(construir_config_alembic()).get_current_head()


def test_la_revision_de_scrum_63_sigue_en_la_cadena_y_el_head_desciende_de_ella():
    script = ScriptDirectory.from_config(construir_config_alembic())
    [head] = script.get_heads()

    assert script.get_bases() == [REVISION_INICIAL]
    assert script.get_revision(REVISION_SCRUM_63).down_revision == REVISION_INICIAL
    assert REVISION_SCRUM_63 in {
        revision.revision for revision in script.iterate_revisions(head, "base")
    }


def test_la_base_parte_del_head(ciclo_de_la_revision):
    assert ciclo_de_la_revision["partida"] == _head_de_la_cadena()


def test_el_downgrade_retrocede_hasta_la_revision_inicial(ciclo_de_la_revision):
    """Y se lleva la tabla con él: la revisión es reversible de verdad."""
    assert ciclo_de_la_revision["tras_downgrade"] == REVISION_INICIAL
    assert ciclo_de_la_revision["tabla_tras_downgrade"] is False


def test_el_upgrade_vuelve_a_dejar_la_base_en_el_head(ciclo_de_la_revision):
    assert ciclo_de_la_revision["tras_upgrade"] == _head_de_la_cadena()
    assert ciclo_de_la_revision["tabla_tras_upgrade"] is True


def test_alembic_check_no_reporta_divergencia_tras_el_ciclo(ciclo_de_la_revision):
    assert ciclo_de_la_revision["diferencias"] is None, (
        "alembic check encontró operaciones pendientes: "
        f"{ciclo_de_la_revision['diferencias']}"
    )


# ---------------------------------------------------------------------------
# 1b. La tabla desplegada, tal como PostgreSQL la reporta
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def tabla_desplegada(engine_de_pruebas, ciclo_de_la_revision):
    """Estructura real de la tabla, leída del catálogo tras el ciclo completo."""
    inspector = inspect(engine_de_pruebas)
    return {
        "columnas": {
            c["name"]: c for c in inspector.get_columns(
                TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL
            )
        },
        "pk": inspector.get_pk_constraint(
            TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL
        ),
        "unicas": inspector.get_unique_constraints(
            TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL
        ),
        "checks": inspector.get_check_constraints(
            TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL
        ),
        "foraneas": inspector.get_foreign_keys(
            TABLA_IDEMPOTENCIA, schema=SCHEMA_OPERACIONAL
        ),
    }


def test_las_columnas_desplegadas_son_las_del_modelo(tabla_desplegada):
    assert set(tabla_desplegada["columnas"]) == {
        "id_idempotencia",
        "recurso",
        "clave",
        "huella",
        "id_sesion",
        "ids_lectura",
        "fecha_hora",
    }


@pytest.mark.parametrize(
    ("columna", "tipo_compilado", "nullable"),
    [
        ("id_idempotencia", "INTEGER", False),
        ("recurso", "VARCHAR(80)", False),
        ("clave", "VARCHAR(128)", False),
        ("huella", "VARCHAR(64)", False),
        ("id_sesion", "INTEGER", True),
        ("ids_lectura", "INTEGER[]", True),
        ("fecha_hora", "TIMESTAMP WITH TIME ZONE", False),
    ],
)
def test_los_tipos_desplegados_son_los_esperados(
    columna, tipo_compilado, nullable, tabla_desplegada
):
    """El tipo se compila con el dialecto, no se convierte a texto.

    ``str(ARRAY(Integer()))`` devuelve solo ``ARRAY``; lo que interesa es lo que
    PostgreSQL tiene desplegado, y eso es ``INTEGER[]``.
    """
    definicion = tabla_desplegada["columnas"][columna]

    assert definicion["type"].compile(dialect=postgresql.dialect()) == tipo_compilado
    assert definicion["nullable"] is nullable


def test_la_llave_primaria_desplegada(tabla_desplegada):
    assert tabla_desplegada["pk"]["constrained_columns"] == ["id_idempotencia"]
    assert tabla_desplegada["pk"]["name"] == "pk_idempotencia_solicitud"


def test_la_unique_desplegada_es_la_garantia(tabla_desplegada):
    unicas = {
        (u["name"], tuple(u["column_names"])) for u in tabla_desplegada["unicas"]
    }

    assert (
        "uq_idempotencia_solicitud_recurso_clave",
        ("recurso", "clave"),
    ) in unicas


def test_el_check_de_resultado_completo_esta_desplegado(tabla_desplegada):
    checks = {c["name"]: c["sqltext"] for c in tabla_desplegada["checks"]}
    texto = checks["ck_idempotencia_solicitud_resultado_completo"]

    assert "id_sesion IS NULL" in texto
    assert "ids_lectura IS NULL" in texto
    assert "cardinality(ids_lectura) > 0" in texto


def test_la_foranea_desplegada_es_restrict(tabla_desplegada):
    foranea = tabla_desplegada["foraneas"][0]

    assert foranea["constrained_columns"] == ["id_sesion"]
    assert foranea["referred_table"] == "sesion_monitoreo"
    assert foranea["referred_columns"] == ["id_sesion"]
    assert foranea["options"]["ondelete"] == "RESTRICT"


# ---------------------------------------------------------------------------
# Fixtures del endpoint
# ---------------------------------------------------------------------------


@pytest.fixture
def clave_de_idempotencia(request) -> str:
    """Clave válida, única por prueba y determinística entre ejecuciones."""
    digest = hashlib.sha256(request.node.nodeid.encode("utf-8")).hexdigest()
    return f"scrum63-{digest[:32]}"


def clave_derivada(clave: str, sufijo: str) -> str:
    return f"{clave}-{sufijo}"


@pytest.fixture
def cliente(sesion_de_pruebas, clave_de_idempotencia) -> TestClient:
    app.dependency_overrides[get_db] = lambda: sesion_de_pruebas
    try:
        yield TestClient(app, headers={CABECERA_IDEMPOTENCIA: clave_de_idempotencia})
    finally:
        app.dependency_overrides.clear()


def huella_de(cuerpo: dict[str, Any]) -> str:
    return huella_del_paquete(SesionMonitoreoEntrada.model_validate(cuerpo))


def reclamaciones(conexion, clave: str) -> list[Any]:
    """Filas de idempotencia de una clave, leídas por la conexión exterior."""
    return (
        conexion.execute(
            select(IdempotenciaSolicitud).where(IdempotenciaSolicitud.clave == clave)
        )
        .mappings()
        .all()
    )


def contar_reclamaciones(conexion, clave: str) -> int:
    return conexion.execute(
        select(func.count())
        .select_from(IdempotenciaSolicitud)
        .where(IdempotenciaSolicitud.clave == clave)
    ).scalar_one()


# ---------------------------------------------------------------------------
# 2. Primera solicitud
# ---------------------------------------------------------------------------


def test_la_primera_solicitud_crea_sesion_lecturas_y_reclamacion(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    cuerpo = paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=95 + indice) for indice in range(3)
        ],
    )

    antes_sesiones = contar_sesiones(conexion_revertida, referencias.id_embarazo)
    antes_lecturas = contar_lecturas(conexion_revertida, referencias.id_embarazo)
    antes_reclamaciones = contar_reclamaciones(conexion_revertida, clave_de_idempotencia)

    respuesta = cliente.post(RUTA, json=cuerpo)

    assert respuesta.status_code == 201
    assert respuesta.headers[CABECERA_REPLAY] == "false"
    assert antes_sesiones == 0 and antes_lecturas == 0 and antes_reclamaciones == 0
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_lecturas(conexion_revertida, referencias.id_embarazo) == 3
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1


def test_la_reclamacion_queda_completa_y_apunta_a_la_sesion(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    cuerpo = paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=95 + indice) for indice in range(3)
        ],
    )

    respuesta = cliente.post(RUTA, json=cuerpo)
    fila = reclamaciones(conexion_revertida, clave_de_idempotencia)[0]

    assert fila["recurso"] == RECURSO_SESIONES_MONITOREO
    assert fila["huella"] == huella_de(cuerpo)
    assert fila["id_sesion"] == respuesta.json()["id_sesion"]
    assert fila["ids_lectura"] == respuesta.json()["ids_lectura"]
    assert fila["fecha_hora"] is not None


def test_el_orden_de_ids_lectura_se_conserva_en_la_reclamacion(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """El array guardado es el orden del paquete, no un orden recalculado."""
    cuerpo = paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=90 + indice) for indice in range(5)
        ],
    )

    respuesta = cliente.post(RUTA, json=cuerpo)
    fila = reclamaciones(conexion_revertida, clave_de_idempotencia)[0]
    persistidas = [
        lectura["id_lectura"]
        for lectura in lecturas_del_embarazo(conexion_revertida, referencias.id_embarazo)
    ]

    assert respuesta.json()["ids_lectura"] == persistidas
    assert list(fila["ids_lectura"]) == persistidas
    assert respuesta.json()["lecturas_creadas"] == 5


# ---------------------------------------------------------------------------
# 3. Replay secuencial
# ---------------------------------------------------------------------------


@pytest.fixture
def primera_y_replay(cliente, referencias):
    """Un paquete enviado dos veces con la misma clave y el mismo cuerpo."""
    cuerpo = paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=95 + indice) for indice in range(2)
        ],
    )
    primera = cliente.post(RUTA, json=cuerpo)
    segunda = cliente.post(RUTA, json=cuerpo)
    return cuerpo, primera, segunda


def test_el_reenvio_identico_devuelve_201_marcado_como_reenvio(primera_y_replay):
    _, primera, segunda = primera_y_replay

    assert primera.status_code == 201
    assert segunda.status_code == 201
    assert primera.headers[CABECERA_REPLAY] == "false"
    assert segunda.headers[CABECERA_REPLAY] == "true"


def test_el_reenvio_devuelve_exactamente_el_mismo_cuerpo(primera_y_replay):
    _, primera, segunda = primera_y_replay

    assert segunda.json() == primera.json()
    assert segunda.json()["id_sesion"] == primera.json()["id_sesion"]
    assert segunda.json()["ids_lectura"] == primera.json()["ids_lectura"]


def test_el_reenvio_no_crea_nada_nuevo(
    primera_y_replay, conexion_revertida, referencias, clave_de_idempotencia
):
    """La cuenta después del reenvío es la misma que después de la creación."""
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_lecturas(conexion_revertida, referencias.id_embarazo) == 2
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1


def test_tres_envios_identicos_siguen_dejando_una_sola_sesion(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    cuerpo = paquete_de_signos(referencias)

    respuestas = [cliente.post(RUTA, json=cuerpo) for _ in range(3)]

    assert [r.status_code for r in respuestas] == [201, 201, 201]
    assert [r.headers[CABECERA_REPLAY] for r in respuestas] == ["false", "true", "true"]
    assert len({r.json()["id_sesion"] for r in respuestas}) == 1
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1


# ---------------------------------------------------------------------------
# 4. Colisión secuencial
# ---------------------------------------------------------------------------


@pytest.fixture
def colision(cliente, referencias):
    """La misma clave con un contenido deliberadamente distinto."""
    original = paquete_de_signos(referencias)
    primera = cliente.post(RUTA, json=original)

    distinto = paquete_de_movimiento(referencias)
    segunda = cliente.post(RUTA, json=distinto)
    return original, primera, segunda


def test_la_misma_clave_con_otro_contenido_devuelve_409(colision):
    _, _, segunda = colision

    assert segunda.status_code == 409
    assert segunda.json()["detail"] == MENSAJE_COLISION


def test_la_colision_no_crea_filas_adicionales(
    colision, conexion_revertida, referencias, clave_de_idempotencia
):
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_lecturas(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1


def test_la_colision_no_modifica_la_operacion_original(
    colision, conexion_revertida, referencias, clave_de_idempotencia
):
    """La sesión y la reclamación quedan idénticas campo por campo."""
    original, primera, _ = colision
    sesion = sesiones_del_embarazo(conexion_revertida, referencias.id_embarazo)[0]
    fila = reclamaciones(conexion_revertida, clave_de_idempotencia)[0]

    assert sesion["id_sesion"] == primera.json()["id_sesion"]
    assert sesion["tipo_sesion"].value == original["tipo_sesion"]
    assert fila["huella"] == huella_de(original)
    assert fila["id_sesion"] == primera.json()["id_sesion"]
    assert list(fila["ids_lectura"]) == primera.json()["ids_lectura"]


def test_la_colision_no_revela_el_contenido_anterior(colision):
    _, primera, segunda = colision
    cuerpo = segunda.text

    assert str(primera.json()["id_sesion"]) not in cuerpo
    for identificador in primera.json()["ids_lectura"]:
        assert str(identificador) not in cuerpo
    for fragmento in FRAGMENTOS_PROHIBIDOS:
        assert fragmento not in cuerpo


# ---------------------------------------------------------------------------
# 5. Claves diferentes: dos operaciones
# ---------------------------------------------------------------------------


def test_dos_claves_distintas_con_el_mismo_cuerpo_crean_dos_sesiones(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """No se deduplica por contenido: dos monitoreos iguales son dos registros."""
    cuerpo = paquete_de_signos(referencias)

    primera = cliente.post(RUTA, json=cuerpo)
    segunda = cliente.post(
        RUTA,
        json=cuerpo,
        headers={CABECERA_IDEMPOTENCIA: clave_derivada(clave_de_idempotencia, "2")},
    )

    assert primera.status_code == 201
    assert segunda.status_code == 201
    assert segunda.headers[CABECERA_REPLAY] == "false"
    assert primera.json()["id_sesion"] != segunda.json()["id_sesion"]
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 2
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1
    assert (
        contar_reclamaciones(
            conexion_revertida, clave_derivada(clave_de_idempotencia, "2")
        )
        == 1
    )


# ---------------------------------------------------------------------------
# 6. Fallos posteriores a la reclamación
# ---------------------------------------------------------------------------


def _paquete_con_referencia_inexistente(referencias):
    return paquete_de_signos(referencias, id_dispositivo=ID_INEXISTENTE)


def _paquete_que_rompe_una_regla(referencias):
    """Movimiento fetal en la semana 12: la regla del dominio lo rechaza."""
    return paquete_de_movimiento(referencias, ventana=VENTANA_TEMPRANA)


def _paquete_que_rompe_un_check(referencias):
    """``spo2_valor`` fuera de rango: lo rechaza PostgreSQL, no Pydantic."""
    return paquete_de_signos(
        referencias,
        lecturas=[lectura_de_signos(referencias, spo2_valor=SPO2_FUERA_DE_RANGO)],
    )


@pytest.mark.parametrize(
    ("constructor", "esperado"),
    [
        (_paquete_con_referencia_inexistente, 404),
        (_paquete_que_rompe_una_regla, 422),
        (_paquete_que_rompe_un_check, 422),
    ],
    ids=["referencia_inexistente", "regla_de_negocio", "check_de_postgresql"],
)
def test_un_fallo_posterior_a_la_reclamacion_no_deja_reclamacion(
    constructor, esperado, cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """La clave se reclama antes de trabajar, y el rollback se la lleva.

    Los tres fallos ocurren **después** del INSERT de la reclamación, cada uno en
    un punto distinto: la verificación de referencias, la regla del dominio y un
    CHECK que solo PostgreSQL puede aplicar. En los tres, lo que queda es nada.
    """
    respuesta = cliente.post(RUTA, json=constructor(referencias))

    assert respuesta.status_code == esperado
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 0
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 0
    assert contar_lecturas(conexion_revertida, referencias.id_embarazo) == 0


@pytest.mark.parametrize(
    "constructor",
    [
        _paquete_con_referencia_inexistente,
        _paquete_que_rompe_una_regla,
        _paquete_que_rompe_un_check,
    ],
    ids=["referencia_inexistente", "regla_de_negocio", "check_de_postgresql"],
)
def test_la_clave_sigue_siendo_utilizable_despues_de_un_fallo(
    constructor, cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """La prueba de que la clave no queda envenenada: el reintento corregido crea."""
    fallida = cliente.post(RUTA, json=constructor(referencias))
    assert fallida.status_code in (404, 422)

    corregida = cliente.post(RUTA, json=paquete_de_signos(referencias))

    assert corregida.status_code == 201
    assert corregida.headers[CABECERA_REPLAY] == "false"
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 1


def test_una_colision_de_secuencia_sigue_siendo_500_y_libera_la_clave(
    cliente, referencias, conexion_revertida, clave_de_idempotencia, engine_de_pruebas
):
    """23505 interno: sigue siendo 500, y tampoco envenena la clave.

    La secuencia se adelanta hasta un ``id_sesion`` ya ocupado, de modo que el
    INSERT de la sesión choca de verdad contra ``pk_sesion_monitoreo``. Ocurre
    después de la reclamación, así que sirve para las dos cosas.

    El ``ALTER SEQUENCE`` vive dentro de la transacción exterior, que siempre se
    revierte; la evidencia del rollback no es el valor final de la secuencia sino
    el conteo de filas.
    """
    primera = cliente.post(
        RUTA,
        json=paquete_de_signos(referencias),
        headers={CABECERA_IDEMPOTENCIA: clave_derivada(clave_de_idempotencia, "previa")},
    )
    assert primera.status_code == 201
    id_ocupado = int(primera.json()["id_sesion"])

    secuencia = localizar_secuencia(
        conexion_revertida, SesionMonitoreo.__table__, "id_sesion"
    )
    conexion_revertida.execute(
        text(f"ALTER SEQUENCE {secuencia} RESTART WITH {id_ocupado}")
    )

    choque = cliente.post(RUTA, json=paquete_de_signos(referencias, tipo_sesion="SIGNOS_MATERNOS"))

    assert choque.status_code == 500
    assert choque.json()["detail"] == MENSAJE_INESPERADO
    assert contar_reclamaciones(conexion_revertida, clave_de_idempotencia) == 0
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 1


# ---------------------------------------------------------------------------
# 7. Anomalía: una reclamación incompleta nunca se reproduce
# ---------------------------------------------------------------------------


def test_una_reclamacion_incompleta_confirmada_produce_500(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """Se siembra a mano el estado que el diseño dice que no puede ocurrir.

    La fila se inserta sin resultado -- el CHECK lo permite, porque es el estado
    intermedio legítimo de una reclamación en curso --, y luego se pide el mismo
    paquete. El endpoint no puede reproducir una respuesta que no existe, así
    que responde 500 saneado en vez de inventar un replay.
    """
    cuerpo = paquete_de_signos(referencias)
    conexion_revertida.execute(
        insert(IdempotenciaSolicitud).values(
            recurso=RECURSO_SESIONES_MONITOREO,
            clave=clave_de_idempotencia,
            huella=huella_de(cuerpo),
        )
    )

    respuesta = cliente.post(RUTA, json=cuerpo)

    assert respuesta.status_code == 500
    assert respuesta.json()["detail"] == MENSAJE_INESPERADO
    assert contar_sesiones(conexion_revertida, referencias.id_embarazo) == 0


def test_una_reclamacion_incompleta_con_otra_huella_tambien_es_500(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """Nunca 409: no hay operación completa contra la que declarar colisión."""
    conexion_revertida.execute(
        insert(IdempotenciaSolicitud).values(
            recurso=RECURSO_SESIONES_MONITOREO,
            clave=clave_de_idempotencia,
            huella="huella-de-otro-paquete-completamente-distinto",
        )
    )

    respuesta = cliente.post(RUTA, json=paquete_de_signos(referencias))

    assert respuesta.status_code == 500
    assert respuesta.json()["detail"] == MENSAJE_INESPERADO
    assert respuesta.json()["detail"] != MENSAJE_COLISION


# ---------------------------------------------------------------------------
# 8. Integridad real
# ---------------------------------------------------------------------------


def test_borrar_una_sesion_con_reclamacion_lo_rechaza_restrict(
    cliente, referencias, conexion_revertida
):
    """``ON DELETE RESTRICT`` protege la reclamación de desaparecer en silencio.

    Con CASCADE, borrar la sesión liberaría la clave sin que nadie lo decidiera
    y el siguiente reenvío crearía una segunda sesión. PostgreSQL lo impide.
    """
    respuesta = cliente.post(RUTA, json=paquete_de_signos(referencias))
    id_sesion = respuesta.json()["id_sesion"]

    with pytest.raises(IntegrityError) as excepcion:
        with conexion_revertida.begin_nested():
            conexion_revertida.execute(
                delete(SesionMonitoreo).where(SesionMonitoreo.id_sesion == id_sesion)
            )

    assert excepcion.value.orig.sqlstate == "23503"


def test_el_update_de_finalizacion_afecta_exactamente_una_fila(
    cliente, referencias, conexion_revertida, clave_de_idempotencia
):
    """El ``rowcount`` que el servicio exige, comprobado contra el servidor real."""
    cliente.post(RUTA, json=paquete_de_signos(referencias))
    fila = reclamaciones(conexion_revertida, clave_de_idempotencia)[0]

    resultado = conexion_revertida.execute(
        IdempotenciaSolicitud.__table__.update()
        .where(
            IdempotenciaSolicitud.id_idempotencia == fila["id_idempotencia"]
        )
        .values(ids_lectura=list(fila["ids_lectura"]))
    )

    assert resultado.rowcount == 1


def test_la_relacion_sesion_lecturas_sigue_siendo_uno_a_muchos(
    cliente, referencias, conexion_revertida
):
    cuerpo = paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=90 + indice) for indice in range(4)
        ],
    )

    respuesta = cliente.post(RUTA, json=cuerpo)
    lecturas = lecturas_del_embarazo(conexion_revertida, referencias.id_embarazo)

    assert len(lecturas) == 4
    assert {lectura["id_sesion"] for lectura in lecturas} == {
        respuesta.json()["id_sesion"]
    }


# ---------------------------------------------------------------------------
# 9. Semántica heredada y saneamiento
# ---------------------------------------------------------------------------


def test_una_referencia_inexistente_sigue_devolviendo_404(cliente, referencias):
    respuesta = cliente.post(
        RUTA, json=_paquete_con_referencia_inexistente(referencias)
    )

    assert respuesta.status_code == 404


def test_un_check_de_postgresql_sigue_devolviendo_422(cliente, referencias):
    respuesta = cliente.post(RUTA, json=_paquete_que_rompe_un_check(referencias))

    assert respuesta.status_code == 422


@pytest.mark.parametrize(
    "constructor",
    [
        _paquete_con_referencia_inexistente,
        _paquete_que_rompe_una_regla,
        _paquete_que_rompe_un_check,
    ],
    ids=["404", "422_regla", "422_check"],
)
def test_ninguna_respuesta_de_error_filtra_internos(
    constructor, cliente, referencias
):
    respuesta = cliente.post(RUTA, json=constructor(referencias))
    cuerpo = respuesta.text

    for fragmento in FRAGMENTOS_PROHIBIDOS:
        assert fragmento not in cuerpo


def test_la_respuesta_de_colision_no_nombra_la_restriccion(colision):
    _, _, segunda = colision

    assert "uq_idempotencia_solicitud_recurso_clave" not in segunda.text
    assert "23505" not in segunda.text
    assert "constraint" not in segunda.text.lower()


# ---------------------------------------------------------------------------
# 10. Concurrencia real: dos solicitudes, dos conexiones, un solo ganador
# ---------------------------------------------------------------------------
#
# Lo que estas pruebas tienen que demostrar no es que dos peticiones «salgan a la
# vez» -- eso no prueba nada, porque nada garantiza que se encuentren en el punto
# que importa. Lo que hay que demostrar es que **la perdedora llegó a PostgreSQL
# y se quedó esperando a la transacción de la ganadora**, y para eso hace falta
# detener a la ganadora en un punto conocido, posterior a su reclamación.
#
# La coreografía usa un candado que el propio endpoint toma sin saberlo, así que
# no hay ni un hook de prueba en el código productivo:
#
#   1. Una conexión de control toma ``LOCK TABLE operacional.embarazo IN ACCESS
#      EXCLUSIVE MODE``. Ese modo entra en conflicto con el ACCESS SHARE que toma
#      cualquier ``SELECT``.
#   2. La solicitud A entra: consulta la vía rápida y **reclama la clave** -- la
#      tabla de idempotencia no está bloqueada --, y queda detenida en el primer
#      ``SELECT`` de ``verificar_referencias``, que lee ``embarazo``. Su
#      transacción sigue abierta, con la reclamación tomada y sin confirmar.
#   3. La solicitud B entra con la misma clave y queda detenida en su
#      ``INSERT ... ON CONFLICT``, bloqueada por la entrada no confirmada de A en
#      el índice único.
#   4. Se comprueba con ``pg_blocking_pids`` que **B está bloqueada por A**. Ésa
#      es la evidencia, y no la simultaneidad del arranque.
#   5. El control libera. A continúa y decide el desenlace.
#
# Sobre las esperas: no se usan sleeps fijos para asumir simultaneidad; se
# sondean condiciones observables con intervalos breves y un deadline. Si la
# condición no se cumple, la prueba falla por tiempo agotado en vez de continuar
# a ciegas.

TIEMPO_MAXIMO_DE_ESPERA = 20.0
INTERVALO_DE_SONDEO = 0.02
TIEMPO_MAXIMO_DE_RESPUESTA = 30.0

# Último recurso, del lado del servidor. La coordinación de Python ya libera el
# candado en un ``finally``, pero si *esa* liberación fallara, un worker seguiría
# esperando dentro de PostgreSQL y ninguna cantidad de deadlines en Python lo
# desbloquearía: el hilo no se puede interrumpir desde fuera. Con estos límites
# el servidor aborta la sentencia por su cuenta, el worker termina y el proceso
# no puede quedarse colgado -- ni siquiera en el ``atexit`` de
# ``concurrent.futures``, que sí hace join de los hilos vivos.
#
# Se aplican **solo a las conexiones de este arnés**: no tocan la configuración
# del servidor ni la del engine de la aplicación.
#
# Son mayores que ``TIEMPO_MAXIMO_DE_ESPERA`` a propósito, para que en el camino
# normal nunca se disparen antes que la coordinación.
ESPERA_MAXIMA_DE_CANDADO = "25s"
ESPERA_MAXIMA_DE_SENTENCIA = "30s"
OPCIONES_DE_LIMITE = (
    f"-c lock_timeout={ESPERA_MAXIMA_DE_CANDADO} "
    f"-c statement_timeout={ESPERA_MAXIMA_DE_SENTENCIA}"
)

# Prefijo de todo lo que crean los escenarios concurrentes. Es lo que permite
# limpiar exactamente lo que se creó, sin TRUNCATE y sin borrados generales.
MARCA = "SCRUM63C"

# Cabecera exclusiva de las pruebas: dice a qué participante pertenece la
# solicitud. No la lee ni la conoce el código productivo -- solo la sustitución
# de ``get_db`` que instalan estas pruebas.
#
# Hizo falta porque un ``threading.local`` no sirve aquí: FastAPI ejecuta un
# endpoint síncrono, y sus dependencias, en un hilo del threadpool, no en el que
# envía la petición. El engine tiene que viajar con la solicitud, y la cabecera
# es la forma más simple de que lo haga.
CABECERA_PARTICIPANTE = "X-Participante-De-Prueba"

_ENGINES_POR_PARTICIPANTE: dict[str, Any] = {}


def _sesion_del_participante(peticion: Request):
    """Dependencia ``get_db`` durante la concurrencia: una Session por petición.

    Cada solicitud abre su propia ``Session`` sobre el engine de su participante,
    y cada engine tiene su propia conexión. No se comparte ninguna, y no se
    reutiliza la ``sesion_de_pruebas`` secuencial.
    """
    engine = _ENGINES_POR_PARTICIPANTE[peticion.headers[CABECERA_PARTICIPANTE]]
    sesion = Session(bind=engine)
    try:
        yield sesion
    finally:
        sesion.close()


@dataclass
class Participante:
    """Una solicitud concurrente con todo lo suyo: engine, conexión y cliente."""

    nombre: str
    engine: Any
    cliente: TestClient


def esperar_a(
    condicion,
    descripcion: str,
    limite: float = TIEMPO_MAXIMO_DE_ESPERA,
    futuros=(),
):
    """Sondea una condición observable hasta que se cumpla, o falla por deadline.

    El ``sleep`` de aquí dentro es el intervalo entre sondeos, nunca el
    mecanismo de sincronización: lo que decide es la condición, y el límite
    existe para que una prueba concurrente no pueda dejar CI colgado.

    ``futuros`` son las solicitudes que deberían seguir en vuelo. Si alguna
    termina antes de que la condición se cumpla, la espera se corta y se reporta
    **su** desenlace: una petición que murió pronto explica el problema, y
    esperar veinte segundos para decir «tiempo agotado» lo esconde.
    """
    fin = time.monotonic() + limite
    while time.monotonic() < fin:
        valor = condicion()
        if valor:
            return valor
        for futuro in futuros:
            if futuro.done():
                try:
                    respuesta = futuro.result(timeout=1)
                except Exception as error:  # noqa: BLE001 -- se reporta tal cual
                    pytest.fail(
                        f"Una solicitud terminó con una excepción mientras se "
                        f"esperaba «{descripcion}»: "
                        f"{type(error).__name__}: {error}"
                    )
                pytest.fail(
                    f"Una solicitud terminó antes de tiempo mientras se esperaba "
                    f"«{descripcion}»: http={respuesta.status_code} "
                    f"cuerpo={respuesta.text[:300]}"
                )
        time.sleep(INTERVALO_DE_SONDEO)
    pytest.fail(f"Tiempo agotado ({limite}s) esperando: {descripcion}")


def pid_de(observador, nombre_app: str):
    return observador.execute(
        text("select pid from pg_stat_activity where application_name = :n"),
        {"n": nombre_app},
    ).scalar()


def bloqueado_por(observador, pid: int) -> list[int]:
    return list(
        observador.execute(text("select pg_blocking_pids(:p)"), {"p": pid}).scalar() or []
    )


def esta_esperando_un_candado(observador, pid: int) -> bool:
    fila = observador.execute(
        text("select wait_event_type from pg_stat_activity where pid = :p"), {"p": pid}
    ).scalar()
    return fila == "Lock"


@dataclass
class EntornoConcurrente:
    """Referencias confirmadas y participantes, con su limpieza dirigida."""

    referencias: Referencias
    observador: Any
    control: Any
    participantes: list[Participante]
    clave: str


@pytest.fixture
def entorno_concurrente(engine_de_pruebas, url_de_pruebas, request):
    """Referencias **confirmadas** y dos participantes independientes.

    La concurrencia no cabe en el aislamiento por transacción revertida: dos
    transacciones distintas no pueden ver las filas de referencia de una tercera
    sin confirmar. Por eso aquí se confirma, y por eso la limpieza es explícita:
    se borra exactamente lo que se creó, en orden inverso de llaves foráneas, y
    nada más. Sin TRUNCATE, sin DROP y sin borrados generales.
    """
    sufijo = hashlib.sha256(request.node.nodeid.encode("utf-8")).hexdigest()[:10]
    clave = f"{MARCA}-{sufijo}"

    # Catálogos: se anota lo que ya existía para no borrar nada ajeno.
    with engine_de_pruebas.connect() as conexion:
        tiempos_previos = set(
            conexion.execute(select(TiempoGestacional.id_tiempo_gest)).scalars().all()
        )
        semaforos_previos = set(
            conexion.execute(select(Semaforo.id_semaforo)).scalars().all()
        )

    with engine_de_pruebas.begin() as conexion:
        id_clinica = conexion.execute(
            insert(Clinica)
            .values(
                nombre_clinica=f"Clinica {MARCA} {sufijo}",
                ruc=f"{MARCA}-RUC-{sufijo}",
                provincia="Chiriquí",
                distrito="Renacimiento",
                corregimiento="Plaza Caisán",
                direccion_fisica="Dirección simulada sin correspondencia real",
            )
            .returning(Clinica.id_clinica)
        ).scalar_one()
        id_paciente = conexion.execute(
            insert(Paciente)
            .values(
                cedula=f"{MARCA}-{sufijo}",
                primer_nombre="Gestante",
                apellido_paterno="Simulada",
                email_pac=f"{MARCA}.{sufijo}@example.invalid",
                fecha_nac=date(1998, 5, 14),
            )
            .returning(Paciente.id_paciente)
        ).scalar_one()
        id_embarazo = conexion.execute(
            insert(Embarazo)
            .values(
                id_paciente=id_paciente,
                id_clinica=id_clinica,
                numero_gestas=2,
                numero_partos=1,
                fecha_inicio=FECHA_INICIO_EMBARAZO,
                fecha_probable_parto=FECHA_PROBABLE_PARTO,
            )
            .returning(Embarazo.id_embarazo)
        ).scalar_one()
        id_dispositivo = _crear_dispositivo(
            conexion, id_clinica, f"{MARCA}-DISP-{sufijo}"
        )
        id_sin_asignar = _crear_dispositivo(
            conexion, id_clinica, f"{MARCA}-LIBRE-{sufijo}"
        )
        id_asignacion = _crear_asignacion(
            conexion,
            id_dispositivo=id_dispositivo,
            id_embarazo=id_embarazo,
            fecha_inicio=FECHA_INICIO_EMBARAZO,
            fecha_fin=None,
        )
        referencias_creadas = Referencias(
            id_clinica=id_clinica,
            id_paciente=id_paciente,
            id_embarazo=id_embarazo,
            id_dispositivo=id_dispositivo,
            id_dispositivo_sin_asignar=id_sin_asignar,
            id_asignacion=id_asignacion,
            id_tiempo_por_semana=_asegurar_semanas(
                conexion, (VENTANA.semana, VENTANA_TEMPRANA.semana)
            ),
            id_semaforo=_asegurar_semaforo(conexion),
        )

    participantes = [
        Participante(
            nombre=f"{MARCA}-{sufijo}-{letra}",
            engine=create_engine(
                url_de_pruebas,
                pool_size=1,
                max_overflow=0,
                connect_args={
                    "application_name": f"{MARCA}-{sufijo}-{letra}",
                    "options": OPCIONES_DE_LIMITE,
                },
            ),
            cliente=None,
        )
        for letra in ("A", "B")
    ]
    for participante in participantes:
        participante.cliente = TestClient(app)

    observador = engine_de_pruebas.connect().execution_options(
        isolation_level="AUTOCOMMIT"
    )
    control = engine_de_pruebas.connect()

    for participante in participantes:
        _ENGINES_POR_PARTICIPANTE[participante.nombre] = participante.engine
    anterior = app.dependency_overrides.get(get_db)
    app.dependency_overrides[get_db] = _sesion_del_participante

    entorno = EntornoConcurrente(
        referencias=referencias_creadas,
        observador=observador,
        control=control,
        participantes=participantes,
        clave=clave,
    )
    try:
        yield entorno
    finally:
        if anterior is None:
            app.dependency_overrides.pop(get_db, None)
        else:
            app.dependency_overrides[get_db] = anterior
        for participante in participantes:
            _ENGINES_POR_PARTICIPANTE.pop(participante.nombre, None)
        control.close()
        observador.close()
        for participante in participantes:
            participante.cliente.close()
            participante.engine.dispose()

        # Limpieza dirigida, en orden inverso de llaves foráneas. La reclamación
        # va primero: su FK RESTRICT impide borrar la sesión antes.
        with engine_de_pruebas.begin() as conexion:
            conexion.execute(
                delete(IdempotenciaSolicitud).where(
                    IdempotenciaSolicitud.clave.like(f"{MARCA}-{sufijo}%")
                )
            )
            conexion.execute(
                delete(SesionMonitoreo).where(
                    SesionMonitoreo.id_embarazo == id_embarazo
                )
            )
            conexion.execute(
                delete(AsignacionDispositivo).where(
                    AsignacionDispositivo.id_embarazo == id_embarazo
                )
            )
            conexion.execute(delete(Embarazo).where(Embarazo.id_embarazo == id_embarazo))
            conexion.execute(
                delete(Dispositivo).where(
                    Dispositivo.id_dispositivo.in_([id_dispositivo, id_sin_asignar])
                )
            )
            conexion.execute(delete(Paciente).where(Paciente.id_paciente == id_paciente))
            conexion.execute(delete(Clinica).where(Clinica.id_clinica == id_clinica))
            # Del catálogo, solo lo que esta prueba llegó a crear.
            conexion.execute(
                delete(TiempoGestacional).where(
                    TiempoGestacional.id_tiempo_gest.in_(
                        set(referencias_creadas.id_tiempo_por_semana.values())
                        - tiempos_previos
                    )
                )
            )
            conexion.execute(
                delete(Semaforo).where(
                    Semaforo.id_semaforo.in_(
                        {referencias_creadas.id_semaforo} - semaforos_previos
                    )
                )
            )


def enviar(participante: Participante, cuerpo: dict[str, Any], clave: str):
    return participante.cliente.post(
        RUTA,
        json=cuerpo,
        headers={
            CABECERA_IDEMPOTENCIA: clave,
            CABECERA_PARTICIPANTE: participante.nombre,
        },
    )


@dataclass
class Carrera:
    """Lo observado durante la carrera, para que las pruebas lo afirmen."""

    respuesta_a: Any
    respuesta_b: Any
    pid_a: int
    pid_b: int
    bloqueadores_de_b: list[int]
    b_esperaba_un_candado: bool


def liberar_el_control(control) -> None:
    """Suelta el candado del control. Idempotente y tolerante a fallos.

    Se llama dos veces a propósito: en el paso 5 del camino normal, que es
    cuando la carrera tiene que resolverse, y otra vez en el ``finally``, que es
    lo que cubre todos los caminos de error. Un segundo ``rollback`` sobre una
    conexión sin transacción abierta no hace nada.

    Si la conexión ya está inservible, el error se descarta: estamos en la
    limpieza, y tapar la excepción que nos trajo hasta aquí sería peor que no
    poder soltar un candado que los límites del servidor van a resolver igual.
    """
    try:
        control.rollback()
    except SQLAlchemyError:
        pass


def correr_carrera(entorno: EntornoConcurrente, cuerpo_a, cuerpo_b) -> Carrera:
    """Ejecuta la coreografía completa y devuelve la evidencia recogida.

    **Por qué el executor se gestiona a mano y no con ``with``.** El
    ``__exit__`` de ``ThreadPoolExecutor`` llama a ``shutdown(wait=True)``, que
    espera a que terminen los workers en vuelo. En el camino normal eso es
    inocuo, pero en cualquier camino de error sería una trampa: las dos
    solicitudes están bloqueadas dentro de PostgreSQL esperando el candado que
    tiene el control, el ``finally`` que lo suelta todavía no ha corrido, y la
    espera no termina nunca. Los deadlines de arriba quedarían anulados
    justamente cuando hacen falta.

    Así que el orden es el inverso: primero se suelta el candado —lo que deja a
    los workers terminar—, y solo después se cierra el executor **sin esperar**.
    """
    a, b = entorno.participantes
    observador = entorno.observador

    # 1. El control detiene cualquier lectura de 'embarazo'.
    entorno.control.execute(
        text(f"LOCK TABLE {SCHEMA_OPERACIONAL}.embarazo IN ACCESS EXCLUSIVE MODE")
    )

    ejecutor = ThreadPoolExecutor(max_workers=2)
    try:
        futuro_a = ejecutor.submit(enviar, a, cuerpo_a, entorno.clave)

        # 2. A reclamó la clave y quedó detenida al leer 'embarazo'.
        pid_a = esperar_a(
            lambda: pid_de(observador, a.nombre),
            "que la solicitud A abra su conexión",
            futuros=(futuro_a,),
        )
        esperar_a(
            lambda: esta_esperando_un_candado(observador, pid_a),
            "que la solicitud A quede esperando el candado de la tabla",
            futuros=(futuro_a,),
        )
        esperar_a(
            lambda: contar_reclamaciones_en(observador, entorno.clave) == 0,
            "que la reclamación de A siga sin confirmar",
            futuros=(futuro_a,),
        )

        futuro_b = ejecutor.submit(enviar, b, cuerpo_b, entorno.clave)

        # 3-4. B llegó a PostgreSQL y espera por la transacción de A.
        pid_b = esperar_a(
            lambda: pid_de(observador, b.nombre),
            "que la solicitud B abra su conexión",
            futuros=(futuro_b,),
        )
        bloqueadores = esperar_a(
            lambda: (
                bloqueado_por(observador, pid_b)
                if pid_a in bloqueado_por(observador, pid_b)
                else None
            ),
            "que la solicitud B quede bloqueada por la transacción de A",
            futuros=(futuro_b,),
        )
        b_esperaba = esta_esperando_un_candado(observador, pid_b)

        # 5. Se libera y cada una decide su desenlace.
        liberar_el_control(entorno.control)

        respuesta_a = futuro_a.result(timeout=TIEMPO_MAXIMO_DE_RESPUESTA)
        respuesta_b = futuro_b.result(timeout=TIEMPO_MAXIMO_DE_RESPUESTA)
    finally:
        # El orden importa: soltar el candado desbloquea a los workers, y solo
        # entonces se cierra el executor. ``wait=False`` es lo que garantiza que
        # ningún camino de error se quede atrapado aquí, y ``cancel_futures``
        # descarta lo que aún no hubiera arrancado.
        liberar_el_control(entorno.control)
        ejecutor.shutdown(wait=False, cancel_futures=True)

    return Carrera(
        respuesta_a=respuesta_a,
        respuesta_b=respuesta_b,
        pid_a=pid_a,
        pid_b=pid_b,
        bloqueadores_de_b=bloqueadores,
        b_esperaba_un_candado=b_esperaba,
    )


def contar_reclamaciones_en(conexion, clave: str) -> int:
    return conexion.execute(
        select(func.count())
        .select_from(IdempotenciaSolicitud)
        .where(IdempotenciaSolicitud.clave == clave)
    ).scalar_one()


def paquete_de_tres_lecturas(referencias: Referencias) -> dict[str, Any]:
    return paquete_de_signos(
        referencias,
        lecturas=[
            lectura_de_signos(referencias, spo2_valor=95 + indice) for indice in range(3)
        ],
    )


# ---------------------------------------------------------------------------
# 10a. Idénticas
# ---------------------------------------------------------------------------


@pytest.fixture
def carrera_identica(entorno_concurrente):
    cuerpo = paquete_de_tres_lecturas(entorno_concurrente.referencias)
    return entorno_concurrente, cuerpo, correr_carrera(entorno_concurrente, cuerpo, cuerpo)


def test_concurrencia_las_dos_conexiones_son_distintas(carrera_identica):
    """Dos backends de PostgreSQL distintos: no es concurrencia simulada."""
    _, _, carrera = carrera_identica

    assert carrera.pid_a != carrera.pid_b


def test_concurrencia_la_perdedora_espero_a_la_ganadora(carrera_identica):
    """La evidencia que una barrera de arranque no puede dar.

    B no «salió a la vez»: llegó a PostgreSQL, intentó su reclamación y quedó
    bloqueada por la transacción de A, que ya tenía la clave tomada y sin
    confirmar. Lo dice ``pg_blocking_pids``, no el reloj.
    """
    _, _, carrera = carrera_identica

    assert carrera.pid_a in carrera.bloqueadores_de_b
    assert carrera.b_esperaba_un_candado is True


def test_concurrencia_identica_devuelve_dos_201(carrera_identica):
    _, _, carrera = carrera_identica

    assert carrera.respuesta_a.status_code == 201
    assert carrera.respuesta_b.status_code == 201


def test_concurrencia_identica_marca_una_creacion_y_un_reenvio(carrera_identica):
    _, _, carrera = carrera_identica
    marcas = sorted(
        [
            carrera.respuesta_a.headers[CABECERA_REPLAY],
            carrera.respuesta_b.headers[CABECERA_REPLAY],
        ]
    )

    assert marcas == ["false", "true"]


def test_concurrencia_identica_devuelve_el_mismo_cuerpo(carrera_identica):
    _, _, carrera = carrera_identica

    assert carrera.respuesta_a.json() == carrera.respuesta_b.json()
    assert (
        carrera.respuesta_a.json()["id_sesion"] == carrera.respuesta_b.json()["id_sesion"]
    )
    assert (
        carrera.respuesta_a.json()["ids_lectura"]
        == carrera.respuesta_b.json()["ids_lectura"]
    )


def test_concurrencia_identica_crea_exactamente_una_operacion(carrera_identica):
    entorno, _, carrera = carrera_identica
    embarazo = entorno.referencias.id_embarazo

    assert contar_sesiones(entorno.observador, embarazo) == 1
    assert contar_lecturas(entorno.observador, embarazo) == 3
    assert contar_reclamaciones_en(entorno.observador, entorno.clave) == 1


def test_concurrencia_identica_deja_la_reclamacion_completa(carrera_identica):
    entorno, _, carrera = carrera_identica
    fila = (
        entorno.observador.execute(
            select(IdempotenciaSolicitud).where(
                IdempotenciaSolicitud.clave == entorno.clave
            )
        )
        .mappings()
        .one()
    )

    assert fila["id_sesion"] == carrera.respuesta_a.json()["id_sesion"]
    assert list(fila["ids_lectura"]) == carrera.respuesta_a.json()["ids_lectura"]


# ---------------------------------------------------------------------------
# 10b. Colisión concurrente
# ---------------------------------------------------------------------------


@pytest.fixture
def carrera_con_colision(entorno_concurrente):
    referencias = entorno_concurrente.referencias
    cuerpo_a = paquete_de_tres_lecturas(referencias)
    cuerpo_b = paquete_de_movimiento(referencias)
    return (
        entorno_concurrente,
        cuerpo_a,
        cuerpo_b,
        correr_carrera(entorno_concurrente, cuerpo_a, cuerpo_b),
    )


def test_concurrencia_con_colision_devuelve_201_y_409(carrera_con_colision):
    """El UNIQUE de PostgreSQL decidió la carrera, no el orden del scheduler."""
    _, _, _, carrera = carrera_con_colision
    codigos = sorted(
        [carrera.respuesta_a.status_code, carrera.respuesta_b.status_code]
    )

    assert codigos == [201, 409]
    assert carrera.respuesta_a.status_code == 201
    assert carrera.respuesta_b.status_code == 409
    assert carrera.respuesta_b.json()["detail"] == MENSAJE_COLISION


def test_concurrencia_con_colision_persiste_solo_el_paquete_ganador(
    carrera_con_colision,
):
    """Ni una lectura del perdedor, ni una mezcla de los dos paquetes."""
    entorno, cuerpo_a, _, carrera = carrera_con_colision
    embarazo = entorno.referencias.id_embarazo
    sesiones = sesiones_del_embarazo(entorno.observador, embarazo)
    lecturas = lecturas_del_embarazo(entorno.observador, embarazo)

    assert len(sesiones) == 1
    assert sesiones[0]["tipo_sesion"].value == cuerpo_a["tipo_sesion"]
    assert len(lecturas) == len(cuerpo_a["lecturas"])
    # El paquete perdedor era de movimiento fetal: ni una sola de sus lecturas.
    assert all(lectura["mov_valor"] is None for lectura in lecturas)
    assert all(lectura["hr_valor"] is not None for lectura in lecturas)
    assert contar_reclamaciones_en(entorno.observador, entorno.clave) == 1


def test_concurrencia_con_colision_no_revela_nada_del_ganador(carrera_con_colision):
    entorno, _, _, carrera = carrera_con_colision
    cuerpo = carrera.respuesta_b.text
    fila = (
        entorno.observador.execute(
            select(IdempotenciaSolicitud).where(
                IdempotenciaSolicitud.clave == entorno.clave
            )
        )
        .mappings()
        .one()
    )

    assert fila["huella"] not in cuerpo
    assert str(fila["id_sesion"]) not in cuerpo
    for fragmento in FRAGMENTOS_PROHIBIDOS:
        assert fragmento not in cuerpo


# ---------------------------------------------------------------------------
# 10c. La ganadora revierte: la clave vuelve a estar libre
# ---------------------------------------------------------------------------


@pytest.fixture
def carrera_con_ganadora_que_revierte(entorno_concurrente):
    """A reclama la clave y luego falla de verdad; B la toma y completa.

    El fallo de A no se simula: su paquete apunta a un dispositivo inexistente,
    así que ``verificar_referencias`` lo rechaza con 404 -- y lo hace **después**
    de la reclamación, que es el punto del escenario. Mientras A está detenida
    por el candado, su transacción sigue abierta con la clave tomada, y B espera.

    Cuando A revierte, PostgreSQL reevalúa la inserción especulativa de B: la
    fila de A está muerta, así que el ``ON CONFLICT DO NOTHING`` de B **inserta**
    en lugar de no hacer nada. Que eso ocurra de verdad es lo que sostiene la
    decisión de no reintentar en ningún sitio.
    """
    referencias = entorno_concurrente.referencias
    cuerpo_a = paquete_de_signos(referencias, id_dispositivo=ID_INEXISTENTE)
    cuerpo_b = paquete_de_tres_lecturas(referencias)
    return (
        entorno_concurrente,
        cuerpo_b,
        correr_carrera(entorno_concurrente, cuerpo_a, cuerpo_b),
    )


def test_la_ganadora_que_falla_devuelve_su_error_controlado(
    carrera_con_ganadora_que_revierte,
):
    _, _, carrera = carrera_con_ganadora_que_revierte

    assert carrera.respuesta_a.status_code == 404


def test_la_perdedora_adquiere_la_clave_y_completa(carrera_con_ganadora_que_revierte):
    """Tras el rollback de A, B deja de ser perdedora y crea el paquete."""
    _, _, carrera = carrera_con_ganadora_que_revierte

    assert carrera.respuesta_b.status_code == 201
    assert carrera.respuesta_b.headers[CABECERA_REPLAY] == "false"


def test_la_solicitud_fallida_no_deja_datos_parciales(
    carrera_con_ganadora_que_revierte,
):
    entorno, cuerpo_b, carrera = carrera_con_ganadora_que_revierte
    embarazo = entorno.referencias.id_embarazo
    sesiones = sesiones_del_embarazo(entorno.observador, embarazo)

    assert len(sesiones) == 1
    assert sesiones[0]["id_sesion"] == carrera.respuesta_b.json()["id_sesion"]
    assert contar_lecturas(entorno.observador, embarazo) == len(cuerpo_b["lecturas"])


def test_tras_el_rollback_queda_una_sola_reclamacion_y_es_la_de_la_exitosa(
    carrera_con_ganadora_que_revierte,
):
    entorno, _, carrera = carrera_con_ganadora_que_revierte
    fila = (
        entorno.observador.execute(
            select(IdempotenciaSolicitud).where(
                IdempotenciaSolicitud.clave == entorno.clave
            )
        )
        .mappings()
        .one()
    )

    assert contar_reclamaciones_en(entorno.observador, entorno.clave) == 1
    assert fila["id_sesion"] == carrera.respuesta_b.json()["id_sesion"]
    assert list(fila["ids_lectura"]) == carrera.respuesta_b.json()["ids_lectura"]


# ---------------------------------------------------------------------------
# 11. Estado final
# ---------------------------------------------------------------------------


def test_la_base_no_conserva_nada_de_esta_suite(engine_de_pruebas):
    """Cada prueba revierte su transacción exterior: no queda una sola fila.

    Se mira desde una conexión nueva, fuera de cualquier transacción de prueba.
    """
    with engine_de_pruebas.connect() as verificacion:
        assert (
            verificacion.execute(
                select(func.count()).select_from(IdempotenciaSolicitud)
            ).scalar_one()
            == 0
        )
        assert (
            verificacion.execute(
                select(func.count()).select_from(SesionMonitoreo)
            ).scalar_one()
            == 0
        )
        assert (
            verificacion.execute(
                select(func.count()).select_from(LecturaBiometrica)
            ).scalar_one()
            == 0
        )
