"""Esquema analítico y ETL contra un servidor PostgreSQL 16 real (SCRUM-69).

Se omite salvo que esté definida ``SCRUM69_TEST_DATABASE_URL``. Nunca cae por
omisión sobre ``DATABASE_URL`` ni sobre la variable de otra suite, y el workflow
de CI convierte la omisión en un job en rojo.

**Aislamiento por bases temporales.** Esa URL es solo la conexión de
mantenimiento: sobre la base a la que apunta esta suite no crea tablas, no migra
y no escribe una sola fila. Lo que hace es crear bases nuevas con el prefijo
``scrum69_tmp_`` más un identificador de ejecución, migrarlas, cargar el dataset
canónico, ejecutar el ETL con commits reales -- que es lo que hay que demostrar:
rollback, candado, idempotencia -- y eliminarlas al terminar. Solo elimina bases
que ella misma creó en esta ejecución, comprobadas por nombre, y termina antes
las conexiones que pudieran quedar abiertas contra ellas.

Una base «plantilla» se migra y se carga una sola vez; cada prueba que necesita
un estado limpio recibe una copia (``CREATE DATABASE ... TEMPLATE``), así que
ninguna ve lo que escribió otra.

Requiere un rol con permiso para crear bases (el superusuario efímero de CI lo
tiene). Ejecución desde ``backend/``::

    $env:SCRUM69_TEST_DATABASE_URL = "postgresql+psycopg://<usuario>:<clave>@127.0.0.1:<puerto>/<base>"
    .\\.venv\\Scripts\\python.exe -m pytest tests/test_etl_postgresql.py -v

Todos los datos son simulados y completamente ficticios.
"""

from __future__ import annotations

import itertools
import json
import os
import re
import time
import uuid
from collections import Counter
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import date, timedelta
from decimal import Decimal
from typing import Any

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi.testclient import TestClient
from sqlalchemy import CheckConstraint, create_engine, event, func, inspect, select, text
from sqlalchemy.engine import Engine, make_url
from sqlalchemy.orm import Session
from sqlalchemy.pool import NullPool

from app.api.v1.sesiones import CABECERA_IDEMPOTENCIA, CABECERA_REPLAY
from app.config import settings
from app.db.base import SCHEMA_OPERACIONAL, Base
from app.db.base_analitica import SCHEMA_ANALITICO
from app.db.session import get_db
from app.etl import (
    CLAVE_DEL_CANDADO,
    TABLAS_ANALITICAS,
    CandadoOcupado,
    CargaInconsistente,
    ConciliacionFallida,
    DerivacionAmbigua,
    DerivacionImposible,
    DiscrepanciaDeSemaforo,
    LecturaInvalida,
    VersionDeReglasDesconocida,
    conciliar_sin_escribir,
    ejecutar_etl,
    extraccion,
)
from app.loader import (
    MotorNoSoportado,
    cargar_dataset,
    preflight,
    validar_dataset,
    verificar_url,
)
from app.main import app
from tests.conftest import construir_config_alembic
from tests.test_etl_cli import cli  # noqa: F401  -- fixture del script
from tests.test_generate_mock_data import cargar_generador
from tests.test_load_mock_data_postgresql import FILAS_ESPERADAS
from tests.test_models import PG_MAX_IDENTIFIER_LENGTH, TABLAS_ESPERADAS

VARIABLE_DE_ENTORNO = "SCRUM69_TEST_DATABASE_URL"
PREFIJO_DE_BASE = "scrum69_tmp_"
PATRON_DE_BASE = re.compile(r"^scrum69_tmp_[0-9a-f]{8}_[a-z0-9_]{1,30}$")

pytestmark = pytest.mark.skipif(
    not os.environ.get(VARIABLE_DE_ENTORNO),
    reason=(
        f"Define {VARIABLE_DE_ENTORNO} apuntando a un servidor PostgreSQL donde "
        "el rol pueda crear bases temporales para validar el ETL analítico."
    ),
)

O, A = SCHEMA_OPERACIONAL, SCHEMA_ANALITICO

# --- Cantidades aprobadas del dataset canónico (SCRUM-54) --------------------
LECTURAS = 1180
SESIONES = 732
LECTURAS_HR = 560
LECTURAS_MOVIMIENTO = 620
SEMAFORO = {"OK": 826, "WARNING": 295, "ERROR": 59}
FACTORES_POR_EMBARAZO = {0: 14, 1: 9, 2: 7}
DIMENSIONES = {
    "dim_clinica": 3,
    "dim_semaforo": 3,
    "dim_tiempo_gestacional": 40,
    "dim_factor_riesgo": 3,
    "dim_medico": 5,
    "dim_paciente": 30,
    "dim_embarazo": 30,
    "bridge_embarazo_factor_riesgo": 23,
}
# Distribución por métrica que las reglas SIM-1.0 producen sobre el dataset
# canónico. No es una cantidad de la especificación: es la línea base observada,
# fijada para que un cambio en las reglas o en el generador no pase inadvertido.
ESTADOS_POR_METRICA = {
    "estado_hr": {"OK": 472, "WARNING": 76, "ERROR": 12},
    "estado_spo2": {"OK": 478, "WARNING": 64, "ERROR": 18},
    "estado_mov": {"OK": 436, "WARNING": 155, "ERROR": 29},
}

ID_OK, ID_WARNING = 100, 101
EMBARAZO_DE_PRUEBA = 100  # clínica 100, inicio 2025-01-06, médico 100 (PRINCIPAL)
MEDICO_DE_PRUEBA = 100
DISPOSITIVO_DE_PRUEBA = 100
INICIO_DEL_EMBARAZO_DE_PRUEBA = date(2025, 1, 6)
SEMANA_1, SEMANA_8, SEMANA_9, SEMANA_39 = 100, 107, 108, 138  # id_tiempo_gest
SEMANA_19 = 118  # antes de la 20 no existen movimientos fetales
RUTA = "/api/v1/sesiones-monitoreo"

# El paquete ficticio del handoff de SCRUM-65: aceptado por la API sobre la base
# canónica, con fechas de negocio de febrero de 2025.
PAQUETE_INCREMENTO = {
    "id_embarazo": EMBARAZO_DE_PRUEBA,
    "id_dispositivo": DISPOSITIVO_DE_PRUEBA,
    "tipo_sesion": "SIGNOS_MATERNOS",
    "fecha_inicio": "2025-02-24T14:20:00+00:00",
    "fecha_fin": "2025-02-24T14:25:00+00:00",
    "estado_sesion": "COMPLETADA",
    "lecturas": [
        {"id_tiempo_gest": SEMANA_8, "id_semaforo": ID_OK,
         "fecha_hora_captura": "2025-02-24T14:21:00+00:00",
         "fecha_hora_sincronizacion": None, "hr_valor": 88, "spo2_valor": 97,
         "mov_valor": None},
        {"id_tiempo_gest": SEMANA_8, "id_semaforo": ID_OK,
         "fecha_hora_captura": "2025-02-24T14:22:30+00:00",
         "fecha_hora_sincronizacion": None, "hr_valor": 91, "spo2_valor": 96,
         "mov_valor": None},
        {"id_tiempo_gest": SEMANA_8, "id_semaforo": ID_OK,
         "fecha_hora_captura": "2025-02-24T14:24:00+00:00",
         "fecha_hora_sincronizacion": None, "hr_valor": 89, "spo2_valor": 98,
         "mov_valor": None},
    ],
}

CONTADOR = itertools.count(1)


# ---------------------------------------------------------------------------
# Servidor, bases temporales y utilidades
# ---------------------------------------------------------------------------


class ServidorDePruebas:
    """Crea y elimina bases temporales; nunca toca una que no haya creado."""

    def __init__(self, url: str) -> None:
        self.url = make_url(url)
        self.ejecucion = uuid.uuid4().hex[:8]
        self.engine = create_engine(url, isolation_level="AUTOCOMMIT", poolclass=NullPool)
        self.creadas: list[str] = []

    def _citar(self, nombre: str) -> str:
        return self.engine.dialect.identifier_preparer.quote(nombre)

    def url_de(self, nombre: str) -> str:
        return self.url.set(database=nombre).render_as_string(hide_password=False)

    def crear(self, sufijo: str, *, plantilla: str | None = None) -> str:
        nombre = f"{PREFIJO_DE_BASE}{self.ejecucion}_{sufijo}"
        assert PATRON_DE_BASE.match(nombre), nombre
        # Los nombres se generan aquí y se validan contra el patrón: DDL no
        # admite parámetros, y nada externo llega a esta interpolación.
        sentencia = f"CREATE DATABASE {self._citar(nombre)}"
        if plantilla is not None:
            assert plantilla in self.creadas
            sentencia += f" TEMPLATE {self._citar(plantilla)}"
        with self.engine.connect() as conexion:
            conexion.execute(text(sentencia))
        self.creadas.append(nombre)
        return nombre

    def eliminar(self, nombre: str) -> None:
        if nombre not in self.creadas or not PATRON_DE_BASE.match(nombre):
            raise AssertionError(f"Se rechaza eliminar una base no creada aquí: {nombre}")
        with self.engine.connect() as conexion:
            conexion.execute(
                text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :nombre AND pid <> pg_backend_pid()"
                ),
                {"nombre": nombre},
            )
            conexion.execute(text(f"DROP DATABASE {self._citar(nombre)}"))
        self.creadas.remove(nombre)


@dataclass
class BaseTemporal:
    nombre: str
    url: str
    engine: Engine

    def escalar(self, sql: str, **parametros: Any) -> Any:
        with self.engine.connect() as conexion:
            return conexion.execute(text(sql), parametros).scalar()

    def filas(self, sql: str, **parametros: Any) -> list:
        with self.engine.connect() as conexion:
            return list(conexion.execute(text(sql), parametros))

    def escribir(self, sql: str, **parametros: Any) -> list:
        with self.engine.begin() as conexion:
            resultado = conexion.execute(text(sql), parametros)
            return list(resultado) if resultado.returns_rows else []


def migrar(url: str, destino: str) -> None:
    with pytest.MonkeyPatch.context() as parche:
        # alembic/env.py resuelve la URL desde settings, no desde el Config.
        parche.setattr(settings, "database_url", url)
        command.upgrade(construir_config_alembic(), destino)


def revertir(url: str, destino: str) -> None:
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(settings, "database_url", url)
        command.downgrade(construir_config_alembic(), destino)


def diferencias_de_alembic(url: str) -> str | None:
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(settings, "database_url", url)
        try:
            command.check(construir_config_alembic())
        except AutogenerateDiffsDetected as error:
            return str(error)
    return None


def revisiones() -> tuple[str, str]:
    """El head actual y la revisión sobre la que se apoya."""
    script = ScriptDirectory.from_config(construir_config_alembic())
    head = script.get_current_head()
    return head, script.get_revision(head).down_revision


def conteos_analiticos(base: BaseTemporal) -> dict[str, int]:
    return {
        tabla.name: base.escalar(f"SELECT count(*) FROM {A}.{tabla.name}")
        for tabla in TABLAS_ANALITICAS
    }


def huella(base: BaseTemporal) -> dict[str, str]:
    """Contenido completo de cada tabla analítica, resumido en un hash."""
    return {
        tabla.name: base.escalar(
            "SELECT md5(coalesce(string_agg(t::text, '|' ORDER BY t::text), '')) "
            f"FROM {A}.{tabla.name} t"
        )
        for tabla in TABLAS_ANALITICAS
    }


def candados_del_etl(base: BaseTemporal) -> int:
    return base.escalar(
        "SELECT count(*) FROM pg_locks WHERE locktype = 'advisory' "
        "AND classid = 0 AND objid = :clave AND objsubid = 1",
        clave=CLAVE_DEL_CANDADO,
    )


def el_candado_esta_libre(base: BaseTemporal) -> bool:
    """Otra transacción puede tomarlo ahora mismo (y lo suelta al terminar)."""
    with base.engine.connect() as conexion:
        with conexion.begin():
            return bool(
                conexion.execute(
                    select(func.pg_try_advisory_xact_lock(CLAVE_DEL_CANDADO))
                ).scalar_one()
            )


@contextmanager
def otra_ejecucion_con_el_candado(base: BaseTemporal, *, confirmar: bool):
    """Una transacción ajena que toma el candado igual que el ETL y lo retiene."""
    conexion = base.engine.connect()
    transaccion = conexion.begin()
    try:
        assert conexion.execute(
            select(func.pg_try_advisory_xact_lock(CLAVE_DEL_CANDADO))
        ).scalar_one()
        yield
    finally:
        (transaccion.commit if confirmar else transaccion.rollback)()
        conexion.close()


def lectura_ok_de_signos(base: BaseTemporal) -> tuple[int, Decimal]:
    """Una lectura HR/SpO2 cuyo estado seguiría OK con un latido más."""
    return tuple(
        base.filas(
            f"SELECT id_lectura, hr_valor FROM {O}.lectura_biometrica "
            "WHERE hr_valor BETWEEN 60 AND 97 AND spo2_valor >= 95 "
            "ORDER BY id_lectura LIMIT 1"
        )[0]
    )


def lectura_de_movimiento(base: BaseTemporal) -> tuple[int, int]:
    """Una lectura de movimiento fetal y la fila gestacional que trae de origen."""
    return tuple(
        base.filas(
            f"SELECT id_lectura, id_tiempo_gest FROM {O}.lectura_biometrica "
            "WHERE mov_valor IS NOT NULL ORDER BY id_lectura LIMIT 1"
        )[0]
    )


def semana_del_embarazo_de_prueba(dia: date) -> int:
    """id_tiempo_gest de la semana en que cae ``dia`` para el embarazo de prueba."""
    return 99 + (dia - INICIO_DEL_EMBARAZO_DE_PRUEBA).days // 7 + 1


def nueva_sesion(
    base: BaseTemporal,
    inicio: str,
    fin: str | None,
    *,
    estado: str = "COMPLETADA",
    id_embarazo: int = EMBARAZO_DE_PRUEBA,
    id_dispositivo: int = DISPOSITIVO_DE_PRUEBA,
) -> int:
    [(id_sesion,)] = base.escribir(
        f"INSERT INTO {O}.sesion_monitoreo "
        "(id_embarazo, id_dispositivo, tipo_sesion, fecha_inicio, fecha_fin, estado_sesion) "
        "VALUES (:embarazo, :dispositivo, 'SIGNOS_MATERNOS', :inicio, :fin, :estado) "
        "RETURNING id_sesion",
        embarazo=id_embarazo, dispositivo=id_dispositivo, inicio=inicio, fin=fin,
        estado=estado,
    )
    return id_sesion


def nueva_lectura(
    base: BaseTemporal,
    sesion: int,
    captura: str,
    *,
    semana: int,
    hr: str = "80",
    spo2: str = "97",
    semaforo: int = ID_OK,
) -> int:
    [(id_lectura,)] = base.escribir(
        f"INSERT INTO {O}.lectura_biometrica "
        "(id_sesion, id_tiempo_gest, id_semaforo, fecha_hora_captura, hr_valor, spo2_valor) "
        "VALUES (:sesion, :semana, :semaforo, :captura, :hr, :spo2) RETURNING id_lectura",
        sesion=sesion, semana=semana, semaforo=semaforo, captura=captura,
        hr=Decimal(hr), spo2=Decimal(spo2),
    )
    return id_lectura


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def servidor():
    url = os.environ[VARIABLE_DE_ENTORNO]
    try:
        verificar_url(url)
    except MotorNoSoportado as error:
        pytest.fail(f"{VARIABLE_DE_ENTORNO}: {error}")
    servidor = ServidorDePruebas(url)
    try:
        yield servidor
    finally:
        for nombre in reversed(list(servidor.creadas)):
            servidor.eliminar(nombre)
        servidor.engine.dispose()


@pytest.fixture(scope="session")
def dataset_canonico(tmp_path_factory):
    generador = cargar_generador()
    carpeta = tmp_path_factory.mktemp("dataset_scrum69")
    with pytest.MonkeyPatch.context() as parche:
        parche.setattr(generador, "CARPETA_SALIDA", carpeta)
        generador.main()
    return validar_dataset(
        json.loads((carpeta / "dataset_fetalalert.json").read_text(encoding="utf-8"))
    )


@pytest.fixture(scope="session")
def plantilla(servidor, dataset_canonico) -> str:
    """Base migrada a head con el dataset canónico, y sin ninguna ejecución del ETL."""
    nombre = servidor.crear("plantilla")
    url = servidor.url_de(nombre)
    migrar(url, "head")
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conexion:
            revision = preflight(conexion)
        with engine.begin() as conexion:
            cargar_dataset(conexion, dataset_canonico, revision=revision)
    finally:
        engine.dispose()
    return nombre


@contextmanager
def base_nueva(servidor, *, plantilla: str | None = None):
    nombre = servidor.crear(f"c{next(CONTADOR)}", plantilla=plantilla)
    url = servidor.url_de(nombre)
    base = BaseTemporal(nombre, url, create_engine(url, poolclass=NullPool))
    try:
        yield base
    finally:
        base.engine.dispose()
        servidor.eliminar(nombre)


@pytest.fixture
def clon(servidor, plantilla):
    """Copia de la plantilla: el dataset cargado y el esquema analítico vacío."""
    with base_nueva(servidor, plantilla=plantilla) as base:
        yield base


@pytest.fixture
def base_vacia(servidor):
    with base_nueva(servidor) as base:
        yield base


@pytest.fixture(scope="module")
def base_cargada(servidor, plantilla):
    """Una copia con una primera ejecución del ETL, para pruebas de solo lectura."""
    with base_nueva(servidor, plantilla=plantilla) as base:
        yield base, ejecutar_etl(base.engine)


@contextmanager
def api_sobre(base: BaseTemporal):
    """El endpoint real, con su sesión atada a la base temporal."""

    def sesion_temporal():
        sesion = Session(bind=base.engine, autoflush=False)
        try:
            yield sesion
        finally:
            sesion.close()

    app.dependency_overrides[get_db] = sesion_temporal
    try:
        with TestClient(app) as cliente:
            yield cliente
    finally:
        app.dependency_overrides.pop(get_db, None)


# ---------------------------------------------------------------------------
# 1. Migración
# ---------------------------------------------------------------------------


def test_upgrade_desde_base_vacia_despliega_ambos_esquemas(base_vacia):
    head, _ = revisiones()
    migrar(base_vacia.url, "head")
    inspector = inspect(base_vacia.engine)

    assert {O, A} <= set(inspector.get_schema_names())
    assert set(inspector.get_table_names(schema=O)) == TABLAS_ESPERADAS
    assert set(inspector.get_table_names(schema=A)) == {t.name for t in TABLAS_ANALITICAS}
    assert base_vacia.escalar("SELECT version_num FROM alembic_version") == head
    assert diferencias_de_alembic(base_vacia.url) is None


def test_el_esquema_operacional_se_despliega_con_los_nombres_de_siempre(base_vacia):
    """The analytic registry must not change how the operational schema is built.

    Alembic names the CHECK constraints that back the enums of the first
    revision through the naming convention of ``target_metadata``. A regression
    in ``env.py`` would create them under their bare names on a fresh database,
    and only a deployment from scratch shows it.
    """
    migrar(base_vacia.url, "head")
    inspector = inspect(base_vacia.engine)

    desplegados = {
        (tabla, check["name"])
        for tabla in TABLAS_ESPERADAS
        for check in inspector.get_check_constraints(tabla, schema=O)
    }
    declarados = {
        (tabla.name, restriccion.name)
        for tabla in Base.metadata.tables.values()
        for restriccion in tabla.constraints
        if isinstance(restriccion, CheckConstraint)
    }

    assert desplegados == declarados


def test_la_estructura_desplegada_es_la_de_la_metadata(base_vacia):
    migrar(base_vacia.url, "head")
    inspector = inspect(base_vacia.engine)

    for tabla in TABLAS_ANALITICAS:
        nombre = tabla.name
        pk = inspector.get_pk_constraint(nombre, schema=A)
        assert tuple(pk["constrained_columns"]) == tuple(c.name for c in tabla.primary_key)
        assert pk["name"] == tabla.primary_key.name

        reflejadas = {
            (fk["name"], tuple(fk["constrained_columns"]), fk["referred_schema"],
             fk["referred_table"], tuple(fk["referred_columns"]),
             fk["options"].get("ondelete"))
            for fk in inspector.get_foreign_keys(nombre, schema=A)
        }
        declaradas = {
            (fk.name, tuple(fk.column_keys), A, fk.referred_table.name,
             tuple(e.column.name for e in fk.elements), fk.ondelete)
            for fk in tabla.foreign_key_constraints
        }
        assert reflejadas == declaradas

        assert {u["name"] for u in inspector.get_unique_constraints(nombre, schema=A)} == {
            c.name for c in tabla.constraints if c.__class__.__name__ == "UniqueConstraint"
        }
        assert {c["name"] for c in inspector.get_check_constraints(nombre, schema=A)} == {
            c.name for c in tabla.constraints if c.__class__.__name__ == "CheckConstraint"
        }
        assert {
            i["name"] for i in inspector.get_indexes(nombre, schema=A)
            if not i.get("duplicates_constraint")
        } == {i.name for i in tabla.indexes}

        columnas = {c["name"]: c for c in inspector.get_columns(nombre, schema=A)}
        for columna in tabla.columns:
            assert columnas[columna.name]["nullable"] == columna.nullable


def test_ningun_nombre_supera_63_caracteres_ni_quedo_truncado(base_vacia):
    migrar(base_vacia.url, "head")
    en_el_servidor = {
        fila[0]
        for fila in base_vacia.filas(
            "SELECT c.conname FROM pg_constraint c JOIN pg_class r ON r.oid = c.conrelid "
            "JOIN pg_namespace n ON n.oid = r.relnamespace WHERE n.nspname = :esquema "
            "UNION SELECT indexname FROM pg_indexes WHERE schemaname = :esquema",
            esquema=A,
        )
    }
    declarados = {
        str(c.name) for tabla in TABLAS_ANALITICAS for c in tabla.constraints
    } | {str(i.name) for tabla in TABLAS_ANALITICAS for i in tabla.indexes}

    # Iguales: si PostgreSQL hubiera recortado alguno, no coincidiría.
    assert en_el_servidor == declarados
    assert max(len(nombre) for nombre in en_el_servidor) <= PG_MAX_IDENTIFIER_LENGTH


def test_ninguna_llave_foranea_cruza_de_un_esquema_a_otro(base_vacia):
    migrar(base_vacia.url, "head")

    assert base_vacia.escalar(
        "SELECT count(*) FROM pg_constraint c "
        "JOIN pg_class r ON r.oid = c.conrelid JOIN pg_namespace n ON n.oid = r.relnamespace "
        "JOIN pg_class fr ON fr.oid = c.confrelid "
        "JOIN pg_namespace fn ON fn.oid = fr.relnamespace "
        "WHERE c.contype = 'f' AND n.nspname <> fn.nspname"
    ) == 0


def test_downgrade_al_head_previo_conserva_los_datos_y_vuelve_a_subir(clon):
    head, previa = revisiones()
    ejecutar_etl(clon.engine)

    revertir(clon.url, previa)
    assert A not in inspect(clon.engine).get_schema_names()
    assert clon.escalar("SELECT version_num FROM alembic_version") == previa
    assert clon.escalar(f"SELECT count(*) FROM {O}.lectura_biometrica") == LECTURAS
    assert clon.escalar(f"SELECT count(*) FROM {O}.sesion_monitoreo") == SESIONES

    migrar(clon.url, "head")
    assert clon.escalar("SELECT version_num FROM alembic_version") == head
    assert set(conteos_analiticos(clon).values()) == {0}
    assert diferencias_de_alembic(clon.url) is None

    # Y el ETL vuelve a cargar todo sobre el esquema recién recreado.
    assert ejecutar_etl(clon.engine).hechos_nuevos == LECTURAS


def test_downgrade_a_base_elimina_ambos_esquemas(base_vacia):
    migrar(base_vacia.url, "head")
    revertir(base_vacia.url, "base")
    esquemas = set(inspect(base_vacia.engine).get_schema_names())

    assert A not in esquemas
    assert O not in esquemas
    assert "public" in esquemas


# ---------------------------------------------------------------------------
# 2. Carga inicial canónica
# ---------------------------------------------------------------------------


def test_el_cargador_no_toca_el_esquema_analitico(clon):
    assert set(conteos_analiticos(clon).values()) == {0}


def test_la_primera_carga_informa_lo_que_hizo(base_cargada):
    _, resultado = base_cargada

    assert resultado.hechos_nuevos == LECTURAS
    assert resultado.hechos_existentes == 0
    assert {r.tabla: r.insertadas for r in resultado.dimensiones} == {
        nombre: cantidad for nombre, cantidad in DIMENSIONES.items()
        if nombre != "bridge_embarazo_factor_riesgo"
    }
    assert resultado.bridge.insertadas == DIMENSIONES["bridge_embarazo_factor_riesgo"]
    assert resultado.informe.correcta


def test_conteos_canonicos_medidos_con_sql_independiente(base_cargada):
    base, _ = base_cargada

    assert base.escalar(f"SELECT count(*) FROM {A}.fact_lectura_biometrica") == LECTURAS
    assert base.escalar(f"SELECT count(*) FROM {O}.sesion_monitoreo") == SESIONES
    assert base.escalar(
        f"SELECT count(*) FROM {O}.sesion_monitoreo s WHERE EXISTS "
        f"(SELECT 1 FROM {O}.lectura_biometrica l WHERE l.id_sesion = s.id_sesion)"
    ) == SESIONES
    assert base.escalar(f"SELECT count(DISTINCT id_sesion) FROM {O}.lectura_biometrica") == SESIONES
    assert base.escalar(f"SELECT count(DISTINCT id_sesion) FROM {A}.fact_lectura_biometrica") == SESIONES
    assert base.escalar(
        f"SELECT count(*) FROM (SELECT DISTINCT id_sesion FROM {O}.lectura_biometrica "
        f"EXCEPT SELECT DISTINCT id_sesion FROM {A}.fact_lectura_biometrica) x"
    ) == 0
    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE hr_valor IS NOT NULL"
    ) == LECTURAS_HR
    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE mov_valor IS NOT NULL"
    ) == LECTURAS_MOVIMIENTO
    assert dict(base.filas(
        f"SELECT s.codigo_nivel, count(*) FROM {A}.fact_lectura_biometrica f "
        f"JOIN {A}.dim_semaforo s USING (id_semaforo) GROUP BY 1"
    )) == SEMAFORO
    for metrica, esperado in ESTADOS_POR_METRICA.items():
        assert dict(base.filas(
            f"SELECT {metrica}, count(*) FROM {A}.fact_lectura_biometrica "
            f"WHERE {metrica} IS NOT NULL GROUP BY 1"
        )) == esperado
    assert conteos_analiticos(base) == {**DIMENSIONES, "fact_lectura_biometrica": LECTURAS}
    assert dict(Counter(
        cantidad for (cantidad,) in base.filas(
            f"SELECT count(b.id_factor_riesgo) FROM {A}.dim_embarazo e "
            f"LEFT JOIN {A}.bridge_embarazo_factor_riesgo b USING (id_embarazo) GROUP BY e.id_embarazo"
        )
    )) == FACTORES_POR_EMBARAZO
    assert base.escalar(
        f"SELECT count(*) FROM {A}.dim_embarazo WHERE duracion_est_semanas <> 40"
    ) == 0
    assert dict(base.filas(
        f"SELECT id_clinica, count(*) FROM {A}.fact_lectura_biometrica GROUP BY 1"
    )) == dict(base.filas(
        f"SELECT e.id_clinica, count(*) FROM {O}.lectura_biometrica l "
        f"JOIN {O}.sesion_monitoreo s USING (id_sesion) "
        f"JOIN {O}.embarazo e ON e.id_embarazo = s.id_embarazo GROUP BY 1"
    ))


def test_la_conciliacion_completa_no_encuentra_diferencias(base_cargada):
    _, resultado = base_cargada
    informe = resultado.informe

    assert informe.fallidas == ()
    for nombre in (
        "semaforo_distinto_del_origen",
        "semaforo_distinto_de_la_mayor_severidad",
        "huerfanos_del_hecho",
        "huerfanos_de_dimensiones",
        "forma_invalida",
        "claves_duplicadas",
        "contenido_divergente",
        "movimiento_antes_de_semana_20",
        "fecha_fuera_del_embarazo",
        "medico_no_resoluble",
        "medico_distinto_del_responsable",
        "afiliacion_no_aplicable",
    ):
        assert informe.discrepancias(nombre) == 0, nombre
    assert informe.discrepancias("semana_recalculada_distinta") == 0
    assert informe.conteos["sesiones_con_lecturas_origen"] == SESIONES
    assert informe.conteos["sesiones_en_hecho"] == SESIONES


def test_clasificacion_embarazo_pendiente_se_reporta_sin_ser_error(base_cargada):
    base, resultado = base_cargada
    [pendiente] = [
        v for v in resultado.informe.verificaciones
        if v.nombre == "clasificacion_embarazo_pendiente"
    ]

    assert pendiente.discrepancias == DIMENSIONES["dim_embarazo"]
    assert not pendiente.bloqueante
    assert pendiente.correcta
    assert base.escalar(
        f"SELECT count(*) FROM {A}.dim_embarazo WHERE clasificacion_embarazo IS NOT NULL"
    ) == 0


def test_clasificacion_embarazo_pendiente_se_cuenta_en_cada_ejecucion(clon):
    """El informe cuenta filas al vuelo: un embarazo más mueve el número."""
    primera = ejecutar_etl(clon.engine)
    assert primera.informe.discrepancias(
        "clasificacion_embarazo_pendiente"
    ) == DIMENSIONES["dim_embarazo"]

    [(paciente,)] = clon.escribir(
        f"INSERT INTO {O}.paciente (cedula, primer_nombre, apellido_paterno, email_pac, fecha_nac) "
        "VALUES ('0-000-6902', 'Paciente', 'Pendiente', 'pendiente.clasif@ejemplo.test', "
        "'1995-05-05') RETURNING id_paciente"
    )
    clon.escribir(
        f"INSERT INTO {O}.embarazo (id_paciente, id_clinica, numero_gestas, numero_partos, "
        "fecha_inicio, fecha_probable_parto, estado_embarazo) "
        "VALUES (:paciente, 100, 1, 0, '2025-01-06', '2025-10-13', 'ACTIVO')",
        paciente=paciente,
    )

    segunda = ejecutar_etl(clon.engine)

    assert segunda.informe.discrepancias(
        "clasificacion_embarazo_pendiente"
    ) == DIMENSIONES["dim_embarazo"] + 1
    assert clon.escalar(
        f"SELECT count(*) FROM {A}.dim_embarazo WHERE clasificacion_embarazo IS NOT NULL"
    ) == 0


def test_null_por_metrica_y_cero_como_valor_real(base_cargada):
    base, _ = base_cargada

    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE hr_valor IS NOT NULL "
        "AND (mov_valor IS NOT NULL OR estado_mov IS NOT NULL "
        "OR estado_hr IS NULL OR estado_spo2 IS NULL)"
    ) == 0
    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE mov_valor IS NOT NULL "
        "AND (hr_valor IS NOT NULL OR spo2_valor IS NOT NULL OR estado_hr IS NOT NULL "
        "OR estado_spo2 IS NOT NULL OR estado_mov IS NULL)"
    ) == 0
    ceros_en_origen = base.escalar(
        f"SELECT count(*) FROM {O}.lectura_biometrica WHERE mov_valor = 0"
    )
    assert ceros_en_origen > 0
    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica "
        "WHERE mov_valor = 0 AND estado_mov = 'ERROR'"
    ) == ceros_en_origen


def test_cada_hecho_se_rastrea_hasta_su_origen(base_cargada):
    base, _ = base_cargada

    assert base.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica f "
        f"JOIN {O}.lectura_biometrica l ON l.id_lectura = f.id_lectura "
        f"JOIN {O}.sesion_monitoreo s ON s.id_sesion = f.id_sesion AND s.id_sesion = l.id_sesion "
        f"JOIN {O}.embarazo e ON e.id_embarazo = s.id_embarazo "
        "AND e.id_embarazo = f.id_embarazo AND e.id_paciente = f.id_paciente "
        "AND e.id_clinica = f.id_clinica "
        f"JOIN {O}.seguimiento_clinico sc ON sc.id_embarazo = e.id_embarazo "
        "AND sc.id_medico = f.id_medico AND sc.rol_seguimiento = 'PRINCIPAL' "
        f"JOIN {O}.medico_clinica mc ON mc.id_medico = f.id_medico "
        "AND mc.id_clinica = f.id_clinica"
    ) == LECTURAS
    assert base.escalar(
        f"SELECT count(*) FROM (SELECT id_embarazo, id_factor_riesgo "
        f"FROM {O}.embarazo_factor_riesgo EXCEPT SELECT id_embarazo, id_factor_riesgo "
        f"FROM {A}.bridge_embarazo_factor_riesgo) x"
    ) == 0


def test_el_esquema_operacional_queda_intacto(base_cargada):
    base, _ = base_cargada
    from app.loader import ORDEN_DE_CARGA

    filas = sum(base.escalar(f"SELECT count(*) FROM {O}.{tabla}") for tabla in ORDEN_DE_CARGA)
    assert filas == FILAS_ESPERADAS
    assert base.escalar(f"SELECT count(*) FROM {O}.idempotencia_solicitud") == 0
    assert base.escalar(f"SELECT count(*) FROM {O}.auditoria_log") == 0


def test_el_modelo_estrella_no_copia_la_traza_del_edge(base_cargada):
    base, _ = base_cargada
    columnas = {
        columna["name"]
        for tabla in TABLAS_ANALITICAS
        for columna in inspect(base.engine).get_columns(tabla.name, schema=A)
    }

    for prohibida in ("clave", "clave_idempotencia", "correlation_id", "id_outbox",
                      "intentos", "fecha_hora_sincronizacion", "huella"):
        assert prohibida not in columnas


def test_conciliar_sin_escribir_sobre_la_base_cargada(base_cargada):
    base, _ = base_cargada
    antes = huella(base)

    informe = conciliar_sin_escribir(base.engine)

    assert informe.correcta
    assert huella(base) == antes


# ---------------------------------------------------------------------------
# 3. Candado transaccional
# ---------------------------------------------------------------------------


def test_el_candado_es_la_primera_sentencia_de_la_transaccion_repeatable_read(
    clon, monkeypatch
):
    with clon.engine.connect():
        pass  # la inicialización del dialecto ocurre aquí, antes de observar
    sentencias: list[str] = []
    aislamiento: list[str] = []

    def anotar(conn, cursor, statement, parameters, context, executemany):
        sentencias.append(statement)

    original = extraccion.extraer_dimensiones

    def extraer_observando(conexion):
        aislamiento.append(conexion.execute(text("SHOW transaction_isolation")).scalar())
        return original(conexion)

    monkeypatch.setattr(extraccion, "extraer_dimensiones", extraer_observando)
    event.listen(clon.engine, "before_cursor_execute", anotar)
    try:
        ejecutar_etl(clon.engine)
    finally:
        event.remove(clon.engine, "before_cursor_execute", anotar)

    assert "pg_try_advisory_xact_lock" in sentencias[0]
    assert aislamiento == ["repeatable read"]
    assert not any("pg_advisory_unlock" in s or "pg_try_advisory_lock(" in s for s in sentencias)
    assert candados_del_etl(clon) == 0


@pytest.mark.parametrize("confirmar", [True, False], ids=["tras-commit", "tras-rollback"])
def test_una_segunda_ejecucion_se_rechaza_de_inmediato_y_otra_posterior_adquiere(
    clon, confirmar
):
    ejecutar_etl(clon.engine)
    antes = huella(clon)

    with otra_ejecucion_con_el_candado(clon, confirmar=confirmar):
        inicio = time.perf_counter()
        with pytest.raises(CandadoOcupado):
            ejecutar_etl(clon.engine)
        # No espera: pg_try_advisory_xact_lock responde en el acto.
        assert time.perf_counter() - inicio < 5
        assert huella(clon) == antes

    # La transacción ajena terminó y PostgreSQL soltó el candado por sí solo.
    assert candados_del_etl(clon) == 0
    assert el_candado_esta_libre(clon)
    assert ejecutar_etl(clon.engine).hechos_nuevos == 0
    assert huella(clon) == antes


def test_el_candado_se_libera_solo_tras_un_commit_del_etl(clon):
    ejecutar_etl(clon.engine)

    assert candados_del_etl(clon) == 0
    assert el_candado_esta_libre(clon)
    assert ejecutar_etl(clon.engine).hechos_existentes == LECTURAS


def test_el_candado_se_libera_solo_tras_una_excepcion_y_la_siguiente_ejecucion_adquiere(clon):
    id_lectura, _ = lectura_ok_de_signos(clon)
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_semaforo = :warning WHERE id_lectura = :id",
        warning=ID_WARNING, id=id_lectura,
    )

    with pytest.raises(DiscrepanciaDeSemaforo):
        ejecutar_etl(clon.engine)

    assert candados_del_etl(clon) == 0
    assert el_candado_esta_libre(clon)

    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_semaforo = :ok WHERE id_lectura = :id",
        ok=ID_OK, id=id_lectura,
    )
    assert ejecutar_etl(clon.engine).hechos_nuevos == LECTURAS


# ---------------------------------------------------------------------------
# 4. Idempotencia, incrementalidad e inserción del hecho
# ---------------------------------------------------------------------------


def test_la_segunda_ejecucion_no_cambia_nada(clon):
    ejecutar_etl(clon.engine)
    antes = huella(clon)

    segunda = ejecutar_etl(clon.engine)

    assert segunda.hechos_nuevos == 0
    assert segunda.hechos_existentes == LECTURAS
    assert all(r.insertadas == 0 and r.actualizadas == 0 for r in segunda.dimensiones)
    assert (segunda.bridge.insertadas, segunda.bridge.actualizadas) == (0, 0)
    assert huella(clon) == antes


def test_incremento_por_el_endpoint_y_replay_con_la_misma_clave(clon):
    ejecutar_etl(clon.engine)
    clave = str(uuid.uuid4())

    with api_sobre(clon) as cliente:
        primera = cliente.post(RUTA, json=PAQUETE_INCREMENTO, headers={CABECERA_IDEMPOTENCIA: clave})
    assert primera.status_code == 201
    assert primera.headers[CABECERA_REPLAY] == "false"
    id_sesion, ids_lectura = primera.json()["id_sesion"], primera.json()["ids_lectura"]

    incremental = ejecutar_etl(clon.engine)
    assert incremental.hechos_nuevos == 3
    assert incremental.hechos_existentes == LECTURAS
    assert incremental.informe.conteos["sesiones_en_hecho"] == SESIONES + 1
    assert incremental.informe.semaforo["OK"] == SEMAFORO["OK"] + 3
    assert sorted(
        fila[0] for fila in clon.filas(
            f"SELECT id_lectura FROM {A}.fact_lectura_biometrica WHERE id_sesion = :sesion",
            sesion=id_sesion,
        )
    ) == sorted(ids_lectura)
    # Trazabilidad hasta la clave: vive en operacional, no se copia al hecho.
    assert clon.escalar(
        f"SELECT clave FROM {O}.idempotencia_solicitud WHERE id_sesion = :sesion",
        sesion=id_sesion,
    ) == clave

    with api_sobre(clon) as cliente:
        repetida = cliente.post(RUTA, json=PAQUETE_INCREMENTO, headers={CABECERA_IDEMPOTENCIA: clave})
    assert repetida.status_code == 201
    assert repetida.headers[CABECERA_REPLAY] == "true"
    assert repetida.json()["id_sesion"] == id_sesion
    assert repetida.json()["ids_lectura"] == ids_lectura

    tras_replay = ejecutar_etl(clon.engine)
    assert tras_replay.hechos_nuevos == 0
    assert tras_replay.informe.conteos["hechos"] == LECTURAS + 3


def test_llegada_tardia_con_fecha_clinica_antigua_se_carga(clon):
    ejecutar_etl(clon.engine)
    mas_reciente = clon.escalar(f"SELECT max(fecha_hora) FROM {A}.fact_lectura_biometrica")
    sesion = nueva_sesion(clon, "2025-02-25T15:00:00+00:00", "2025-02-25T15:05:00+00:00")
    id_lectura = nueva_lectura(
        clon, sesion, "2025-02-25T15:01:00+00:00", semana=SEMANA_8
    )
    captura = clon.escalar(
        f"SELECT fecha_hora_captura FROM {O}.lectura_biometrica WHERE id_lectura = :id",
        id=id_lectura,
    )
    # Una marca de agua por fecha clínica la perdería.
    assert captura < mas_reciente

    resultado = ejecutar_etl(clon.engine)

    assert resultado.hechos_nuevos == 1
    assert clon.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE id_lectura = :id",
        id=id_lectura,
    ) == 1


def test_un_id_menor_que_el_maximo_y_uno_con_hueco_se_cargan(clon):
    ejecutar_etl(clon.engine)
    maximo = clon.escalar(f"SELECT max(id_lectura) FROM {A}.fact_lectura_biometrica")
    sesion = nueva_sesion(clon, "2025-02-26T15:00:00+00:00", "2025-02-26T15:05:00+00:00")
    clon.escribir(
        f"INSERT INTO {O}.lectura_biometrica "
        "(id_lectura, id_sesion, id_tiempo_gest, id_semaforo, fecha_hora_captura, "
        "hr_valor, spo2_valor) VALUES "
        "(99, :sesion, :semana, :ok, '2025-02-26T15:01:00+00:00', 80, 97), "
        "(:hueco, :sesion, :semana, :ok, '2025-02-26T15:02:00+00:00', 81, 97)",
        sesion=sesion, semana=SEMANA_8, ok=ID_OK, hueco=maximo + 20,
    )
    # MAX(id) como marca de agua nunca volvería a ver el 99.
    assert 99 < maximo

    resultado = ejecutar_etl(clon.engine)

    assert resultado.hechos_nuevos == 2
    assert {
        fila[0] for fila in clon.filas(
            f"SELECT id_lectura FROM {A}.fact_lectura_biometrica "
            "WHERE id_lectura IN (99, :hueco)", hueco=maximo + 20,
        )
    } == {99, maximo + 20}


def test_una_colision_en_el_hecho_revierte_en_lugar_de_saltarse_la_fila(clon, monkeypatch):
    """A plain INSERT: a candidate whose key already exists is an anomaly.

    The race is simulated: between the anti-join and the INSERT, a row with the
    candidate's key appears in the fact. ``ON CONFLICT DO NOTHING`` would skip
    it and report success; the plain INSERT fails and the whole run -- the
    intruding row included -- is rolled back.
    """
    ejecutar_etl(clon.engine)
    antes = huella(clon)
    sesion = nueva_sesion(clon, "2025-02-27T15:00:00+00:00", "2025-02-27T15:05:00+00:00")
    candidata = nueva_lectura(clon, sesion, "2025-02-27T15:01:00+00:00", semana=SEMANA_8)

    original = extraccion.extraer_lecturas_nuevas

    def carrera(conexion):
        filas = original(conexion)
        conexion.execute(
            text(
                f"INSERT INTO {A}.fact_lectura_biometrica SELECT :id, id_sesion, "
                "id_paciente, id_medico, id_clinica, id_tiempo_gestacional, id_embarazo, "
                "id_semaforo, hr_valor, spo2_valor, mov_valor, estado_hr, estado_spo2, "
                f"estado_mov, fecha_hora FROM {A}.fact_lectura_biometrica "
                "WHERE hr_valor IS NOT NULL ORDER BY id_lectura LIMIT 1"
            ),
            {"id": candidata},
        )
        return filas

    monkeypatch.setattr(extraccion, "extraer_lecturas_nuevas", carrera)

    with pytest.raises(CargaInconsistente, match="SQLSTATE 23505"):
        ejecutar_etl(clon.engine)

    assert huella(clon) == antes
    assert conteos_analiticos(clon)["fact_lectura_biometrica"] == LECTURAS


def test_se_cargan_lecturas_de_sesiones_en_cualquier_estado(clon):
    ejecutar_etl(clon.engine)
    ids = {}
    for dia, estado, cierra in (
        (3, "PENDIENTE", False),
        (4, "COMPLETADA", True),
        (5, "INTERRUMPIDA", False),
        (6, "PROCESADA", True),
    ):
        fecha = date(2025, 3, dia)
        inicio = f"{fecha.isoformat()}T15:00:00+00:00"
        sesion = nueva_sesion(
            clon, inicio, f"{fecha.isoformat()}T15:05:00+00:00" if cierra else None,
            estado=estado,
        )
        ids[estado] = nueva_lectura(
            clon, sesion, f"{fecha.isoformat()}T15:01:00+00:00",
            semana=semana_del_embarazo_de_prueba(fecha),
        )

    resultado = ejecutar_etl(clon.engine)

    assert resultado.hechos_nuevos == 4
    assert {
        estado for (estado,) in clon.filas(
            f"SELECT s.estado_sesion FROM {A}.fact_lectura_biometrica f "
            f"JOIN {O}.sesion_monitoreo s ON s.id_sesion = f.id_sesion "
            "WHERE f.id_lectura = ANY(:ids)", ids=list(ids.values()),
        )
    } == set(ids)


def test_hr_y_spo2_se_clasifican_con_decimal_exacto(clon):
    ejecutar_etl(clon.engine)
    sesion = nueva_sesion(clon, "2025-03-10T15:00:00+00:00", "2025-03-10T15:05:00+00:00")
    semana = semana_del_embarazo_de_prueba(date(2025, 3, 10))
    frontera = nueva_lectura(
        clon, sesion, "2025-03-10T15:01:00+00:00", semana=semana,
        hr="99.99", spo2="94.99", semaforo=ID_WARNING,
    )
    cien = nueva_lectura(
        clon, sesion, "2025-03-10T15:02:00+00:00", semana=semana,
        hr="100.00", spo2="95.00", semaforo=ID_WARNING,
    )
    with clon.engine.connect() as conexion:
        candidatas = extraccion.extraer_lecturas_nuevas(conexion)
    assert all(isinstance(f["hr_valor"], Decimal) for f in candidatas)
    assert all(isinstance(f["spo2_valor"], Decimal) for f in candidatas)

    ejecutar_etl(clon.engine)

    hechos = {
        fila[0]: fila[1:]
        for fila in clon.filas(
            f"SELECT id_lectura, hr_valor, spo2_valor, estado_hr, estado_spo2 "
            f"FROM {A}.fact_lectura_biometrica WHERE id_lectura IN (:a, :b)",
            a=frontera, b=cien,
        )
    }
    assert hechos[frontera] == (Decimal("99.99"), Decimal("94.99"), "OK", "WARNING")
    assert hechos[cien] == (Decimal("100.00"), Decimal("95.00"), "WARNING", "OK")


def test_una_hr_entre_55_y_60_se_carga_y_concilia_como_warning(clon):
    """Bradicardia de tamizaje: WARNING, se carga y la conciliación no protesta."""
    ejecutar_etl(clon.engine)
    fecha = date(2025, 3, 18)
    sesion = nueva_sesion(
        clon, f"{fecha.isoformat()}T15:00:00+00:00", f"{fecha.isoformat()}T15:05:00+00:00"
    )
    id_lectura = nueva_lectura(
        clon, sesion, f"{fecha.isoformat()}T15:01:00+00:00",
        semana=semana_del_embarazo_de_prueba(fecha), hr="57", spo2="97",
        semaforo=ID_WARNING,
    )

    resultado = ejecutar_etl(clon.engine)

    assert resultado.hechos_nuevos == 1
    assert resultado.informe.correcta
    assert clon.filas(
        f"SELECT hr_valor, estado_hr, estado_spo2, id_semaforo "
        f"FROM {A}.fact_lectura_biometrica WHERE id_lectura = :id", id=id_lectura,
    ) == [(Decimal("57.00"), "WARNING", "OK", ID_WARNING)]


def test_una_lectura_modificada_tras_cargarse_hace_fallar_sin_actualizar_el_hecho(clon):
    ejecutar_etl(clon.engine)
    id_lectura, hr_original = lectura_ok_de_signos(clon)
    antes = huella(clon)
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET hr_valor = hr_valor + 1 WHERE id_lectura = :id",
        id=id_lectura,
    )

    with pytest.raises(ConciliacionFallida) as error:
        ejecutar_etl(clon.engine)

    assert error.value.informe.discrepancias("contenido_divergente") == 1
    assert clon.escalar(
        f"SELECT hr_valor FROM {A}.fact_lectura_biometrica WHERE id_lectura = :id",
        id=id_lectura,
    ) == hr_original
    assert huella(clon) == antes


def test_una_lectura_eliminada_tras_cargarse_hace_fallar_sin_borrar_el_hecho(clon):
    ejecutar_etl(clon.engine)
    id_lectura, _ = lectura_ok_de_signos(clon)
    antes = huella(clon)
    clon.escribir(f"DELETE FROM {O}.lectura_biometrica WHERE id_lectura = :id", id=id_lectura)

    with pytest.raises(ConciliacionFallida) as error:
        ejecutar_etl(clon.engine)

    assert error.value.informe.discrepancias("hechos_sin_lectura_origen") == 1
    assert conciliar_sin_escribir(clon.engine).discrepancias("hechos_sin_lectura_origen") == 1
    assert clon.escalar(
        f"SELECT count(*) FROM {A}.fact_lectura_biometrica WHERE id_lectura = :id",
        id=id_lectura,
    ) == 1
    assert huella(clon) == antes


def test_tipo_1_actualiza_la_dimension_sin_tocar_los_hechos(clon):
    ejecutar_etl(clon.engine)
    clon.escribir(
        f"UPDATE {O}.clinica SET nombre_clinica = nombre_clinica || ' (renombrada)' "
        "WHERE id_clinica = 100"
    )

    resultado = ejecutar_etl(clon.engine)

    [clinicas] = [r for r in resultado.dimensiones if r.tabla == "dim_clinica"]
    assert (clinicas.insertadas, clinicas.actualizadas, clinicas.sin_cambios) == (0, 1, 2)
    assert resultado.hechos_nuevos == 0
    assert clon.escalar(
        f"SELECT nombre_clinica FROM {A}.dim_clinica WHERE id_clinica = 100"
    ).endswith(" (renombrada)")


def test_un_fallo_posterior_revierte_tambien_tipo_1_y_bridge(clon):
    ejecutar_etl(clon.engine)
    antes = huella(clon)
    clon.escribir(
        f"UPDATE {O}.clinica SET nombre_clinica = nombre_clinica || ' (renombrada)' "
        "WHERE id_clinica = 100"
    )
    clon.escribir(
        f"UPDATE {O}.embarazo_factor_riesgo SET observaciones = 'Nota simulada' "
        f"WHERE (id_embarazo, id_factor_riesgo) = (SELECT id_embarazo, id_factor_riesgo "
        f"FROM {O}.embarazo_factor_riesgo ORDER BY 1, 2 LIMIT 1)"
    )
    # El fallo llega después de las dimensiones y del bridge: en los hechos.
    # HR 130 es ERROR y el origen la registró como OK: nadie corrige a nadie.
    sesion = nueva_sesion(clon, "2025-03-11T15:00:00+00:00", "2025-03-11T15:05:00+00:00")
    nueva_lectura(
        clon, sesion, "2025-03-11T15:01:00+00:00",
        semana=semana_del_embarazo_de_prueba(date(2025, 3, 11)), hr="130",
    )

    with pytest.raises(DiscrepanciaDeSemaforo):
        ejecutar_etl(clon.engine)

    assert huella(clon) == antes
    assert not clon.escalar(
        f"SELECT nombre_clinica FROM {A}.dim_clinica WHERE id_clinica = 100"
    ).endswith(" (renombrada)")
    assert clon.escalar(
        f"SELECT count(*) FROM {A}.bridge_embarazo_factor_riesgo "
        "WHERE observaciones = 'Nota simulada'"
    ) == 0


def test_una_relacion_que_desaparece_del_origen_no_se_borra_en_silencio(clon):
    ejecutar_etl(clon.engine)
    clon.escribir(
        f"DELETE FROM {O}.embarazo_factor_riesgo "
        f"WHERE (id_embarazo, id_factor_riesgo) = (SELECT id_embarazo, id_factor_riesgo "
        f"FROM {O}.embarazo_factor_riesgo ORDER BY id_embarazo, id_factor_riesgo LIMIT 1)"
    )

    with pytest.raises(ConciliacionFallida) as error:
        ejecutar_etl(clon.engine)

    assert error.value.informe.discrepancias("bridge_distinto_del_origen") == 1
    assert conteos_analiticos(clon)["bridge_embarazo_factor_riesgo"] == 23


# ---------------------------------------------------------------------------
# 5. Reglas que detienen la carga
# ---------------------------------------------------------------------------


def test_una_lectura_imposible_revierte_todo_y_la_reejecucion_corregida_carga(clon):
    """Movimiento fetal fechado antes de la semana 20: el dato no puede existir."""
    id_lectura, semana_original = lectura_de_movimiento(clon)
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_tiempo_gest = :semana WHERE id_lectura = :id",
        semana=SEMANA_19, id=id_lectura,
    )

    with pytest.raises(LecturaInvalida) as error:
        ejecutar_etl(clon.engine)

    assert f"id_lectura={id_lectura}" in error.value.detalle
    # Ni dimensiones ni hechos: la transacción entera se revirtió.
    assert set(conteos_analiticos(clon).values()) == {0}
    assert candados_del_etl(clon) == 0

    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_tiempo_gest = :semana WHERE id_lectura = :id",
        semana=semana_original, id=id_lectura,
    )
    resultado = ejecutar_etl(clon.engine)

    assert resultado.hechos_nuevos == LECTURAS
    assert resultado.informe.correcta


def test_un_semaforo_derivado_distinto_del_origen_revierte_todo(clon):
    id_lectura, _ = lectura_ok_de_signos(clon)
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_semaforo = :warning WHERE id_lectura = :id",
        warning=ID_WARNING, id=id_lectura,
    )

    with pytest.raises(DiscrepanciaDeSemaforo) as error:
        ejecutar_etl(clon.engine)

    assert f"id_lectura=[{id_lectura}]" in error.value.detalle
    assert set(conteos_analiticos(clon).values()) == {0}


def test_una_version_de_semaforo_distinta_de_la_de_las_reglas_revierte_todo(clon):
    clon.escribir(
        f"UPDATE {O}.semaforo SET version_referencia = 'SIM-2.0' WHERE codigo_nivel = 'OK'"
    )

    with pytest.raises(VersionDeReglasDesconocida, match="SIM-2.0"):
        ejecutar_etl(clon.engine)

    assert set(conteos_analiticos(clon).values()) == {0}


def test_un_medico_ambiguo_revierte_todo(clon):
    otro = clon.escalar(
        f"SELECT min(id_medico) FROM {O}.medico WHERE id_medico <> :medico",
        medico=MEDICO_DE_PRUEBA,
    )
    clon.escribir(
        f"INSERT INTO {O}.seguimiento_clinico "
        "(id_embarazo, id_medico, fecha_asignacion, fecha_fin, rol_seguimiento, activo) "
        "VALUES (:embarazo, :medico, '2025-01-06', NULL, 'PRINCIPAL', true)",
        embarazo=EMBARAZO_DE_PRUEBA, medico=otro,
    )

    with pytest.raises(DerivacionAmbigua):
        ejecutar_etl(clon.engine)

    assert set(conteos_analiticos(clon).values()) == {0}


# ---------------------------------------------------------------------------
# 6. Afiliación clínica del médico del hecho
# ---------------------------------------------------------------------------


def test_una_afiliacion_historica_inactiva_que_cubre_el_dia_es_valida(clon):
    """``activo = false`` does not discard an affiliation: its dates decide."""
    clon.escribir(
        f"UPDATE {O}.medico_clinica SET activo = false WHERE id_medico = :medico",
        medico=MEDICO_DE_PRUEBA,
    )

    resultado = ejecutar_etl(clon.engine)

    assert resultado.informe.correcta
    assert resultado.hechos_nuevos == LECTURAS


def test_un_medico_afiliado_a_otra_clinica_ese_dia_revierte_todo(clon):
    otra = clon.escalar(
        f"SELECT min(id_clinica) FROM {O}.clinica WHERE id_clinica <> 100"
    )
    clon.escribir(
        f"UPDATE {O}.medico_clinica SET id_clinica = :otra WHERE id_medico = :medico",
        otra=otra, medico=MEDICO_DE_PRUEBA,
    )

    with pytest.raises(DerivacionImposible, match="no a la del embarazo"):
        ejecutar_etl(clon.engine)

    assert set(conteos_analiticos(clon).values()) == {0}


def test_un_medico_sin_afiliacion_que_cubra_el_dia_revierte_todo(clon):
    clon.escribir(
        f"UPDATE {O}.medico_clinica SET fecha_final = '2025-01-02' WHERE id_medico = :medico",
        medico=MEDICO_DE_PRUEBA,
    )

    with pytest.raises(DerivacionImposible, match="ninguna afiliación"):
        ejecutar_etl(clon.engine)

    assert set(conteos_analiticos(clon).values()) == {0}


def test_un_medico_con_dos_afiliaciones_aplicables_revierte_todo(clon):
    otra = clon.escalar(
        f"SELECT min(id_clinica) FROM {O}.clinica WHERE id_clinica <> 100"
    )
    clon.escribir(
        f"INSERT INTO {O}.medico_clinica (id_medico, id_clinica, fecha_inicio) "
        "VALUES (:medico, :otra, '2025-01-01')",
        medico=MEDICO_DE_PRUEBA, otra=otra,
    )

    with pytest.raises(DerivacionAmbigua):
        ejecutar_etl(clon.engine)

    assert set(conteos_analiticos(clon).values()) == {0}


# ---------------------------------------------------------------------------
# 7. Entidades maestras que todavía no tienen relación
# ---------------------------------------------------------------------------


def test_entidades_maestras_sin_relacion_no_detienen_la_carga(clon):
    [(sin_embarazo,)] = clon.escribir(
        f"INSERT INTO {O}.paciente (cedula, primer_nombre, apellido_paterno, email_pac, fecha_nac) "
        "VALUES ('0-000-6911', 'Paciente', 'Nueva', 'paciente.nueva@ejemplo.test', '1996-06-06') "
        "RETURNING id_paciente"
    )
    [(con_embarazo,)] = clon.escribir(
        f"INSERT INTO {O}.paciente (cedula, primer_nombre, apellido_paterno, email_pac, fecha_nac) "
        "VALUES ('0-000-6912', 'Paciente', 'Registrada', 'paciente.registrada@ejemplo.test', "
        "'1997-07-07') RETURNING id_paciente"
    )
    clon.escribir(
        f"INSERT INTO {O}.embarazo (id_paciente, id_clinica, numero_gestas, numero_partos, "
        "fecha_inicio, fecha_probable_parto, estado_embarazo) "
        "VALUES (:paciente, 101, 1, 0, '2025-05-05', :fpp, 'ACTIVO')",
        paciente=con_embarazo, fpp=date(2025, 5, 5) + timedelta(days=280),
    )
    [(sin_afiliacion,)] = clon.escribir(
        f"INSERT INTO {O}.medico (id_especialidad, primer_nombre, apellido_paterno, email_med) "
        "VALUES (100, 'Medico', 'Nuevo', 'medico.nuevo@ejemplo.test') RETURNING id_medico"
    )

    resultado = ejecutar_etl(clon.engine)

    assert resultado.informe.correcta
    assert resultado.hechos_nuevos == LECTURAS
    assert clon.escalar(
        f"SELECT id_clinica FROM {A}.dim_paciente WHERE id_paciente = :id", id=sin_embarazo
    ) is None
    assert clon.escalar(
        f"SELECT id_clinica FROM {A}.dim_paciente WHERE id_paciente = :id", id=con_embarazo
    ) == 101
    assert clon.escalar(
        f"SELECT id_clinica FROM {A}.dim_medico WHERE id_medico = :id", id=sin_afiliacion
    ) is None
    # Pendientes contados en cada ejecución, no fijados: ahora hay 31 embarazos.
    assert resultado.informe.discrepancias("clasificacion_embarazo_pendiente") == 31
    assert resultado.informe.conteos["dim_embarazo"] == 31
    assert resultado.informe.discrepancias("huerfanos_de_dimensiones") == 0


# ---------------------------------------------------------------------------
# 8. Fechas del embarazo y zona horaria
# ---------------------------------------------------------------------------


def test_el_cierre_se_juzga_por_el_dia_de_panama(clon):
    clon.escribir(
        f"UPDATE {O}.embarazo SET fecha_cierre = '2025-10-01' WHERE id_embarazo = :e",
        e=EMBARAZO_DE_PRUEBA,
    )
    sesion = nueva_sesion(clon, "2025-10-02T02:55:00+00:00", "2025-10-02T06:05:00+00:00")
    # 03:00Z es el 1 de octubre a las 22:00 en Panamá: el mismo día del cierre.
    nueva_lectura(clon, sesion, "2025-10-02T03:00:00+00:00", semana=SEMANA_39)
    assert clon.escalar(
        "SELECT (timestamptz '2025-10-02T03:00:00Z' AT TIME ZONE 'UTC')::date > date '2025-10-01'"
    )  # con el día UTC quedaría fuera

    resultado = ejecutar_etl(clon.engine)
    assert resultado.informe.discrepancias("fecha_fuera_del_embarazo") == 0

    # 06:00Z ya es el 2 de octubre en Panamá: posterior al cierre.
    nueva_lectura(clon, sesion, "2025-10-02T06:00:00+00:00", semana=SEMANA_39)
    with pytest.raises(ConciliacionFallida) as error:
        ejecutar_etl(clon.engine)
    assert error.value.informe.discrepancias("fecha_fuera_del_embarazo") == 1


def test_un_dia_anterior_al_inicio_hace_fallar_la_conciliacion(clon):
    # El seguimiento se adelanta para que el médico se resuelva y el caso
    # llegue hasta la conciliación, que es lo que se prueba aquí.
    clon.escribir(
        f"UPDATE {O}.seguimiento_clinico SET fecha_asignacion = '2025-01-01' "
        "WHERE id_embarazo = :e", e=EMBARAZO_DE_PRUEBA,
    )
    sesion = nueva_sesion(clon, "2025-01-06T02:55:00+00:00", "2025-01-06T03:05:00+00:00")
    # 03:00Z del 6 de enero es el 5 de enero en Panamá: un día antes del inicio.
    nueva_lectura(clon, sesion, "2025-01-06T03:00:00+00:00", semana=SEMANA_1)

    with pytest.raises(ConciliacionFallida) as error:
        ejecutar_etl(clon.engine)

    assert error.value.informe.discrepancias("fecha_fuera_del_embarazo") == 1
    assert set(conteos_analiticos(clon).values()) == {0}


def test_la_fecha_probable_de_parto_no_es_un_limite(clon):
    embarazo = clon.escalar(
        f"SELECT min(e.id_embarazo) FROM {O}.embarazo e WHERE e.fecha_cierre IS NULL"
    )
    clon.escribir(
        f"UPDATE {O}.embarazo SET fecha_probable_parto = fecha_inicio + 140 "
        "WHERE id_embarazo = :e", e=embarazo,
    )
    posteriores = clon.escalar(
        f"SELECT count(*) FROM {O}.lectura_biometrica l "
        f"JOIN {O}.sesion_monitoreo s USING (id_sesion) "
        f"JOIN {O}.embarazo e ON e.id_embarazo = s.id_embarazo "
        "WHERE e.id_embarazo = :e "
        "AND (l.fecha_hora_captura AT TIME ZONE 'America/Panama')::date > e.fecha_probable_parto",
        e=embarazo,
    )
    assert posteriores > 0

    resultado = ejecutar_etl(clon.engine)

    assert resultado.informe.discrepancias("fecha_fuera_del_embarazo") == 0
    assert clon.escalar(
        f"SELECT duracion_est_semanas FROM {A}.dim_embarazo WHERE id_embarazo = :e",
        e=embarazo,
    ) == 20


def test_el_medico_se_decide_por_el_dia_de_panama_y_no_por_el_de_utc(clon):
    inicio = date(2025, 1, 1)
    [(paciente,)] = clon.escribir(
        f"INSERT INTO {O}.paciente (cedula, primer_nombre, apellido_paterno, email_pac, fecha_nac) "
        "VALUES ('0-000-6901', 'Paciente', 'Zona', 'zona.horaria@ejemplo.test', '1994-04-04') "
        "RETURNING id_paciente"
    )
    [(embarazo,)] = clon.escribir(
        f"INSERT INTO {O}.embarazo (id_paciente, id_clinica, numero_gestas, numero_partos, "
        "fecha_inicio, fecha_probable_parto, estado_embarazo) "
        "VALUES (:paciente, 100, 1, 0, :inicio, :fpp, 'ACTIVO') RETURNING id_embarazo",
        paciente=paciente, inicio=inicio, fpp=inicio + timedelta(days=280),
    )
    medicos = []
    for letra in ("a", "b"):
        [(medico,)] = clon.escribir(
            f"INSERT INTO {O}.medico (id_especialidad, primer_nombre, apellido_paterno, email_med) "
            f"VALUES (100, 'Medico', '{letra.upper()}', 'medico.{letra}.zona@ejemplo.test') "
            "RETURNING id_medico"
        )
        clon.escribir(
            f"INSERT INTO {O}.medico_clinica (id_medico, id_clinica, fecha_inicio) "
            "VALUES (:medico, 100, '2024-01-01')", medico=medico,
        )
        medicos.append(medico)
    medico_a, medico_b = medicos
    clon.escribir(
        f"INSERT INTO {O}.seguimiento_clinico "
        "(id_embarazo, id_medico, fecha_asignacion, fecha_fin, rol_seguimiento, activo) VALUES "
        "(:embarazo, :a, '2025-01-01', '2025-02-28', 'PRINCIPAL', false), "
        "(:embarazo, :b, '2025-03-01', NULL, 'PRINCIPAL', true)",
        embarazo=embarazo, a=medico_a, b=medico_b,
    )
    [(dispositivo,)] = clon.escribir(
        f"INSERT INTO {O}.dispositivo (id_clinica, codigo_dispositivo, modelo, version_firmware) "
        "VALUES (100, 'FA-ZONA-6901', 'SIMULADO', '1.0') RETURNING id_dispositivo"
    )
    clon.escribir(
        f"INSERT INTO {O}.asignacion_dispositivo (id_dispositivo, id_embarazo, fecha_inicio) "
        "VALUES (:dispositivo, :embarazo, '2025-01-01')",
        dispositivo=dispositivo, embarazo=embarazo,
    )
    sesion = nueva_sesion(
        clon, "2025-03-01T03:25:00+00:00", "2025-03-01T03:35:00+00:00",
        id_embarazo=embarazo, id_dispositivo=dispositivo,
    )
    # 2025-03-01T03:30Z es el 28 de febrero a las 22:30 en Panamá: semana 9.
    id_lectura = nueva_lectura(clon, sesion, "2025-03-01T03:30:00+00:00", semana=SEMANA_9)
    # La trampa existe: con el día UTC, el seguimiento vigente sería el de B.
    assert clon.escalar(
        f"SELECT id_medico FROM {O}.seguimiento_clinico WHERE id_embarazo = :embarazo "
        "AND fecha_asignacion <= (timestamptz '2025-03-01T03:30:00Z' AT TIME ZONE 'UTC')::date "
        "AND (fecha_fin IS NULL OR fecha_fin >= "
        "(timestamptz '2025-03-01T03:30:00Z' AT TIME ZONE 'UTC')::date)",
        embarazo=embarazo,
    ) == medico_b

    resultado = ejecutar_etl(clon.engine)

    assert resultado.informe.correcta
    assert clon.escalar(
        f"SELECT id_medico FROM {A}.fact_lectura_biometrica WHERE id_lectura = :id",
        id=id_lectura,
    ) == medico_a


# ---------------------------------------------------------------------------
# 9. El comando: códigos de salida y salida sin datos personales
# ---------------------------------------------------------------------------


def _datos_personales(base: BaseTemporal) -> list[str]:
    valores = []
    for sql in (
        f"SELECT cedula, nombre_completo, telefono_pac FROM {A}.dim_paciente",
        f"SELECT nombre_completo, email_med, telefono_med FROM {A}.dim_medico",
    ):
        for fila in base.filas(sql):
            valores += [str(valor) for valor in fila if valor]
    return valores


def test_el_comando_ejecuta_concilia_y_no_imprime_datos_personales(cli, clon, capsys, monkeypatch):
    monkeypatch.setattr(settings, "database_url", clon.url)
    id_lectura, semana_original = lectura_de_movimiento(clon)
    clave = make_url(clon.url).password

    # 1. Un dato imposible: código 2 y nada escrito.
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_tiempo_gest = :semana WHERE id_lectura = :id",
        semana=SEMANA_19, id=id_lectura,
    )
    assert cli.main(["ejecutar"]) == cli.CODIGO_ORIGEN_RECHAZADO
    fallo = capsys.readouterr()
    assert "resultado=FAILED" in fallo.err
    assert f"id_lectura={id_lectura}" in fallo.err
    # El mensaje nombra la regla y la semana, nunca el conteo de movimientos.
    assert "semana 19" in fallo.err

    # 2. Corregido: código 0 y el resumen completo.
    clon.escribir(
        f"UPDATE {O}.lectura_biometrica SET id_tiempo_gest = :semana WHERE id_lectura = :id",
        semana=semana_original, id=id_lectura,
    )
    assert cli.main(["ejecutar"]) == cli.CODIGO_DE_EXITO
    exito = capsys.readouterr()
    assert "resultado=SUCCESS" in exito.out
    assert "hechos_nuevos=1180" in exito.out
    assert "semaforo: OK=826 WARNING=295 ERROR=59" in exito.out
    assert "clasificacion_embarazo_pendiente=30" in exito.out

    # 3. Conciliación de solo lectura: código 0.
    assert cli.main(["conciliar"]) == cli.CODIGO_DE_EXITO
    conciliacion = capsys.readouterr()

    # 4. Candado ocupado por otra transacción: código 4, sin esperar.
    with otra_ejecucion_con_el_candado(clon, confirmar=False):
        assert cli.main(["ejecutar"]) == cli.CODIGO_CANDADO_OCUPADO
    candado = capsys.readouterr()
    assert "resultado=FAILED" in candado.err

    salida_completa = "".join(
        parte for captura in (fallo, exito, conciliacion, candado)
        for parte in (captura.out, captura.err)
    )
    for dato in _datos_personales(clon):
        assert dato not in salida_completa
    assert clave not in salida_completa
    assert "postgresql+psycopg" not in salida_completa
