"""Optional round trip of the initial revision against a real PostgreSQL server.

Skipped unless ``SCRUM52_TEST_DATABASE_URL`` is set, so the normal suite stays
offline and CI does not need a database. When it is set, the module runs the
full cycle once per session::

    upgrade head -> inspect -> downgrade base -> upgrade head -> alembic check

and leaves the database at ``head`` so the evidence can be captured afterwards
with psql or pgAdmin.

Safety rails, because the cycle drops and recreates the whole ``operacional``
schema:

* the connected database must be named exactly ``scrum52_validacion_tmp``;
  anything else aborts before a single statement runs;
* an ``operacional`` schema that this revision did not stamp aborts as well,
  rather than being taken over;
* the database is never created, never dropped, and its URL is never printed.

Run it from ``backend/`` with::

    $env:SCRUM52_TEST_DATABASE_URL = "postgresql+psycopg://<usuario>:<clave>@127.0.0.1:<puerto>/scrum52_validacion_tmp"
    .\\.venv\\Scripts\\python.exe -m pytest tests/test_migration_postgresql.py -v
"""

import os
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import (
    CheckConstraint,
    UniqueConstraint,
    create_engine,
    delete,
    insert,
    inspect,
    select,
    text,
)

import app.models  # noqa: F401  -- registers every model on Base.metadata
from app.config import settings
from app.db.base import SCHEMA_OPERACIONAL, Base
from tests.conftest import construir_config_alembic
from tests.test_migrations import CANTIDADES_ESPERADAS
from tests.test_models import (
    COLUMNAS_NULLABLE_ESPERADAS,
    FOREIGN_KEYS_ESPERADAS,
    ONDELETE_ESPERADOS,
    PRIMARY_KEYS_ESPERADAS,
    TABLAS_ESPERADAS,
)

VARIABLE_DE_ENTORNO = "SCRUM52_TEST_DATABASE_URL"
NOMBRE_DE_BASE_REQUERIDO = "scrum52_validacion_tmp"

pytestmark = pytest.mark.skipif(
    not os.environ.get(VARIABLE_DE_ENTORNO),
    reason=(
        f"Define {VARIABLE_DE_ENTORNO} apuntando a la base dedicada "
        f"{NOMBRE_DE_BASE_REQUERIDO} para ejecutar la validación contra PostgreSQL."
    ),
)


@dataclass
class EstructuraDesplegada:
    """Snapshot of what actually exists in the server after an upgrade."""

    tablas: set[str] = field(default_factory=set)
    llaves_primarias: dict[str, tuple[str, ...]] = field(default_factory=dict)
    llaves_foraneas: set[tuple[str, str, str, str, str | None]] = field(
        default_factory=set
    )
    indices_explicitos: set[tuple[str, str, tuple[str, ...]]] = field(
        default_factory=set
    )
    restricciones_unique: set[tuple[str, str, tuple[str, ...]]] = field(
        default_factory=set
    )
    restricciones_check: set[tuple[str, str]] = field(default_factory=set)
    columnas: dict[str, set[str]] = field(default_factory=dict)
    columnas_nullable: dict[str, set[str]] = field(default_factory=dict)
    tipos: dict[tuple[str, str], str] = field(default_factory=dict)


def _describir_tipo(tipo) -> str:
    """``str(tipo)`` alone hides the time zone flag of TIMESTAMP columns."""
    if getattr(tipo, "timezone", False):
        return f"{tipo} WITH TIME ZONE"
    return str(tipo)


def _tomar_estructura(engine) -> EstructuraDesplegada:
    inspector = inspect(engine)
    estructura = EstructuraDesplegada()
    estructura.tablas = set(inspector.get_table_names(schema=SCHEMA_OPERACIONAL))

    for tabla in sorted(estructura.tablas):
        pk = inspector.get_pk_constraint(tabla, schema=SCHEMA_OPERACIONAL)
        estructura.llaves_primarias[tabla] = tuple(pk["constrained_columns"])

        for fk in inspector.get_foreign_keys(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.llaves_foraneas.add(
                (
                    tabla,
                    fk["constrained_columns"][0],
                    fk["referred_table"],
                    fk["referred_columns"][0],
                    fk.get("options", {}).get("ondelete"),
                )
            )

        for indice in inspector.get_indexes(tabla, schema=SCHEMA_OPERACIONAL):
            # PostgreSQL materialises every UNIQUE constraint as an index too;
            # duplicates_constraint marks those, leaving the declared ones.
            if indice.get("duplicates_constraint"):
                continue
            estructura.indices_explicitos.add(
                (tabla, indice["name"], tuple(indice["column_names"]))
            )

        for unica in inspector.get_unique_constraints(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.restricciones_unique.add(
                (tabla, unica["name"], tuple(unica["column_names"]))
            )

        for check in inspector.get_check_constraints(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.restricciones_check.add((tabla, check["name"]))

        columnas = inspector.get_columns(tabla, schema=SCHEMA_OPERACIONAL)
        estructura.columnas[tabla] = {c["name"] for c in columnas}
        estructura.columnas_nullable[tabla] = {
            c["name"] for c in columnas if c["nullable"]
        }
        for columna in columnas:
            estructura.tipos[(tabla, columna["name"])] = _describir_tipo(columna["type"])

    return estructura


def _esquemas(engine) -> set[str]:
    return set(inspect(engine).get_schema_names())


def _revision_estampada(engine) -> str | None:
    """Revision recorded in alembic_version, or None if the table is not there yet."""
    with engine.connect() as conexion:
        existe = conexion.execute(
            text("select to_regclass('public.alembic_version')")
        ).scalar()
        if existe is None:
            return None
        return conexion.execute(text("select version_num from alembic_version")).scalar()


@dataclass
class ResultadoDelCiclo:
    revision_inicial: str
    estructura_tras_primer_upgrade: EstructuraDesplegada
    esquemas_tras_primer_upgrade: set[str]
    esquemas_tras_downgrade: set[str]
    estructura_tras_segundo_upgrade: EstructuraDesplegada
    revision_final: str | None
    diferencias_de_alembic_check: str | None


@pytest.fixture(scope="session")
def ciclo() -> ResultadoDelCiclo:
    """Run upgrade -> downgrade -> upgrade -> check once, and snapshot each step."""
    url = os.environ[VARIABLE_DE_ENTORNO]
    engine = create_engine(url)

    with engine.connect() as conexion:
        nombre = conexion.execute(text("select current_database()")).scalar()
    if nombre != NOMBRE_DE_BASE_REQUERIDO:
        # No URL in the message: it carries credentials.
        pytest.fail(
            f"{VARIABLE_DE_ENTORNO} apunta a la base '{nombre}'. Esta validación "
            f"borra y recrea el esquema {SCHEMA_OPERACIONAL} completo, así que sólo "
            f"se ejecuta contra la base dedicada '{NOMBRE_DE_BASE_REQUERIDO}'."
        )

    config = construir_config_alembic()
    revision_inicial = ScriptDirectory.from_config(config).get_bases()[0]

    estampada = _revision_estampada(engine)
    if SCHEMA_OPERACIONAL in _esquemas(engine) and estampada != revision_inicial:
        pytest.fail(
            f"La base '{nombre}' ya tiene un esquema {SCHEMA_OPERACIONAL} que esta "
            f"revisión no creó (alembic_version: {estampada!r}). Se aborta en lugar "
            "de adoptarlo o eliminarlo."
        )

    with pytest.MonkeyPatch.context() as parche:
        # alembic/env.py resolves the URL from settings, not from the Config, so
        # this is what actually keeps the cycle away from the development database.
        parche.setattr(settings, "database_url", url)

        if estampada == revision_inicial:
            command.downgrade(config, "base")

        command.upgrade(config, "head")
        estructura_1 = _tomar_estructura(engine)
        esquemas_1 = _esquemas(engine)

        command.downgrade(config, "base")
        esquemas_tras_downgrade = _esquemas(engine)

        command.upgrade(config, "head")
        estructura_2 = _tomar_estructura(engine)

        try:
            command.check(config)
            diferencias = None
        except AutogenerateDiffsDetected as error:
            diferencias = str(error)

        revision_final = _revision_estampada(engine)

    engine.dispose()
    return ResultadoDelCiclo(
        revision_inicial=revision_inicial,
        estructura_tras_primer_upgrade=estructura_1,
        esquemas_tras_primer_upgrade=esquemas_1,
        esquemas_tras_downgrade=esquemas_tras_downgrade,
        estructura_tras_segundo_upgrade=estructura_2,
        revision_final=revision_final,
        diferencias_de_alembic_check=diferencias,
    )


# --------------------------------------------------------------------------
# Esquema y tablas
# --------------------------------------------------------------------------


def test_el_upgrade_crea_el_esquema_operacional(ciclo):
    assert SCHEMA_OPERACIONAL in ciclo.esquemas_tras_primer_upgrade


def test_el_upgrade_crea_exactamente_las_tablas_de_la_metadata(ciclo):
    assert ciclo.estructura_tras_primer_upgrade.tablas == TABLAS_ESPERADAS
    assert len(ciclo.estructura_tras_primer_upgrade.tablas) == len(Base.metadata.tables)


# --------------------------------------------------------------------------
# Llaves primarias
# --------------------------------------------------------------------------


def test_las_llaves_primarias_desplegadas_coinciden(ciclo):
    assert ciclo.estructura_tras_primer_upgrade.llaves_primarias == (
        PRIMARY_KEYS_ESPERADAS
    )


# --------------------------------------------------------------------------
# Llaves foráneas y políticas de borrado
# --------------------------------------------------------------------------


def test_las_llaves_foraneas_desplegadas_apuntan_a_donde_deben(ciclo):
    desplegadas = {
        (tabla, columna): (tabla_ref, columna_ref)
        for tabla, columna, tabla_ref, columna_ref, _ in (
            ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        )
    }

    assert desplegadas == FOREIGN_KEYS_ESPERADAS


def test_las_politicas_on_delete_desplegadas_coinciden(ciclo):
    desplegadas = {
        (tabla, columna): politica
        for tabla, columna, _, _, politica in (
            ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        )
    }

    assert desplegadas == ONDELETE_ESPERADOS


@pytest.mark.parametrize("politica", ["RESTRICT", "CASCADE"])
def test_cantidad_de_politicas_desplegadas(politica, ciclo):
    esperadas = sum(1 for p in ONDELETE_ESPERADOS.values() if p == politica)
    desplegadas = sum(
        1
        for *_, encontrada in ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        if encontrada == politica
    )

    assert desplegadas == esperadas


# --------------------------------------------------------------------------
# Índices y restricciones
# --------------------------------------------------------------------------


def test_los_indices_explicitos_desplegados_coinciden(ciclo):
    esperados = {
        (tabla.name, indice.name, tuple(c.name for c in indice.columns))
        for tabla in Base.metadata.tables.values()
        for indice in tabla.indexes
    }

    assert ciclo.estructura_tras_primer_upgrade.indices_explicitos == esperados


def test_las_restricciones_unique_desplegadas_coinciden(ciclo):
    esperadas = {
        (tabla.name, constraint.name, tuple(c.name for c in constraint.columns))
        for tabla in Base.metadata.tables.values()
        for constraint in tabla.constraints
        if isinstance(constraint, UniqueConstraint)
    }

    assert ciclo.estructura_tras_primer_upgrade.restricciones_unique == esperadas


def test_las_restricciones_check_desplegadas_coinciden(ciclo):
    esperadas = {
        (tabla.name, constraint.name)
        for tabla in Base.metadata.tables.values()
        for constraint in tabla.constraints
        if isinstance(constraint, CheckConstraint)
    }

    assert ciclo.estructura_tras_primer_upgrade.restricciones_check == esperadas


def test_las_cantidades_desplegadas_coinciden_con_lo_pinneado(ciclo):
    """UNIQUE dropped from 18 to 17 with the 1:N change; nothing else moved."""
    estructura = ciclo.estructura_tras_primer_upgrade
    reales = {
        "tablas": len(estructura.tablas),
        "primary_key": len(estructura.llaves_primarias),
        "foreign_key": len(estructura.llaves_foraneas),
        "on_delete_restrict": sum(
            1 for *_, politica in estructura.llaves_foraneas if politica == "RESTRICT"
        ),
        "on_delete_cascade": sum(
            1 for *_, politica in estructura.llaves_foraneas if politica == "CASCADE"
        ),
        "unique": len(estructura.restricciones_unique),
        "check": len(estructura.restricciones_check),
        "indices": len(estructura.indices_explicitos),
    }

    assert reales == CANTIDADES_ESPERADAS


def test_id_sesion_no_es_unico_en_el_servidor(ciclo):
    """A surviving UNIQUE would cap the session at a single reading."""
    unicas = ciclo.estructura_tras_primer_upgrade.restricciones_unique
    nombres = {nombre for _, nombre, _ in unicas}

    assert "uq_lectura_biometrica_id_sesion" not in nombres
    assert not [fila for fila in unicas if fila[0] == "lectura_biometrica"]


def test_id_sesion_conserva_nulabilidad_y_borrado_en_cascada(ciclo):
    """Loosening the cardinality must not touch NOT NULL, the FK or ON DELETE."""
    estructura = ciclo.estructura_tras_primer_upgrade

    assert "id_sesion" not in estructura.columnas_nullable["lectura_biometrica"]
    assert (
        "lectura_biometrica",
        "id_sesion",
        "sesion_monitoreo",
        "id_sesion",
        "CASCADE",
    ) in estructura.llaves_foraneas


# --------------------------------------------------------------------------
# Columnas, nulabilidad y tipos
# --------------------------------------------------------------------------


@pytest.mark.parametrize("nombre_tabla", sorted(TABLAS_ESPERADAS))
def test_las_columnas_desplegadas_coinciden_con_la_metadata(nombre_tabla, ciclo):
    tabla = Base.metadata.tables[f"{SCHEMA_OPERACIONAL}.{nombre_tabla}"]
    esperadas = {c.name for c in tabla.columns}

    assert ciclo.estructura_tras_primer_upgrade.columnas[nombre_tabla] == esperadas


@pytest.mark.parametrize("nombre_tabla", sorted(COLUMNAS_NULLABLE_ESPERADAS))
def test_la_nulabilidad_desplegada_coincide(nombre_tabla, ciclo):
    assert ciclo.estructura_tras_primer_upgrade.columnas_nullable[nombre_tabla] == (
        COLUMNAS_NULLABLE_ESPERADAS[nombre_tabla]
    )


@pytest.mark.parametrize(
    ("nombre_tabla", "nombre_columna", "tipo_esperado"),
    [
        ("lectura_biometrica", "hr_valor", "NUMERIC(5, 2)"),
        ("lectura_biometrica", "spo2_valor", "NUMERIC(5, 2)"),
        ("lectura_biometrica", "mov_valor", "SMALLINT"),
        ("lectura_biometrica", "fecha_hora_captura", "TIMESTAMP WITH TIME ZONE"),
        ("sesion_monitoreo", "fecha_inicio", "TIMESTAMP WITH TIME ZONE"),
        ("auditoria_log", "fecha_hora", "TIMESTAMP WITH TIME ZONE"),
        ("auditoria_log", "id_entidad_afectada", "VARCHAR(255)"),
        ("telefono_paciente", "valor_contacto", "VARCHAR(120)"),
        ("telefono_medico", "valor_contacto", "VARCHAR(120)"),
        # native_enum=False: the enum reaches PostgreSQL as a checked VARCHAR.
        ("telefono_paciente", "tipo_contacto", "VARCHAR(30)"),
        ("sesion_monitoreo", "estado_sesion", "VARCHAR(30)"),
    ],
)
def test_tipos_relevantes_desplegados(nombre_tabla, nombre_columna, tipo_esperado, ciclo):
    assert ciclo.estructura_tras_primer_upgrade.tipos[(nombre_tabla, nombre_columna)] == (
        tipo_esperado
    )


def test_no_se_creo_ningun_tipo_enum_nativo(ciclo):
    """A native ENUM would survive downgrade and block a value list change."""
    url = os.environ[VARIABLE_DE_ENTORNO]
    engine = create_engine(url)
    with engine.connect() as conexion:
        nativos = conexion.execute(
            text(
                "select count(*) from pg_type t"
                " join pg_namespace n on n.oid = t.typnamespace"
                " where t.typtype = 'e' and n.nspname = :esquema"
            ),
            {"esquema": SCHEMA_OPERACIONAL},
        ).scalar()
    engine.dispose()

    assert nativos == 0


# --------------------------------------------------------------------------
# Reversibilidad
# --------------------------------------------------------------------------


def test_el_downgrade_elimina_el_esquema_creado(ciclo):
    assert SCHEMA_OPERACIONAL not in ciclo.esquemas_tras_downgrade


def test_el_downgrade_no_arrastra_el_esquema_public(ciclo):
    """DROP SCHEMA without CASCADE must leave everything else standing."""
    assert "public" in ciclo.esquemas_tras_downgrade


def test_el_segundo_upgrade_reconstruye_una_estructura_identica(ciclo):
    assert (
        ciclo.estructura_tras_segundo_upgrade == ciclo.estructura_tras_primer_upgrade
    )


# --------------------------------------------------------------------------
# Estado final
# --------------------------------------------------------------------------


def test_la_base_queda_en_la_revision_inicial(ciclo):
    assert ciclo.revision_final == ciclo.revision_inicial


def test_alembic_check_no_reporta_divergencia(ciclo):
    assert ciclo.diferencias_de_alembic_check is None, (
        "alembic check encontró operaciones pendientes: "
        f"{ciclo.diferencias_de_alembic_check}"
    )


# --------------------------------------------------------------------------
# Cardinalidad 1:N ejercida contra el servidor
# --------------------------------------------------------------------------

# SCRUM-54 plans five representative readings per session. Five is what the
# dataset will generate, not a rule the database enforces: nothing here caps or
# requires that number, the point is only that more than one is accepted.
LECTURAS_POR_SESION = 5


def tabla_operacional(nombre: str):
    return Base.metadata.tables[f"{SCHEMA_OPERACIONAL}.{nombre}"]


@pytest.fixture
def conexion_revertible(ciclo):
    """Connection whose transaction is always rolled back.

    Every row these tests insert disappears when the fixture tears down, so the
    temporary database keeps only the schema the migration deployed.
    """
    engine = create_engine(os.environ[VARIABLE_DE_ENTORNO])
    conexion = engine.connect()
    transaccion = conexion.begin()
    try:
        yield conexion
    finally:
        transaccion.rollback()
        conexion.close()
        engine.dispose()


def _sembrar_sesion(conexion) -> int:
    """Insert the minimum fictitious chain a session needs, and return its id.

    All data is invented: clinic, patient, pregnancy and device exist only to
    satisfy the foreign keys that ``sesion_monitoreo`` depends on.
    """
    id_clinica = conexion.execute(
        insert(tabla_operacional("clinica"))
        .values(
            nombre_clinica="Centro de Salud Ficticio SCRUM-52",
            ruc="RUC-FICTICIO-SCRUM52",
            provincia="Veraguas",
            distrito="Santa Fe",
            corregimiento="El Alto",
            direccion_fisica="Camino ficticio sin numero",
        )
        .returning(tabla_operacional("clinica").c.id_clinica)
    ).scalar_one()

    id_paciente = conexion.execute(
        insert(tabla_operacional("paciente"))
        .values(
            cedula="0-000-0000",
            primer_nombre="Paciente",
            apellido_paterno="Ficticia",
            email_pac="paciente.ficticia@ejemplo.invalid",
            fecha_nac=date(1998, 3, 14),
        )
        .returning(tabla_operacional("paciente").c.id_paciente)
    ).scalar_one()

    id_embarazo = conexion.execute(
        insert(tabla_operacional("embarazo"))
        .values(
            id_paciente=id_paciente,
            id_clinica=id_clinica,
            numero_gestas=2,
            numero_partos=1,
            fecha_inicio=date(2026, 1, 5),
            fecha_probable_parto=date(2026, 10, 12),
        )
        .returning(tabla_operacional("embarazo").c.id_embarazo)
    ).scalar_one()

    id_dispositivo = conexion.execute(
        insert(tabla_operacional("dispositivo"))
        .values(
            id_clinica=id_clinica,
            codigo_dispositivo="DISPOSITIVO-FICTICIO-SCRUM52",
            modelo="Modelo simulado",
            version_firmware="0.0.0-sim",
        )
        .returning(tabla_operacional("dispositivo").c.id_dispositivo)
    ).scalar_one()

    return conexion.execute(
        insert(tabla_operacional("sesion_monitoreo"))
        .values(
            id_embarazo=id_embarazo,
            id_dispositivo=id_dispositivo,
            tipo_sesion="SIGNOS_MATERNOS",
            fecha_inicio=datetime(2026, 6, 1, 8, 0, tzinfo=timezone.utc),
            fecha_fin=datetime(2026, 6, 1, 8, 30, tzinfo=timezone.utc),
        )
        .returning(tabla_operacional("sesion_monitoreo").c.id_sesion)
    ).scalar_one()


def _sembrar_catalogos_de_lectura(conexion) -> tuple[int, int]:
    id_tiempo_gest = conexion.execute(
        insert(tabla_operacional("tiempo_gestacional"))
        .values(
            semana_gestacion=24,
            mes_gestacion=6,
            trimestre=2,
            grupo_clinico="Segundo trimestre",
        )
        .returning(tabla_operacional("tiempo_gestacional").c.id_tiempo_gest)
    ).scalar_one()

    id_semaforo = conexion.execute(
        insert(tabla_operacional("semaforo"))
        .values(
            codigo_nivel="OK",
            etiqueta_visual="Normal",
            color_hex="#0AA36B",
            prioridad=1,
            mensaje_app="Todo dentro del rango esperado.",
            version_referencia="sim-1.0",
        )
        .returning(tabla_operacional("semaforo").c.id_semaforo)
    ).scalar_one()

    return id_tiempo_gest, id_semaforo


def _insertar_lecturas(conexion, id_sesion: int, cantidad: int) -> list[int]:
    """Insert ``cantidad`` distinct maternal-vitals readings on the same session."""
    id_tiempo_gest, id_semaforo = _sembrar_catalogos_de_lectura(conexion)
    captura = datetime(2026, 6, 1, 8, 0, tzinfo=timezone.utc)
    lectura = tabla_operacional("lectura_biometrica")

    return [
        conexion.execute(
            insert(lectura)
            .values(
                id_sesion=id_sesion,
                id_tiempo_gest=id_tiempo_gest,
                id_semaforo=id_semaforo,
                fecha_hora_captura=captura + timedelta(minutes=5 * i),
                hr_valor=Decimal("78.50") + i,
                spo2_valor=Decimal("97.00"),
            )
            .returning(lectura.c.id_lectura)
        ).scalar_one()
        for i in range(cantidad)
    ]


def test_postgresql_acepta_cinco_lecturas_en_la_misma_sesion(conexion_revertible):
    """The 1:N is only real if the server itself accepts the five inserts."""
    id_sesion = _sembrar_sesion(conexion_revertible)

    ids = _insertar_lecturas(conexion_revertible, id_sesion, LECTURAS_POR_SESION)

    assert len(set(ids)) == LECTURAS_POR_SESION

    lectura = tabla_operacional("lectura_biometrica")
    filas = conexion_revertible.execute(
        select(lectura.c.id_lectura, lectura.c.id_sesion).where(
            lectura.c.id_sesion == id_sesion
        )
    ).all()

    assert len(filas) == LECTURAS_POR_SESION
    # Cada lectura sigue perteneciendo a una sola sesión: la misma para las cinco.
    assert {fila.id_sesion for fila in filas} == {id_sesion}
    assert {fila.id_lectura for fila in filas} == set(ids)


def test_borrar_la_sesion_arrastra_sus_lecturas_por_cascade(conexion_revertible):
    """ON DELETE CASCADE must still remove every reading of the session."""
    id_sesion = _sembrar_sesion(conexion_revertible)
    _insertar_lecturas(conexion_revertible, id_sesion, LECTURAS_POR_SESION)
    lectura = tabla_operacional("lectura_biometrica")

    def cuantas() -> int:
        return len(
            conexion_revertible.execute(
                select(lectura.c.id_lectura).where(lectura.c.id_sesion == id_sesion)
            ).all()
        )

    assert cuantas() == LECTURAS_POR_SESION

    sesion = tabla_operacional("sesion_monitoreo")
    conexion_revertible.execute(delete(sesion).where(sesion.c.id_sesion == id_sesion))

    assert cuantas() == 0


def test_la_base_temporal_no_conserva_filas_de_prueba(ciclo):
    """The reversible transaction must leave the deployed schema empty."""
    engine = create_engine(os.environ[VARIABLE_DE_ENTORNO])
    with engine.connect() as conexion:
        pendientes = {
            nombre: conexion.execute(
                select(text("count(*)")).select_from(tabla_operacional(nombre))
            ).scalar_one()
            for nombre in sorted(TABLAS_ESPERADAS)
        }
    engine.dispose()

    assert pendientes == dict.fromkeys(sorted(TABLAS_ESPERADAS), 0)
