"""Optional round trip of the initial revision against a real PostgreSQL server.

Skipped unless ``SCRUM52_TEST_DATABASE_URL`` is set, so the normal suite stays
offline and CI does not need a database. When it is set, the module runs the
full cycle once per session::

    upgrade head -> inspect -> downgrade base -> upgrade head -> alembic check

and leaves the database at ``head`` so the evidence can be captured afterwards
with psql or pgAdmin.

Safety rails, because the cycle drops and recreates the whole ``operacional``
schema:

* the connected database must be named exactly ``scrum52_validacion_tmp``;
  anything else aborts before a single statement runs;
* an ``operacional`` schema that this revision did not stamp aborts as well,
  rather than being taken over;
* the database is never created, never dropped, and its URL is never printed.

Run it from ``backend/`` with::

    $env:SCRUM52_TEST_DATABASE_URL = "postgresql+psycopg://<usuario>:<clave>@127.0.0.1:<puerto>/scrum52_validacion_tmp"
    .\\.venv\\Scripts\\python.exe -m pytest tests/test_migration_postgresql.py -v
"""

import os
from dataclasses import dataclass, field

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import CheckConstraint, UniqueConstraint, create_engine, inspect, text

import app.models  # noqa: F401  -- registers every model on Base.metadata
from app.config import settings
from app.db.base import SCHEMA_OPERACIONAL, Base
from tests.conftest import construir_config_alembic
from tests.test_models import (
    COLUMNAS_NULLABLE_ESPERADAS,
    FOREIGN_KEYS_ESPERADAS,
    ONDELETE_ESPERADOS,
    PRIMARY_KEYS_ESPERADAS,
    TABLAS_ESPERADAS,
)

VARIABLE_DE_ENTORNO = "SCRUM52_TEST_DATABASE_URL"
NOMBRE_DE_BASE_REQUERIDO = "scrum52_validacion_tmp"

pytestmark = pytest.mark.skipif(
    not os.environ.get(VARIABLE_DE_ENTORNO),
    reason=(
        f"Define {VARIABLE_DE_ENTORNO} apuntando a la base dedicada "
        f"{NOMBRE_DE_BASE_REQUERIDO} para ejecutar la validación contra PostgreSQL."
    ),
)


@dataclass
class EstructuraDesplegada:
    """Snapshot of what actually exists in the server after an upgrade."""

    tablas: set[str] = field(default_factory=set)
    llaves_primarias: dict[str, tuple[str, ...]] = field(default_factory=dict)
    llaves_foraneas: set[tuple[str, str, str, str, str | None]] = field(
        default_factory=set
    )
    indices_explicitos: set[tuple[str, str, tuple[str, ...]]] = field(
        default_factory=set
    )
    restricciones_unique: set[tuple[str, str, tuple[str, ...]]] = field(
        default_factory=set
    )
    restricciones_check: set[tuple[str, str]] = field(default_factory=set)
    columnas: dict[str, set[str]] = field(default_factory=dict)
    columnas_nullable: dict[str, set[str]] = field(default_factory=dict)
    tipos: dict[tuple[str, str], str] = field(default_factory=dict)


def _describir_tipo(tipo) -> str:
    """``str(tipo)`` alone hides the time zone flag of TIMESTAMP columns."""
    if getattr(tipo, "timezone", False):
        return f"{tipo} WITH TIME ZONE"
    return str(tipo)


def _tomar_estructura(engine) -> EstructuraDesplegada:
    inspector = inspect(engine)
    estructura = EstructuraDesplegada()
    estructura.tablas = set(inspector.get_table_names(schema=SCHEMA_OPERACIONAL))

    for tabla in sorted(estructura.tablas):
        pk = inspector.get_pk_constraint(tabla, schema=SCHEMA_OPERACIONAL)
        estructura.llaves_primarias[tabla] = tuple(pk["constrained_columns"])

        for fk in inspector.get_foreign_keys(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.llaves_foraneas.add(
                (
                    tabla,
                    fk["constrained_columns"][0],
                    fk["referred_table"],
                    fk["referred_columns"][0],
                    fk.get("options", {}).get("ondelete"),
                )
            )

        for indice in inspector.get_indexes(tabla, schema=SCHEMA_OPERACIONAL):
            # PostgreSQL materialises every UNIQUE constraint as an index too;
            # duplicates_constraint marks those, leaving the declared ones.
            if indice.get("duplicates_constraint"):
                continue
            estructura.indices_explicitos.add(
                (tabla, indice["name"], tuple(indice["column_names"]))
            )

        for unica in inspector.get_unique_constraints(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.restricciones_unique.add(
                (tabla, unica["name"], tuple(unica["column_names"]))
            )

        for check in inspector.get_check_constraints(tabla, schema=SCHEMA_OPERACIONAL):
            estructura.restricciones_check.add((tabla, check["name"]))

        columnas = inspector.get_columns(tabla, schema=SCHEMA_OPERACIONAL)
        estructura.columnas[tabla] = {c["name"] for c in columnas}
        estructura.columnas_nullable[tabla] = {
            c["name"] for c in columnas if c["nullable"]
        }
        for columna in columnas:
            estructura.tipos[(tabla, columna["name"])] = _describir_tipo(columna["type"])

    return estructura


def _esquemas(engine) -> set[str]:
    return set(inspect(engine).get_schema_names())


def _revision_estampada(engine) -> str | None:
    """Revision recorded in alembic_version, or None if the table is not there yet."""
    with engine.connect() as conexion:
        existe = conexion.execute(
            text("select to_regclass('public.alembic_version')")
        ).scalar()
        if existe is None:
            return None
        return conexion.execute(text("select version_num from alembic_version")).scalar()


@dataclass
class ResultadoDelCiclo:
    revision_inicial: str
    estructura_tras_primer_upgrade: EstructuraDesplegada
    esquemas_tras_primer_upgrade: set[str]
    esquemas_tras_downgrade: set[str]
    estructura_tras_segundo_upgrade: EstructuraDesplegada
    revision_final: str | None
    diferencias_de_alembic_check: str | None


@pytest.fixture(scope="session")
def ciclo() -> ResultadoDelCiclo:
    """Run upgrade -> downgrade -> upgrade -> check once, and snapshot each step."""
    url = os.environ[VARIABLE_DE_ENTORNO]
    engine = create_engine(url)

    with engine.connect() as conexion:
        nombre = conexion.execute(text("select current_database()")).scalar()
    if nombre != NOMBRE_DE_BASE_REQUERIDO:
        # No URL in the message: it carries credentials.
        pytest.fail(
            f"{VARIABLE_DE_ENTORNO} apunta a la base '{nombre}'. Esta validación "
            f"borra y recrea el esquema {SCHEMA_OPERACIONAL} completo, así que sólo "
            f"se ejecuta contra la base dedicada '{NOMBRE_DE_BASE_REQUERIDO}'."
        )

    config = construir_config_alembic()
    revision_inicial = ScriptDirectory.from_config(config).get_bases()[0]

    estampada = _revision_estampada(engine)
    if SCHEMA_OPERACIONAL in _esquemas(engine) and estampada != revision_inicial:
        pytest.fail(
            f"La base '{nombre}' ya tiene un esquema {SCHEMA_OPERACIONAL} que esta "
            f"revisión no creó (alembic_version: {estampada!r}). Se aborta en lugar "
            "de adoptarlo o eliminarlo."
        )

    with pytest.MonkeyPatch.context() as parche:
        # alembic/env.py resolves the URL from settings, not from the Config, so
        # this is what actually keeps the cycle away from the development database.
        parche.setattr(settings, "database_url", url)

        if estampada == revision_inicial:
            command.downgrade(config, "base")

        command.upgrade(config, "head")
        estructura_1 = _tomar_estructura(engine)
        esquemas_1 = _esquemas(engine)

        command.downgrade(config, "base")
        esquemas_tras_downgrade = _esquemas(engine)

        command.upgrade(config, "head")
        estructura_2 = _tomar_estructura(engine)

        try:
            command.check(config)
            diferencias = None
        except AutogenerateDiffsDetected as error:
            diferencias = str(error)

        revision_final = _revision_estampada(engine)

    engine.dispose()
    return ResultadoDelCiclo(
        revision_inicial=revision_inicial,
        estructura_tras_primer_upgrade=estructura_1,
        esquemas_tras_primer_upgrade=esquemas_1,
        esquemas_tras_downgrade=esquemas_tras_downgrade,
        estructura_tras_segundo_upgrade=estructura_2,
        revision_final=revision_final,
        diferencias_de_alembic_check=diferencias,
    )


# --------------------------------------------------------------------------
# Esquema y tablas
# --------------------------------------------------------------------------


def test_el_upgrade_crea_el_esquema_operacional(ciclo):
    assert SCHEMA_OPERACIONAL in ciclo.esquemas_tras_primer_upgrade


def test_el_upgrade_crea_exactamente_las_tablas_de_la_metadata(ciclo):
    assert ciclo.estructura_tras_primer_upgrade.tablas == TABLAS_ESPERADAS
    assert len(ciclo.estructura_tras_primer_upgrade.tablas) == len(Base.metadata.tables)


# --------------------------------------------------------------------------
# Llaves primarias
# --------------------------------------------------------------------------


def test_las_llaves_primarias_desplegadas_coinciden(ciclo):
    assert ciclo.estructura_tras_primer_upgrade.llaves_primarias == (
        PRIMARY_KEYS_ESPERADAS
    )


# --------------------------------------------------------------------------
# Llaves foráneas y políticas de borrado
# --------------------------------------------------------------------------


def test_las_llaves_foraneas_desplegadas_apuntan_a_donde_deben(ciclo):
    desplegadas = {
        (tabla, columna): (tabla_ref, columna_ref)
        for tabla, columna, tabla_ref, columna_ref, _ in (
            ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        )
    }

    assert desplegadas == FOREIGN_KEYS_ESPERADAS


def test_las_politicas_on_delete_desplegadas_coinciden(ciclo):
    desplegadas = {
        (tabla, columna): politica
        for tabla, columna, _, _, politica in (
            ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        )
    }

    assert desplegadas == ONDELETE_ESPERADOS


@pytest.mark.parametrize("politica", ["RESTRICT", "CASCADE"])
def test_cantidad_de_politicas_desplegadas(politica, ciclo):
    esperadas = sum(1 for p in ONDELETE_ESPERADOS.values() if p == politica)
    desplegadas = sum(
        1
        for *_, encontrada in ciclo.estructura_tras_primer_upgrade.llaves_foraneas
        if encontrada == politica
    )

    assert desplegadas == esperadas


# --------------------------------------------------------------------------
# Índices y restricciones
# --------------------------------------------------------------------------


def test_los_indices_explicitos_desplegados_coinciden(ciclo):
    esperados = {
        (tabla.name, indice.name, tuple(c.name for c in indice.columns))
        for tabla in Base.metadata.tables.values()
        for indice in tabla.indexes
    }

    assert ciclo.estructura_tras_primer_upgrade.indices_explicitos == esperados


def test_las_restricciones_unique_desplegadas_coinciden(ciclo):
    esperadas = {
        (tabla.name, constraint.name, tuple(c.name for c in constraint.columns))
        for tabla in Base.metadata.tables.values()
        for constraint in tabla.constraints
        if isinstance(constraint, UniqueConstraint)
    }

    assert ciclo.estructura_tras_primer_upgrade.restricciones_unique == esperadas


def test_las_restricciones_check_desplegadas_coinciden(ciclo):
    esperadas = {
        (tabla.name, constraint.name)
        for tabla in Base.metadata.tables.values()
        for constraint in tabla.constraints
        if isinstance(constraint, CheckConstraint)
    }

    assert ciclo.estructura_tras_primer_upgrade.restricciones_check == esperadas


def test_la_lectura_es_unica_por_sesion_en_el_servidor(ciclo):
    """The 1:1 only holds if PostgreSQL really enforces UNIQUE on id_sesion."""
    assert (
        "lectura_biometrica",
        "uq_lectura_biometrica_id_sesion",
        ("id_sesion",),
    ) in ciclo.estructura_tras_primer_upgrade.restricciones_unique


# --------------------------------------------------------------------------
# Columnas, nulabilidad y tipos
# --------------------------------------------------------------------------


@pytest.mark.parametrize("nombre_tabla", sorted(TABLAS_ESPERADAS))
def test_las_columnas_desplegadas_coinciden_con_la_metadata(nombre_tabla, ciclo):
    tabla = Base.metadata.tables[f"{SCHEMA_OPERACIONAL}.{nombre_tabla}"]
    esperadas = {c.name for c in tabla.columns}

    assert ciclo.estructura_tras_primer_upgrade.columnas[nombre_tabla] == esperadas


@pytest.mark.parametrize("nombre_tabla", sorted(COLUMNAS_NULLABLE_ESPERADAS))
def test_la_nulabilidad_desplegada_coincide(nombre_tabla, ciclo):
    assert ciclo.estructura_tras_primer_upgrade.columnas_nullable[nombre_tabla] == (
        COLUMNAS_NULLABLE_ESPERADAS[nombre_tabla]
    )


@pytest.mark.parametrize(
    ("nombre_tabla", "nombre_columna", "tipo_esperado"),
    [
        ("lectura_biometrica", "hr_valor", "NUMERIC(5, 2)"),
        ("lectura_biometrica", "spo2_valor", "NUMERIC(5, 2)"),
        ("lectura_biometrica", "mov_valor", "SMALLINT"),
        ("lectura_biometrica", "fecha_hora_captura", "TIMESTAMP WITH TIME ZONE"),
        ("sesion_monitoreo", "fecha_inicio", "TIMESTAMP WITH TIME ZONE"),
        ("auditoria_log", "fecha_hora", "TIMESTAMP WITH TIME ZONE"),
        ("auditoria_log", "id_entidad_afectada", "VARCHAR(255)"),
        ("telefono_paciente", "valor_contacto", "VARCHAR(120)"),
        ("telefono_medico", "valor_contacto", "VARCHAR(120)"),
        # native_enum=False: the enum reaches PostgreSQL as a checked VARCHAR.
        ("telefono_paciente", "tipo_contacto", "VARCHAR(30)"),
        ("sesion_monitoreo", "estado_sesion", "VARCHAR(30)"),
    ],
)
def test_tipos_relevantes_desplegados(nombre_tabla, nombre_columna, tipo_esperado, ciclo):
    assert ciclo.estructura_tras_primer_upgrade.tipos[(nombre_tabla, nombre_columna)] == (
        tipo_esperado
    )


def test_no_se_creo_ningun_tipo_enum_nativo(ciclo):
    """A native ENUM would survive downgrade and block a value list change."""
    url = os.environ[VARIABLE_DE_ENTORNO]
    engine = create_engine(url)
    with engine.connect() as conexion:
        nativos = conexion.execute(
            text(
                "select count(*) from pg_type t"
                " join pg_namespace n on n.oid = t.typnamespace"
                " where t.typtype = 'e' and n.nspname = :esquema"
            ),
            {"esquema": SCHEMA_OPERACIONAL},
        ).scalar()
    engine.dispose()

    assert nativos == 0


# --------------------------------------------------------------------------
# Reversibilidad
# --------------------------------------------------------------------------


def test_el_downgrade_elimina_el_esquema_creado(ciclo):
    assert SCHEMA_OPERACIONAL not in ciclo.esquemas_tras_downgrade


def test_el_downgrade_no_arrastra_el_esquema_public(ciclo):
    """DROP SCHEMA without CASCADE must leave everything else standing."""
    assert "public" in ciclo.esquemas_tras_downgrade


def test_el_segundo_upgrade_reconstruye_una_estructura_identica(ciclo):
    assert (
        ciclo.estructura_tras_segundo_upgrade == ciclo.estructura_tras_primer_upgrade
    )


# --------------------------------------------------------------------------
# Estado final
# --------------------------------------------------------------------------


def test_la_base_queda_en_la_revision_inicial(ciclo):
    assert ciclo.revision_final == ciclo.revision_inicial


def test_alembic_check_no_reporta_divergencia(ciclo):
    assert ciclo.diferencias_de_alembic_check is None, (
        "alembic check encontró operaciones pendientes: "
        f"{ciclo.diferencias_de_alembic_check}"
    )
