"""Password hashing with Argon2id, and the one rule the login flow depends on.

Argon2id is a **hash**, not a cipher: it derives a verifier that cannot be turned
back into the password. Nothing here encrypts anything, and nothing here protects
clinical data -- it protects credentials, and only credentials.

**The unknown user is not a branch.** :func:`verificar` accepts ``None`` as the
stored digest and, instead of returning early, verifies the supplied password
against a dummy hash built once at import. That is what keeps "this account does
not exist" from being cheaper than "this password is wrong": there is no path
through this module that answers without doing the work, so no caller can create
one by accident. The dummy is computed **once**, not per request -- hashing on
every unknown user would be a denial-of-service surface of its own.

This is a reasonable, testable mitigation, not a promise of constant time. The
library's own comparison is what protects the digest itself; the remaining
variation -- scheduling, network -- is outside what this project can claim.

All accounts handled here are fictitious and simulated.
"""

from __future__ import annotations

import secrets

from argon2 import PasswordHasher
from argon2.exceptions import Argon2Error, InvalidHashError

# One hasher for the whole application, with the library's own defaults:
# Argon2**id**, which is what the thesis architecture requires and what
# ``PasswordHasher`` selects when no type is given. The parameters are not
# restated here; pinning copies of them would let this module and the library
# drift apart, and the encoded digest already records the ones it was produced
# with, which is what verification reads.
_HASHER = PasswordHasher()

# Recognisable prefix of an encoded Argon2id digest. Used by the dataset tests
# to assert the algorithm actually in force, never to parse a hash.
PREFIJO_ARGON2ID = "$argon2id$"


def hashear(password: str) -> str:
    """Encoded Argon2id digest of ``password``, with a salt from the library.

    The salt is random and generated by ``argon2-cffi``; this module never
    supplies one. Two calls with the same password therefore produce two
    different digests, and both verify -- which is the property a deterministic
    salt would destroy.
    """
    return _HASHER.hash(password)


# Built at import from a throwaway random string nobody keeps. Its only job is
# to give :func:`verificar` something real to work against when the account does
# not exist. It is not a credential: no password verifies against it, because
# the string it came from is discarded on the next line.
_HASH_DUMMY = _HASHER.hash(secrets.token_urlsafe(32))


def verificar(hash_almacenado: str | None, password: str) -> bool:
    """Whether ``password`` matches ``hash_almacenado``. ``None`` never shortcuts.

    Returns a boolean and raises nothing the caller has to catch:

    * a mismatch is ``False``;
    * a stored value that is not a valid Argon2 digest is ``False`` -- the
      dataset's old placeholder, a truncated column, anything -- because a
      corrupt digest cannot authenticate anybody and is not the caller's
      emergency;
    * ``None`` -- no such account -- verifies against the dummy and is ``False``.

    Neither the password nor the digest is logged, formatted into a message or
    attached to a return value. The only thing that leaves here is a boolean.
    """
    referencia = _HASH_DUMMY if hash_almacenado is None else hash_almacenado
    try:
        _HASHER.verify(referencia, password)
    except (InvalidHashError, Argon2Error):
        return False
    # A dummy verification can never be reported as a success: it is only ever
    # reached with ``hash_almacenado is None``, and there is no account behind it.
    return hash_almacenado is not None
