"""create initial operational schema

Deploys the 22 operational tables of FetalAlert into the PostgreSQL
``operacional`` schema: primary keys, foreign keys with their ON DELETE policy,
UNIQUE and CHECK constraints, explicit indexes and server defaults.

The schema itself is created here rather than assumed to exist. ``CreateSchema``
is issued without ``if_not_exists``: if ``operacional`` already exists the
migration fails loudly instead of silently adopting a schema whose contents are
unknown. ``DropSchema`` on downgrade is likewise plain -- no CASCADE -- so it can
only succeed once every table this migration created has been dropped, and it
refuses to take any object it did not create with it.

The schema name is written as a literal instead of importing
``app.db.base.SCHEMA_OPERACIONAL``: a migration must keep describing the DDL it
actually applied, even if the application constant is renamed later.

Enums are stored as VARCHAR + CHECK (``native_enum=False``), so this revision
issues no CREATE TYPE and needs no ALTER TYPE on downgrade.

Revision ID: 150788f88be7
Revises:
Create Date: 2026-08-15 23:21:32.032638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSchema, DropSchema


# revision identifiers, used by Alembic.
revision: str = '150788f88be7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA_OPERACIONAL = 'operacional'


def upgrade() -> None:
    op.execute(CreateSchema(SCHEMA_OPERACIONAL))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinica',
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('nombre_clinica', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=30), nullable=False),
    sa.Column('provincia', sa.String(length=60), nullable=False),
    sa.Column('distrito', sa.String(length=60), nullable=False),
    sa.Column('corregimiento', sa.String(length=60), nullable=False),
    sa.Column('direccion_fisica', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_clinica', name=op.f('pk_clinica')),
    sa.UniqueConstraint('ruc', name=op.f('uq_clinica_ruc')),
    schema='operacional'
    )
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('nombre_especialidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad', name=op.f('pk_especialidad')),
    sa.UniqueConstraint('nombre_especialidad', name=op.f('uq_especialidad_nombre_especialidad')),
    schema='operacional'
    )
    op.create_table('factor_riesgo',
    sa.Column('id_factor_riesgo', sa.Integer(), nullable=False),
    sa.Column('clave_factor', sa.String(length=50), nullable=False),
    sa.Column('nombre_factor', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_factor_riesgo', name=op.f('pk_factor_riesgo')),
    sa.UniqueConstraint('clave_factor', name=op.f('uq_factor_riesgo_clave_factor')),
    schema='operacional'
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('primer_nombre', sa.String(length=60), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=60), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=60), nullable=False),
    sa.Column('apellido_materno', sa.String(length=60), nullable=True),
    sa.Column('email_pac', sa.String(length=120), nullable=False),
    sa.Column('fecha_nac', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_paciente', name=op.f('pk_paciente')),
    sa.UniqueConstraint('cedula', name=op.f('uq_paciente_cedula')),
    sa.UniqueConstraint('email_pac', name=op.f('uq_paciente_email_pac')),
    schema='operacional'
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.Enum('ADMIN', 'MEDICO', 'PACIENTE', name='nombre_rol', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre_rol', name=op.f('uq_rol_nombre_rol')),
    schema='operacional'
    )
    op.create_table('semaforo',
    sa.Column('id_semaforo', sa.Integer(), nullable=False),
    sa.Column('codigo_nivel', sa.Enum('OK', 'WARNING', 'ERROR', name='codigo_semaforo', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('etiqueta_visual', sa.String(length=60), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('prioridad', sa.SmallInteger(), nullable=False),
    sa.Column('mensaje_app', sa.String(length=255), nullable=False),
    sa.Column('version_referencia', sa.String(length=30), nullable=False),
    sa.CheckConstraint('prioridad BETWEEN 1 AND 3', name=op.f('ck_semaforo_prioridad_rango')),
    sa.PrimaryKeyConstraint('id_semaforo', name=op.f('pk_semaforo')),
    sa.UniqueConstraint('codigo_nivel', name=op.f('uq_semaforo_codigo_nivel')),
    sa.UniqueConstraint('prioridad', name=op.f('uq_semaforo_prioridad')),
    schema='operacional'
    )
    op.create_table('tiempo_gestacional',
    sa.Column('id_tiempo_gest', sa.Integer(), nullable=False),
    sa.Column('semana_gestacion', sa.SmallInteger(), nullable=False),
    sa.Column('mes_gestacion', sa.SmallInteger(), nullable=False),
    sa.Column('trimestre', sa.SmallInteger(), nullable=False),
    sa.Column('grupo_clinico', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint('mes_gestacion BETWEEN 1 AND 10', name=op.f('ck_tiempo_gestacional_mes_rango')),
    sa.CheckConstraint('semana_gestacion BETWEEN 1 AND 42', name=op.f('ck_tiempo_gestacional_semana_rango')),
    sa.CheckConstraint('trimestre BETWEEN 1 AND 3', name=op.f('ck_tiempo_gestacional_trimestre_rango')),
    sa.PrimaryKeyConstraint('id_tiempo_gest', name=op.f('pk_tiempo_gestacional')),
    sa.UniqueConstraint('semana_gestacion', name=op.f('uq_tiempo_gestacional_semana_gestacion')),
    schema='operacional'
    )
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('codigo_dispositivo', sa.String(length=60), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('version_firmware', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'ASIGNADO', 'MANTENIMIENTO', 'INACTIVO', name='estado_dispositivo', native_enum=False, create_constraint=True, length=30), server_default=sa.text("'DISPONIBLE'"), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_clinica'], ['operacional.clinica.id_clinica'], name=op.f('fk_dispositivo_id_clinica_clinica'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_dispositivo', name=op.f('pk_dispositivo')),
    sa.UniqueConstraint('codigo_dispositivo', name=op.f('uq_dispositivo_codigo_dispositivo')),
    schema='operacional'
    )
    op.create_index(op.f('ix_dispositivo_id_clinica'), 'dispositivo', ['id_clinica'], unique=False, schema='operacional')
    op.create_table('embarazo',
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('numero_gestas', sa.SmallInteger(), nullable=False),
    sa.Column('numero_partos', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_probable_parto', sa.Date(), nullable=False),
    sa.Column('estado_embarazo', sa.Enum('ACTIVO', 'FINALIZADO', 'SUSPENDIDO', name='estado_embarazo', native_enum=False, create_constraint=True, length=30), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.CheckConstraint('fecha_cierre IS NULL OR fecha_cierre >= fecha_inicio', name=op.f('ck_embarazo_cierre_posterior_inicio')),
    sa.CheckConstraint('fecha_probable_parto >= fecha_inicio', name=op.f('ck_embarazo_fpp_posterior_inicio')),
    sa.CheckConstraint('numero_gestas >= 1', name=op.f('ck_embarazo_gestas_minimo')),
    sa.CheckConstraint('numero_partos < numero_gestas', name=op.f('ck_embarazo_partos_menor_gestas')),
    sa.CheckConstraint('numero_partos >= 0', name=op.f('ck_embarazo_partos_no_negativo')),
    sa.ForeignKeyConstraint(['id_clinica'], ['operacional.clinica.id_clinica'], name=op.f('fk_embarazo_id_clinica_clinica'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_paciente'], ['operacional.paciente.id_paciente'], name=op.f('fk_embarazo_id_paciente_paciente'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_embarazo', name=op.f('pk_embarazo')),
    schema='operacional'
    )
    op.create_index(op.f('ix_embarazo_id_clinica'), 'embarazo', ['id_clinica'], unique=False, schema='operacional')
    op.create_index(op.f('ix_embarazo_id_paciente'), 'embarazo', ['id_paciente'], unique=False, schema='operacional')
    op.create_table('medico',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=60), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=60), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=60), nullable=False),
    sa.Column('apellido_materno', sa.String(length=60), nullable=True),
    sa.Column('email_med', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['operacional.especialidad.id_especialidad'], name=op.f('fk_medico_id_especialidad_especialidad'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medico', name=op.f('pk_medico')),
    sa.UniqueConstraint('email_med', name=op.f('uq_medico_email_med')),
    schema='operacional'
    )
    op.create_index(op.f('ix_medico_id_especialidad'), 'medico', ['id_especialidad'], unique=False, schema='operacional')
    op.create_table('telefono_paciente',
    sa.Column('id_telefono_paciente', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo_contacto', sa.Enum('CELULAR', 'TELEFONO_DOMICILIO', 'CORREO_ALTERNO', name='tipo_contacto_paciente', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor_contacto', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['operacional.paciente.id_paciente'], name=op.f('fk_telefono_paciente_id_paciente_paciente'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telefono_paciente', name=op.f('pk_telefono_paciente')),
    sa.UniqueConstraint('id_paciente', 'tipo_contacto', 'valor_contacto', name='uq_telefono_paciente_contacto'),
    schema='operacional'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['operacional.rol.id_rol'], name=op.f('fk_usuario_id_rol_rol'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email')),
    schema='operacional'
    )
    op.create_index(op.f('ix_usuario_id_rol'), 'usuario', ['id_rol'], unique=False, schema='operacional')
    op.create_table('asignacion_dispositivo',
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name=op.f('ck_asignacion_dispositivo_fechas_coherentes')),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['operacional.dispositivo.id_dispositivo'], name=op.f('fk_asignacion_dispositivo_id_dispositivo_dispositivo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_embarazo'], ['operacional.embarazo.id_embarazo'], name=op.f('fk_asignacion_dispositivo_id_embarazo_embarazo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_asignacion', name=op.f('pk_asignacion_dispositivo')),
    sa.UniqueConstraint('id_dispositivo', 'id_embarazo', 'fecha_inicio', name='uq_asignacion_dispositivo_periodo'),
    schema='operacional'
    )
    op.create_index(op.f('ix_asignacion_dispositivo_id_embarazo'), 'asignacion_dispositivo', ['id_embarazo'], unique=False, schema='operacional')
    op.create_table('auditoria_log',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('nombre_entidad_afectada', sa.String(length=80), nullable=True),
    sa.Column('id_entidad_afectada', sa.String(length=255), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['operacional.usuario.id_usuario'], name=op.f('fk_auditoria_log_id_usuario_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_log', name=op.f('pk_auditoria_log')),
    schema='operacional'
    )
    op.create_index(op.f('ix_auditoria_log_id_usuario'), 'auditoria_log', ['id_usuario'], unique=False, schema='operacional')
    op.create_table('embarazo_factor_riesgo',
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('id_factor_riesgo', sa.Integer(), nullable=False),
    sa.Column('fecha_diagnostico', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_diagnostico', name=op.f('ck_embarazo_factor_riesgo_fechas_coherentes')),
    sa.ForeignKeyConstraint(['id_embarazo'], ['operacional.embarazo.id_embarazo'], name=op.f('fk_embarazo_factor_riesgo_id_embarazo_embarazo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_factor_riesgo'], ['operacional.factor_riesgo.id_factor_riesgo'], name=op.f('fk_embarazo_factor_riesgo_id_factor_riesgo_factor_riesgo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_embarazo', 'id_factor_riesgo', name=op.f('pk_embarazo_factor_riesgo')),
    schema='operacional'
    )
    op.create_table('medico_clinica',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_final', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('fecha_final IS NULL OR fecha_final >= fecha_inicio', name=op.f('ck_medico_clinica_fechas_coherentes')),
    sa.ForeignKeyConstraint(['id_clinica'], ['operacional.clinica.id_clinica'], name=op.f('fk_medico_clinica_id_clinica_clinica'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medico'], ['operacional.medico.id_medico'], name=op.f('fk_medico_clinica_id_medico_medico'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medico', 'id_clinica', name=op.f('pk_medico_clinica')),
    schema='operacional'
    )
    op.create_table('seguimiento_clinico',
    sa.Column('id_seguimiento', sa.Integer(), nullable=False),
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('rol_seguimiento', sa.Enum('PRINCIPAL', 'APOYO', 'REEMPLAZO', name='rol_seguimiento', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_asignacion', name=op.f('ck_seguimiento_clinico_fechas_coherentes')),
    sa.ForeignKeyConstraint(['id_embarazo'], ['operacional.embarazo.id_embarazo'], name=op.f('fk_seguimiento_clinico_id_embarazo_embarazo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_medico'], ['operacional.medico.id_medico'], name=op.f('fk_seguimiento_clinico_id_medico_medico'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_seguimiento', name=op.f('pk_seguimiento_clinico')),
    schema='operacional'
    )
    op.create_index(op.f('ix_seguimiento_clinico_id_embarazo'), 'seguimiento_clinico', ['id_embarazo'], unique=False, schema='operacional')
    op.create_index(op.f('ix_seguimiento_clinico_id_medico'), 'seguimiento_clinico', ['id_medico'], unique=False, schema='operacional')
    op.create_table('sesion_monitoreo',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('tipo_sesion', sa.Enum('SIGNOS_MATERNOS', 'MOVIMIENTOS_FETALES', name='tipo_sesion', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_sesion', sa.Enum('PENDIENTE', 'COMPLETADA', 'INTERRUMPIDA', 'PROCESADA', name='estado_sesion', native_enum=False, create_constraint=True, length=30), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('origen_dato', sa.Enum('DISPOSITIVO', 'CSV', name='origen_dato', native_enum=False, create_constraint=True, length=30), server_default=sa.text("'DISPOSITIVO'"), nullable=False),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name=op.f('ck_sesion_monitoreo_fechas_coherentes')),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['operacional.dispositivo.id_dispositivo'], name=op.f('fk_sesion_monitoreo_id_dispositivo_dispositivo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_embarazo'], ['operacional.embarazo.id_embarazo'], name=op.f('fk_sesion_monitoreo_id_embarazo_embarazo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_sesion', name=op.f('pk_sesion_monitoreo')),
    schema='operacional'
    )
    op.create_index(op.f('ix_sesion_monitoreo_id_dispositivo'), 'sesion_monitoreo', ['id_dispositivo'], unique=False, schema='operacional')
    op.create_index(op.f('ix_sesion_monitoreo_id_embarazo'), 'sesion_monitoreo', ['id_embarazo'], unique=False, schema='operacional')
    op.create_table('telefono_medico',
    sa.Column('id_telefono_medico', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('tipo_contacto', sa.Enum('CELULAR', 'TELEFONO_DOMICILIO', 'CORREO_ALTERNO', name='tipo_contacto_medico', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor_contacto', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['operacional.medico.id_medico'], name=op.f('fk_telefono_medico_id_medico_medico'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telefono_medico', name=op.f('pk_telefono_medico')),
    sa.UniqueConstraint('id_medico', 'tipo_contacto', 'valor_contacto', name='uq_telefono_medico_contacto'),
    schema='operacional'
    )
    op.create_table('usuario_medico',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['operacional.medico.id_medico'], name=op.f('fk_usuario_medico_id_medico_medico'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['operacional.usuario.id_usuario'], name=op.f('fk_usuario_medico_id_usuario_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuario_medico')),
    sa.UniqueConstraint('id_medico', name=op.f('uq_usuario_medico_id_medico')),
    schema='operacional'
    )
    op.create_table('usuario_paciente',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['operacional.paciente.id_paciente'], name=op.f('fk_usuario_paciente_id_paciente_paciente'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['operacional.usuario.id_usuario'], name=op.f('fk_usuario_paciente_id_usuario_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuario_paciente')),
    sa.UniqueConstraint('id_paciente', name=op.f('uq_usuario_paciente_id_paciente')),
    schema='operacional'
    )
    op.create_table('lectura_biometrica',
    sa.Column('id_lectura', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_tiempo_gest', sa.Integer(), nullable=False),
    sa.Column('id_semaforo', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_captura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_sincronizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_valor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spo2_valor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mov_valor', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('(hr_valor IS NOT NULL AND spo2_valor IS NOT NULL AND mov_valor IS NULL) OR (mov_valor IS NOT NULL AND hr_valor IS NULL AND spo2_valor IS NULL)', name=op.f('ck_lectura_biometrica_forma_valida')),
    sa.CheckConstraint('fecha_hora_sincronizacion IS NULL OR fecha_hora_sincronizacion >= fecha_hora_captura', name=op.f('ck_lectura_biometrica_sincronizacion_posterior')),
    sa.CheckConstraint('hr_valor IS NULL OR hr_valor > 0', name=op.f('ck_lectura_biometrica_hr_positiva')),
    sa.CheckConstraint('mov_valor IS NULL OR mov_valor >= 0', name=op.f('ck_lectura_biometrica_mov_no_negativo')),
    sa.CheckConstraint('spo2_valor IS NULL OR (spo2_valor >= 0 AND spo2_valor <= 100)', name=op.f('ck_lectura_biometrica_spo2_rango')),
    sa.ForeignKeyConstraint(['id_semaforo'], ['operacional.semaforo.id_semaforo'], name=op.f('fk_lectura_biometrica_id_semaforo_semaforo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_sesion'], ['operacional.sesion_monitoreo.id_sesion'], name=op.f('fk_lectura_biometrica_id_sesion_sesion_monitoreo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tiempo_gest'], ['operacional.tiempo_gestacional.id_tiempo_gest'], name=op.f('fk_lectura_biometrica_id_tiempo_gest_tiempo_gestacional'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_lectura', name=op.f('pk_lectura_biometrica')),
    sa.UniqueConstraint('id_sesion', name=op.f('uq_lectura_biometrica_id_sesion')),
    schema='operacional'
    )
    op.create_index(op.f('ix_lectura_biometrica_id_semaforo'), 'lectura_biometrica', ['id_semaforo'], unique=False, schema='operacional')
    op.create_index(op.f('ix_lectura_biometrica_id_tiempo_gest'), 'lectura_biometrica', ['id_tiempo_gest'], unique=False, schema='operacional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectura_biometrica_id_tiempo_gest'), table_name='lectura_biometrica', schema='operacional')
    op.drop_index(op.f('ix_lectura_biometrica_id_semaforo'), table_name='lectura_biometrica', schema='operacional')
    op.drop_table('lectura_biometrica', schema='operacional')
    op.drop_table('usuario_paciente', schema='operacional')
    op.drop_table('usuario_medico', schema='operacional')
    op.drop_table('telefono_medico', schema='operacional')
    op.drop_index(op.f('ix_sesion_monitoreo_id_embarazo'), table_name='sesion_monitoreo', schema='operacional')
    op.drop_index(op.f('ix_sesion_monitoreo_id_dispositivo'), table_name='sesion_monitoreo', schema='operacional')
    op.drop_table('sesion_monitoreo', schema='operacional')
    op.drop_index(op.f('ix_seguimiento_clinico_id_medico'), table_name='seguimiento_clinico', schema='operacional')
    op.drop_index(op.f('ix_seguimiento_clinico_id_embarazo'), table_name='seguimiento_clinico', schema='operacional')
    op.drop_table('seguimiento_clinico', schema='operacional')
    op.drop_table('medico_clinica', schema='operacional')
    op.drop_table('embarazo_factor_riesgo', schema='operacional')
    op.drop_index(op.f('ix_auditoria_log_id_usuario'), table_name='auditoria_log', schema='operacional')
    op.drop_table('auditoria_log', schema='operacional')
    op.drop_index(op.f('ix_asignacion_dispositivo_id_embarazo'), table_name='asignacion_dispositivo', schema='operacional')
    op.drop_table('asignacion_dispositivo', schema='operacional')
    op.drop_index(op.f('ix_usuario_id_rol'), table_name='usuario', schema='operacional')
    op.drop_table('usuario', schema='operacional')
    op.drop_table('telefono_paciente', schema='operacional')
    op.drop_index(op.f('ix_medico_id_especialidad'), table_name='medico', schema='operacional')
    op.drop_table('medico', schema='operacional')
    op.drop_index(op.f('ix_embarazo_id_paciente'), table_name='embarazo', schema='operacional')
    op.drop_index(op.f('ix_embarazo_id_clinica'), table_name='embarazo', schema='operacional')
    op.drop_table('embarazo', schema='operacional')
    op.drop_index(op.f('ix_dispositivo_id_clinica'), table_name='dispositivo', schema='operacional')
    op.drop_table('dispositivo', schema='operacional')
    op.drop_table('tiempo_gestacional', schema='operacional')
    op.drop_table('semaforo', schema='operacional')
    op.drop_table('rol', schema='operacional')
    op.drop_table('paciente', schema='operacional')
    op.drop_table('factor_riesgo', schema='operacional')
    op.drop_table('especialidad', schema='operacional')
    op.drop_table('clinica', schema='operacional')
    # ### end Alembic commands ###
    # Last, and only once the 22 tables above are gone: a plain DROP SCHEMA
    # (no CASCADE) errors out if anything else still lives in ``operacional``.
    op.execute(DropSchema(SCHEMA_OPERACIONAL))
