"""create analytic star schema

Deploys the dimensional model of FetalAlert (SCRUM-69) into its own PostgreSQL
schema, ``analitico``: the nine structures of the approved star schema --
``fact_lectura_biometrica``, seven dimensions and the bridge between pregnancies
and risk factors -- with their primary keys, foreign keys, UNIQUE and CHECK
constraints and the indexes the fact is joined through.

Nothing in ``operacional`` is touched. No analytic table references an
operational one: the warehouse is fed by the ETL and traced back to its source
through the copied operational keys, never through a foreign key that would tie
it to the transactional life cycle.

The schema is created here, without ``IF NOT EXISTS``: if ``analitico`` already
exists the migration fails loudly instead of adopting a schema whose contents
are unknown. The downgrade drops the fact, the bridge and the dimensions in
reverse order of their foreign keys and then the schema, with a plain
``DROP SCHEMA`` -- no CASCADE -- so it refuses to take with it anything this
revision did not create.

The schema name is written as a literal instead of importing
``app.db.base_analitica.SCHEMA_ANALITICO``, for the same reason as in the first
revision: a migration must keep describing the DDL it applied.

Two foreign keys are named explicitly, because the naming convention would
produce 71 and 67 characters and PostgreSQL silently truncates identifiers at
63. Every primary key reuses the operational identifier and owns no sequence.

Revision ID: 60facdbacf51
Revises: 87d8ed46686b
Create Date: 2026-09-11 13:54:10.342550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSchema, DropSchema


# revision identifiers, used by Alembic.
revision: str = '60facdbacf51'
down_revision: Union[str, None] = '87d8ed46686b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA_ANALITICO = 'analitico'


def upgrade() -> None:
    op.execute(CreateSchema(SCHEMA_ANALITICO))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_clinica',
    sa.Column('id_clinica', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre_clinica', sa.String(length=150), nullable=False),
    sa.Column('provincia', sa.String(length=60), nullable=False),
    sa.Column('distrito', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_clinica', name=op.f('pk_dim_clinica')),
    schema=SCHEMA_ANALITICO
    )
    op.create_table('dim_factor_riesgo',
    sa.Column('id_factor_riesgo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('clave_factor', sa.String(length=50), nullable=False),
    sa.Column('nombre_factor', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_factor_riesgo', name=op.f('pk_dim_factor_riesgo')),
    sa.UniqueConstraint('clave_factor', name=op.f('uq_dim_factor_riesgo_clave_factor')),
    schema=SCHEMA_ANALITICO
    )
    op.create_table('dim_semaforo',
    sa.Column('id_semaforo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('codigo_nivel', sa.String(length=7), nullable=False),
    sa.Column('etiqueta_visual', sa.String(length=60), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('mensaje_app', sa.String(length=255), nullable=False),
    sa.Column('version_referencia', sa.String(length=30), nullable=False),
    sa.CheckConstraint("codigo_nivel IN ('OK', 'WARNING', 'ERROR')", name=op.f('ck_dim_semaforo_codigo_nivel_valido')),
    sa.CheckConstraint('prioridad BETWEEN 1 AND 3', name=op.f('ck_dim_semaforo_prioridad_rango')),
    sa.PrimaryKeyConstraint('id_semaforo', name=op.f('pk_dim_semaforo')),
    sa.UniqueConstraint('codigo_nivel', name=op.f('uq_dim_semaforo_codigo_nivel')),
    sa.UniqueConstraint('prioridad', name=op.f('uq_dim_semaforo_prioridad')),
    schema=SCHEMA_ANALITICO
    )
    op.create_table('dim_tiempo_gestacional',
    sa.Column('id_tiempo_gest', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('semana_gestacion', sa.Integer(), nullable=False),
    sa.Column('mes_gestacion', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint('mes_gestacion BETWEEN 1 AND 10', name=op.f('ck_dim_tiempo_gestacional_mes_rango')),
    sa.CheckConstraint('semana_gestacion BETWEEN 1 AND 42', name=op.f('ck_dim_tiempo_gestacional_semana_rango')),
    sa.CheckConstraint('trimestre BETWEEN 1 AND 3', name=op.f('ck_dim_tiempo_gestacional_trimestre_rango')),
    sa.PrimaryKeyConstraint('id_tiempo_gest', name=op.f('pk_dim_tiempo_gestacional')),
    sa.UniqueConstraint('semana_gestacion', name=op.f('uq_dim_tiempo_gestacional_semana_gestacion')),
    schema=SCHEMA_ANALITICO
    )
    op.create_table('dim_medico',
    sa.Column('id_medico', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=True),
    sa.Column('nombre_completo', sa.String(length=243), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('email_med', sa.String(length=120), nullable=False),
    sa.Column('telefono_med', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['analitico.dim_clinica.id_clinica'], name=op.f('fk_dim_medico_id_clinica_dim_clinica'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medico', name=op.f('pk_dim_medico')),
    schema=SCHEMA_ANALITICO
    )
    op.create_index(op.f('ix_dim_medico_id_clinica'), 'dim_medico', ['id_clinica'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_table('dim_paciente',
    sa.Column('id_paciente', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=243), nullable=False),
    sa.Column('telefono_pac', sa.String(length=120), nullable=True),
    sa.Column('fecha_nac', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_clinica'], ['analitico.dim_clinica.id_clinica'], name=op.f('fk_dim_paciente_id_clinica_dim_clinica'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_paciente', name=op.f('pk_dim_paciente')),
    schema=SCHEMA_ANALITICO
    )
    op.create_index(op.f('ix_dim_paciente_id_clinica'), 'dim_paciente', ['id_clinica'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_table('dim_embarazo',
    sa.Column('id_embarazo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('numero_gestas', sa.Integer(), nullable=False),
    sa.Column('numero_partos', sa.Integer(), nullable=False),
    sa.Column('estado_embarazo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_probable_parto', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('duracion_est_semanas', sa.Integer(), nullable=False),
    sa.Column('clasificacion_embarazo', sa.String(length=20), nullable=True),
    sa.CheckConstraint("estado_embarazo IN ('ACTIVO', 'FINALIZADO', 'SUSPENDIDO')", name=op.f('ck_dim_embarazo_estado_embarazo_valido')),
    sa.CheckConstraint('duracion_est_semanas >= 0', name=op.f('ck_dim_embarazo_duracion_no_negativa')),
    sa.ForeignKeyConstraint(['id_paciente'], ['analitico.dim_paciente.id_paciente'], name=op.f('fk_dim_embarazo_id_paciente_dim_paciente'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_embarazo', name=op.f('pk_dim_embarazo')),
    schema=SCHEMA_ANALITICO
    )
    op.create_index(op.f('ix_dim_embarazo_id_paciente'), 'dim_embarazo', ['id_paciente'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_table('bridge_embarazo_factor_riesgo',
    sa.Column('id_embarazo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_factor_riesgo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fecha_diagnostico', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_embarazo'], ['analitico.dim_embarazo.id_embarazo'], name=op.f('fk_bridge_embarazo_factor_riesgo_id_embarazo_dim_embarazo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_factor_riesgo'], ['analitico.dim_factor_riesgo.id_factor_riesgo'], name=op.f('fk_bridge_embarazo_factor_id_factor_riesgo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_embarazo', 'id_factor_riesgo', name=op.f('pk_bridge_embarazo_factor_riesgo')),
    schema=SCHEMA_ANALITICO
    )
    op.create_index(op.f('ix_bridge_embarazo_factor_riesgo_id_factor_riesgo'), 'bridge_embarazo_factor_riesgo', ['id_factor_riesgo'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_table('fact_lectura_biometrica',
    sa.Column('id_lectura', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('id_tiempo_gestacional', sa.Integer(), nullable=False),
    sa.Column('id_embarazo', sa.Integer(), nullable=False),
    sa.Column('id_semaforo', sa.Integer(), nullable=False),
    sa.Column('hr_valor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spo2_valor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mov_valor', sa.Integer(), nullable=True),
    sa.Column('estado_hr', sa.String(length=10), nullable=True),
    sa.Column('estado_spo2', sa.String(length=10), nullable=True),
    sa.Column('estado_mov', sa.String(length=10), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado_hr IS NULL OR estado_hr IN ('OK', 'WARNING', 'ERROR')", name=op.f('ck_fact_lectura_biometrica_estado_hr_valido')),
    sa.CheckConstraint("estado_mov IS NULL OR estado_mov IN ('OK', 'WARNING', 'ERROR')", name=op.f('ck_fact_lectura_biometrica_estado_mov_valido')),
    sa.CheckConstraint("estado_spo2 IS NULL OR estado_spo2 IN ('OK', 'WARNING', 'ERROR')", name=op.f('ck_fact_lectura_biometrica_estado_spo2_valido')),
    sa.CheckConstraint('(hr_valor IS NOT NULL AND spo2_valor IS NOT NULL AND mov_valor IS NULL AND estado_hr IS NOT NULL AND estado_spo2 IS NOT NULL AND estado_mov IS NULL) OR (mov_valor IS NOT NULL AND hr_valor IS NULL AND spo2_valor IS NULL AND estado_mov IS NOT NULL AND estado_hr IS NULL AND estado_spo2 IS NULL)', name=op.f('ck_fact_lectura_biometrica_forma_valida')),
    sa.ForeignKeyConstraint(['id_clinica'], ['analitico.dim_clinica.id_clinica'], name=op.f('fk_fact_lectura_biometrica_id_clinica_dim_clinica'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_embarazo'], ['analitico.dim_embarazo.id_embarazo'], name=op.f('fk_fact_lectura_biometrica_id_embarazo_dim_embarazo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_medico'], ['analitico.dim_medico.id_medico'], name=op.f('fk_fact_lectura_biometrica_id_medico_dim_medico'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_paciente'], ['analitico.dim_paciente.id_paciente'], name=op.f('fk_fact_lectura_biometrica_id_paciente_dim_paciente'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_semaforo'], ['analitico.dim_semaforo.id_semaforo'], name=op.f('fk_fact_lectura_biometrica_id_semaforo_dim_semaforo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tiempo_gestacional'], ['analitico.dim_tiempo_gestacional.id_tiempo_gest'], name=op.f('fk_fact_lectura_id_tiempo_gestacional'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_lectura', name=op.f('pk_fact_lectura_biometrica')),
    schema=SCHEMA_ANALITICO
    )
    op.create_index(op.f('ix_fact_lectura_biometrica_id_clinica'), 'fact_lectura_biometrica', ['id_clinica'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_embarazo'), 'fact_lectura_biometrica', ['id_embarazo'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_medico'), 'fact_lectura_biometrica', ['id_medico'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_paciente'), 'fact_lectura_biometrica', ['id_paciente'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_semaforo'), 'fact_lectura_biometrica', ['id_semaforo'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_sesion'), 'fact_lectura_biometrica', ['id_sesion'], unique=False, schema=SCHEMA_ANALITICO)
    op.create_index(op.f('ix_fact_lectura_biometrica_id_tiempo_gestacional'), 'fact_lectura_biometrica', ['id_tiempo_gestacional'], unique=False, schema=SCHEMA_ANALITICO)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_tiempo_gestacional'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_sesion'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_semaforo'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_paciente'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_medico'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_embarazo'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_fact_lectura_biometrica_id_clinica'), table_name='fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_table('fact_lectura_biometrica', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_bridge_embarazo_factor_riesgo_id_factor_riesgo'), table_name='bridge_embarazo_factor_riesgo', schema=SCHEMA_ANALITICO)
    op.drop_table('bridge_embarazo_factor_riesgo', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_dim_embarazo_id_paciente'), table_name='dim_embarazo', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_embarazo', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_dim_paciente_id_clinica'), table_name='dim_paciente', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_paciente', schema=SCHEMA_ANALITICO)
    op.drop_index(op.f('ix_dim_medico_id_clinica'), table_name='dim_medico', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_medico', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_tiempo_gestacional', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_semaforo', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_factor_riesgo', schema=SCHEMA_ANALITICO)
    op.drop_table('dim_clinica', schema=SCHEMA_ANALITICO)
    # ### end Alembic commands ###
    # Last, and only once the nine tables above are gone: a plain DROP SCHEMA
    # (no CASCADE) errors out if anything else still lives in ``analitico``.
    op.execute(DropSchema(SCHEMA_ANALITICO))
